//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SustitucionMOAWS.HomeNGWebServiceMOA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:OPERACIONES", ConfigurationName="HomeNGWebServiceMOA.SI_MPMF_MOAOP_HOME_NG")]
    public interface SI_MPMF_MOAOP_HOME_NG {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:sap-com:document:sap:rfc:functions) of message SI_MPMF_MOAOP_HOME_NGRequest does not match the default value (urn:OPERACIONES)
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SustitucionMOAWS.HomeNGWebServiceMOA.SI_MPMF_MOAOP_HOME_NGResponse SI_MPMF_MOAOP_HOME_NG(SustitucionMOAWS.HomeNGWebServiceMOA.SI_MPMF_MOAOP_HOME_NGRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SustitucionMOAWS.HomeNGWebServiceMOA.SI_MPMF_MOAOP_HOME_NGResponse> SI_MPMF_MOAOP_HOME_NGAsync(SustitucionMOAWS.HomeNGWebServiceMOA.SI_MPMF_MOAOP_HOME_NGRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES4100 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fECHA_OPField;
        
        private string fECHA_OP_HASTAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FECHA_OP {
            get {
                return this.fECHA_OPField;
            }
            set {
                this.fECHA_OPField = value;
                this.RaisePropertyChanged("FECHA_OP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string FECHA_OP_HASTA {
            get {
                return this.fECHA_OP_HASTAField;
            }
            set {
                this.fECHA_OP_HASTAField = value;
                this.RaisePropertyChanged("FECHA_OP_HASTA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES4550 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dESCRIPCIONField;
        
        private decimal cANTIDADField;
        
        private bool cANTIDADFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
                this.RaisePropertyChanged("DESCRIPCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal CANTIDAD {
            get {
                return this.cANTIDADField;
            }
            set {
                this.cANTIDADField = value;
                this.RaisePropertyChanged("CANTIDAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CANTIDADSpecified {
            get {
                return this.cANTIDADFieldSpecified;
            }
            set {
                this.cANTIDADFieldSpecified = value;
                this.RaisePropertyChanged("CANTIDADSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MPMF_MOAOP_HOME_NG", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MPMF_MOAOP_HOME_NGRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.HomeNGWebServiceMOA.ZMPES4100[] PE_FECHA_IN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PE_PROVEEDOR;
        
        public SI_MPMF_MOAOP_HOME_NGRequest() {
        }
        
        public SI_MPMF_MOAOP_HOME_NGRequest(SustitucionMOAWS.HomeNGWebServiceMOA.ZMPES4100[] PE_FECHA_IN, string PE_PROVEEDOR) {
            this.PE_FECHA_IN = PE_FECHA_IN;
            this.PE_PROVEEDOR = PE_PROVEEDOR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MPMF_MOAOP_HOME_NG.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MPMF_MOAOP_HOME_NGResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.HomeNGWebServiceMOA.ZMPES4550[] T_SALIDA;
        
        public SI_MPMF_MOAOP_HOME_NGResponse() {
        }
        
        public SI_MPMF_MOAOP_HOME_NGResponse(SustitucionMOAWS.HomeNGWebServiceMOA.ZMPES4550[] T_SALIDA) {
            this.T_SALIDA = T_SALIDA;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_MPMF_MOAOP_HOME_NGChannel : SustitucionMOAWS.HomeNGWebServiceMOA.SI_MPMF_MOAOP_HOME_NG, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_MPMF_MOAOP_HOME_NGClient : System.ServiceModel.ClientBase<SustitucionMOAWS.HomeNGWebServiceMOA.SI_MPMF_MOAOP_HOME_NG>, SustitucionMOAWS.HomeNGWebServiceMOA.SI_MPMF_MOAOP_HOME_NG {
        
        public SI_MPMF_MOAOP_HOME_NGClient() {
        }
        
        public SI_MPMF_MOAOP_HOME_NGClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_MPMF_MOAOP_HOME_NGClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MPMF_MOAOP_HOME_NGClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MPMF_MOAOP_HOME_NGClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SustitucionMOAWS.HomeNGWebServiceMOA.SI_MPMF_MOAOP_HOME_NGResponse SustitucionMOAWS.HomeNGWebServiceMOA.SI_MPMF_MOAOP_HOME_NG.SI_MPMF_MOAOP_HOME_NG(SustitucionMOAWS.HomeNGWebServiceMOA.SI_MPMF_MOAOP_HOME_NGRequest request) {
            return base.Channel.SI_MPMF_MOAOP_HOME_NG(request);
        }
        
        public SustitucionMOAWS.HomeNGWebServiceMOA.ZMPES4550[] SI_MPMF_MOAOP_HOME_NG(SustitucionMOAWS.HomeNGWebServiceMOA.ZMPES4100[] PE_FECHA_IN, string PE_PROVEEDOR) {
            SustitucionMOAWS.HomeNGWebServiceMOA.SI_MPMF_MOAOP_HOME_NGRequest inValue = new SustitucionMOAWS.HomeNGWebServiceMOA.SI_MPMF_MOAOP_HOME_NGRequest();
            inValue.PE_FECHA_IN = PE_FECHA_IN;
            inValue.PE_PROVEEDOR = PE_PROVEEDOR;
            SustitucionMOAWS.HomeNGWebServiceMOA.SI_MPMF_MOAOP_HOME_NGResponse retVal = ((SustitucionMOAWS.HomeNGWebServiceMOA.SI_MPMF_MOAOP_HOME_NG)(this)).SI_MPMF_MOAOP_HOME_NG(inValue);
            return retVal.T_SALIDA;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SustitucionMOAWS.HomeNGWebServiceMOA.SI_MPMF_MOAOP_HOME_NGResponse> SustitucionMOAWS.HomeNGWebServiceMOA.SI_MPMF_MOAOP_HOME_NG.SI_MPMF_MOAOP_HOME_NGAsync(SustitucionMOAWS.HomeNGWebServiceMOA.SI_MPMF_MOAOP_HOME_NGRequest request) {
            return base.Channel.SI_MPMF_MOAOP_HOME_NGAsync(request);
        }
        
        public System.Threading.Tasks.Task<SustitucionMOAWS.HomeNGWebServiceMOA.SI_MPMF_MOAOP_HOME_NGResponse> SI_MPMF_MOAOP_HOME_NGAsync(SustitucionMOAWS.HomeNGWebServiceMOA.ZMPES4100[] PE_FECHA_IN, string PE_PROVEEDOR) {
            SustitucionMOAWS.HomeNGWebServiceMOA.SI_MPMF_MOAOP_HOME_NGRequest inValue = new SustitucionMOAWS.HomeNGWebServiceMOA.SI_MPMF_MOAOP_HOME_NGRequest();
            inValue.PE_FECHA_IN = PE_FECHA_IN;
            inValue.PE_PROVEEDOR = PE_PROVEEDOR;
            return ((SustitucionMOAWS.HomeNGWebServiceMOA.SI_MPMF_MOAOP_HOME_NG)(this)).SI_MPMF_MOAOP_HOME_NGAsync(inValue);
        }
    }
}
