CREATE TABLE [dbo].[Area](
	[ID_Area] [int] IDENTITY(1,1) NOT NULL,
	[NombreArea] [nvarchar](max) NOT NULL,
	[Descripcion] [nvarchar](max) NOT NULL
	CONSTRAINT [PK_dbo.Area] PRIMARY KEY CLUSTERED 
(
	[ID_Area] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO