CREATE TABLE [dbo].[CampoProveedor]
(
    [CampoCosecha_Id] INT NOT NULL,
    [Proveedor_Id] INT NOT NULL,
    [HectareasTotales] FLOAT NOT NULL,
    [HectareasSoja] FLOAT NOT NULL,
    [Longitud] NVARCHAR(30) NOT NULL,
    [Latitud] NVARCHAR(30) NOT NULL,
    [Archivo_Id] INT NOT NULL,
    [FechaCreacion] DATETIME NULL, 
    [FechaModificacion] DATETIME NULL, 
    [Borrado] BIT NULL, 
    [CUIT] NVARCHAR(15) NULL, 
    [RazonSocial] NVARCHAR(500) NULL, 
    [HectareasTotalesUcropit] FLOAT NULL DEFAULT NULL,
    [HectareasSojaUcropit] FLOAT NULL DEFAULT NULL,
    [BSVS2] BIT NOT NULL DEFAULT 1, 
    [EPA] BIT NOT NULL DEFAULT 0, 
    [EUDR] BIT NOT NULL DEFAULT 0, 
    [EvidenciaEPA_Id] INT NULL, 
    [EvidenciaPresentada] BIT NOT NULL DEFAULT 0, 
    [CampoCosechaSuperposicion_Id] INT NULL, 
    PRIMARY KEY(CampoCosecha_Id, Proveedor_Id),
    CONSTRAINT [FK_CampoProveedor_ToArchivo] FOREIGN KEY ([Archivo_Id]) REFERENCES [Archivo]([Id]),
    CONSTRAINT [FK_CampoProveedor_ToCampoCosecha] FOREIGN KEY ([CampoCosecha_Id]) REFERENCES [CampoCosecha]([Id]),
    CONSTRAINT [FK_CampoProveedor_ToProveedor] FOREIGN KEY ([Proveedor_Id]) REFERENCES [Proveedor]([Id]),
    CONSTRAINT [FK_CampoProveedor_ToArchivoEPA] FOREIGN KEY ([EvidenciaEPA_Id]) REFERENCES [Archivo]([Id]),
    CONSTRAINT [FK_CampoProveedor_ToCampoCosechaSuperposicion] FOREIGN KEY ([CampoCosechaSuperposicion_Id]) REFERENCES [CampoCosecha]([Id]),
)
