CREATE TABLE [dbo].[Material]
(
	[Id] INT NOT NULL  IDENTITY(1,1), 
    [Nombre] NVARCHAR(50) NOT NULL
	CONSTRAINT [PK_Material] PRIMARY KEY CLUSTERED
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY], 
    [CodigoSap] NVARCHAR(20) NULL, 
    [TablaSeccionMaterial] INT NULL, 
    [ValidaSisaRuca] BIT NOT NULL DEFAULT 0, 
    [Abreviacion] VARCHAR(50) NULL, 
    [EsDerivadoGranario] BIT NOT NULL DEFAULT 0
) ON [PRIMARY]
GO