CREATE TABLE [dbo].[MaterialFason]
(
	[Id] INT NOT NULL  IDENTITY(1,1), 
    [Nombre] NVARCHAR(50) NOT NULL
	CONSTRAINT [PK_MaterialFason] PRIMARY KEY CLUSTERED
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY], 
    [CodigoSap] NVARCHAR(20) NOT NULL 
) ON [PRIMARY]
GO