CREATE TABLE [dbo].[MonedaConversion]
(
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[MonedaCodigo] [nvarchar](max) NOT NULL,
	[CantidadDecimal] INT NOT NULL
CONSTRAINT [PK_dbo.MonedaConversion] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
