CREATE TABLE [dbo].[OrdenDeCarga]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [Cliente_Id] INT NOT NULL, 
    [FechaCarga] DATETIME NOT NULL, 
    [CUITCliente] VARCHAR(15) NOT NULL, 
    [NombreChofer] VARCHAR(30) NOT NULL, 
    [ApellidoChofer] VARCHAR(30) NOT NULL, 
    [CUITChofer] VARCHAR(15) NOT NULL, 
    [CUITTransporte] VARCHAR(15) NOT NULL, 
    [RazonSocialTransporte] VARCHAR(100) NOT NULL, 
    [Cantidad] INT NOT NULL, 
    [Estado] INT NOT NULL, 
    [ContratoSAP] VARCHAR(15) NULL, 
    [CorredorSeleccionado] BIT NOT NULL, 
    [TransporteExiste] BIT NOT NULL, 
    [Observacion] VARCHAR(MAX) NULL, 
    [PatenteAcoplado] VARCHAR(10) NULL, 
    [ChasisAcoplado] VARCHAR(15) NULL, 
    [Corredor] VARCHAR(150) NULL, 
    [AprobadoCredito] BIT NULL, 
    [InformadaSAP] BIT NULL, 
    [FechaEntregaGenerada] DATETIME NULL, 
    [NumeroPedido] VARCHAR(15) NULL, 
    [ContratoIngresado] VARCHAR(15) NULL, 
    [Producto_Id] INT NULL, 
    [ContratosRespuesta] NVARCHAR(MAX) NULL, 
    [NumeroEntrega] NVARCHAR(MAX) NULL, 
    [NumeroPedidoIngresado] NVARCHAR(MAX) NULL, 
    CONSTRAINT [FK_OrdenDeCarga_Proveedor] FOREIGN KEY (Cliente_Id) REFERENCES Proveedor(Id), 
    CONSTRAINT [FK_OrdenDeCarga_Material] FOREIGN KEY (Producto_Id) REFERENCES Material(Id), 
)
