CREATE TABLE [dbo].[OrdenDeCarga]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [Cliente_Id] INT NOT NULL, 
    [FechaCarga] DATETIME NOT NULL, 
    [CUITCliente] VARCHAR(15) NOT NULL, 
    [NombreChofer] VARCHAR(120) NOT NULL, 
    [CUITChofer] VARCHAR(15) NOT NULL, 
    [CUITTransporte] VARCHAR(15) NOT NULL, 
    [RazonSocialTransporte] VARCHAR(100) NOT NULL, 
    [Cantidad] INT NOT NULL, 
    [Estado] INT NOT NULL, 
    [ContratoSAP] VARCHAR(15) NULL, 
    [CorredorSeleccionado] BIT NOT NULL, 
    [TransporteExiste] BIT NOT NULL, 
    [Observacion] VARCHAR(MAX) NULL, 
    [PatenteAcoplado] VARCHAR(10) NULL, 
    [ChasisAcoplado] VARCHAR(15) NULL, 
    [CodigoCorredor] VARCHAR(150) NULL, 
    [AprobadoCredito] BIT NULL, 
    [InformadaSAP] BIT NULL, 
    [FechaEntregaGenerada] DATETIME NULL, 
    [NumeroPedido] VARCHAR(15) NULL, 
    [ContratoIngresado] VARCHAR(15) NULL, 
    [Producto_Id] INT NULL, 
    [ContratosRespuesta] NVARCHAR(MAX) NULL, 
    [NumeroEntrega] NVARCHAR(MAX) NULL, 
    [NumeroPedidoIngresado] NVARCHAR(MAX) NULL, 
    [CodigoVerificacionSap] VARCHAR(200) NULL, 
    [DescripcionCodigoVerificacionSap] NVARCHAR(MAX) NULL, 
    [PedidosRespuesta] NVARCHAR(MAX) NULL, 
    [ContratoSinCantidadPendiente] BIT NULL , 
    [DescripcionErrorInterno] NVARCHAR(MAX) NULL, 
    [Corredor_Id] INT NULL, 
    [PedidoSAP] NVARCHAR(15) NULL, 
    UsuarioCreacion_Id INT
    CONSTRAINT [FK_OrdenDeCarga_Proveedor] FOREIGN KEY (Cliente_Id) REFERENCES Proveedor(Id) NOT NULL, 
    [CUITCorredor] VARCHAR(15) NULL, 
    [FechaVencimiento] DATETIME NULL, 
    [FechaVencimientoAmpliada] BIT NOT NULL DEFAULT 0, 
    [EdicionRechazada] BIT NOT NULL DEFAULT 0, 
    [CUITDestinatario] VARCHAR(15) NULL, 
    [CUITDestino] VARCHAR(15) NULL, 
    [RazonSocialDestinatario] VARCHAR(100) NULL, 
    [RazonSocialDestino] VARCHAR(100) NULL,
    [Reventa] BIT NOT NULL DEFAULT 0, 
    [CUITIntermediarioFlete] VARCHAR(15) NULL, 
    [RazonSocialIntermediarioFlete] VARCHAR(100) NULL, 
    [PlantaCodigo] VARCHAR(6) NULL, 
    [DomicilioTipo] VARCHAR NULL, 
    [DomicilioOrden] SMALLINT NULL, 
    [DomicilioDescr] VARCHAR(250) NULL,
    [NumeroFactura] VARCHAR(50) NULL,
    [NumeroFacturaSeleccionada] VARCHAR(50) NULL,
    [TipoContrato] INT NOT NULL DEFAULT 0, 
    [Escalable] BIT NOT NULL DEFAULT 0, 
    [DestinatarioExisteScato] BIT NULL, 
    [DestinoExisteScato] BIT NULL, 
    [DestinoMercaderia] VARCHAR(250) NULL, 
    CONSTRAINT [FK_OrdenDeCarga_Material] FOREIGN KEY (Producto_Id) REFERENCES Material(Id),
    CONSTRAINT [FK_OrdenDeCarga_Corredor] FOREIGN KEY (Corredor_Id) REFERENCES Proveedor(Id), 
    CONSTRAINT [FK_OrdenDeCarga_Usuario] FOREIGN KEY (UsuarioCreacion_Id) REFERENCES Usuario(Id), 
)
