CREATE TABLE [dbo].[OrdenDeCargaFason](
	[Id] BIGINT PRIMARY KEY IDENTITY(1,1) NOT NULL, 
	[Estado] INT NOT NULL, 
	[FechaCreacion] DATETIME NOT NULL, 
	[Cantidad] INT DEFAULT 30000 NOT NULL, 
	[PatenteChasis] VARCHAR(15) NOT NULL, 
	[PatenteAcoplado] VARCHAR(15) NOT NULL, 
	[NombreChofer] VARCHAR(120) NOT NULL, 
	[CUILChofer] VARCHAR(15) NOT NULL, 
	[RazonSocialTransporte] VARCHAR(120) NOT NULL, 
	[CUITTransporte] VARCHAR(15) NOT NULL, 
	[Observacion] VARCHAR(MAX) NULL, 
	[Cliente_Id] INT NOT NULL, 
	[Producto_Id] INT NOT NULL,
	[TransporteExiste] BIT NOT NULL DEFAULT 1, 
    [LocalidadId] INT NOT NULL DEFAULT 0, 
    [LocalidadDescripcion] VARCHAR(75) NOT NULL DEFAULT '', 
    [CorredorId] INT NULL, 
	[FechaIngreso] DATETIME , 
    [FechaEgreso] DATETIME , 
    [UniMedCant] VARCHAR(50) , 
    [NroRemito] VARCHAR(50) ,
	[DistanciaEnKm] INT NOT NULL DEFAULT 0,
	[KmARecorrer] VARCHAR(50) ,
    [CUITIntermediarioFlete] VARCHAR(15) NULL,
    [RazonSocialIntermediarioFlete] VARCHAR(100) NULL, 
    [FleteMOA] BIT NOT NULL DEFAULT 0, 
    [ClienteComoRemitenteComercial] BIT NOT NULL DEFAULT 0, 
	[PlantaCodigo] VARCHAR(6) NULL, 
    [DomicilioTipo] VARCHAR NULL, 
    [DomicilioOrden] SMALLINT NULL, 
    [DomicilioDescr] VARCHAR(250) NULL,
	[RazonSocialDestino] VARCHAR(100) NULL,
	[Escalable] BIT NOT NULL DEFAULT 0,
    [CUITDestino] VARCHAR(15) NULL, 
    [CUITDestinatario] VARCHAR(15) NULL, 
    [RazonSocialDestinatario] VARCHAR(100) NULL, 
    [DestinatarioExisteScato] BIT NULL, 
    [DestinoExisteScato] BIT NULL, 
    [DestinoMercaderia] VARCHAR(250) NULL, 
    [PesadaTara] FLOAT NULL, 
    [PesadaNeto] FLOAT NULL, 
    CONSTRAINT [FK_OrdenDeCargaFason_Material] FOREIGN KEY (Producto_Id) REFERENCES Material(Id),
    CONSTRAINT [FK_OrdenDeCargaFason_Cliente] FOREIGN KEY (Cliente_Id) REFERENCES Proveedor(Id), 
    CONSTRAINT [FK_OrdenDeCargaFason_Corredor] FOREIGN KEY (CorredorId) REFERENCES Proveedor(Id), 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
