CREATE TABLE [dbo].[OrdenResiduos]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
    [ClienteId] INT NOT NULL,
    [MaterialId] INT NOT NULL,
    [EstadoId] INT NOT NULL, 
    [FechaCreacion] DATETIME NOT NULL, 
    [PatenteChasis] VARCHAR(15) NOT NULL, 
    [PatenteAcoplado] VARCHAR(15) NULL, 
    [ChoferNombre] VARCHAR(120) NOT NULL, 
    [ChoferApellido] VARCHAR(120) NOT NULL, 
    [ChoferCuil] VARCHAR(15) NOT NULL, 
    [TransporteRazonSocial] VARCHAR(120) NOT NULL, 
    [TransporteCuit] VARCHAR(15) NOT NULL, 
    [Observacion] VARCHAR(MAX) NULL, 
    [LocalidadId] INT NULL, 
    [LocalidadScatoId] INT NOT NULL, 
    [LocalidadScatoDescripcion] VARCHAR(250) NOT NULL,
    [FechaIngreso] DATETIME NULL, 
    [FechaEgreso] DATETIME NULL, 
    [PlantaCodigo] VARCHAR(6) NULL, 
    [DomicilioTipo] VARCHAR NULL, 
    [DomicilioOrden] SMALLINT NULL, 
    [DomicilioDescr] VARCHAR(250) NULL, 
    [AlmacenId] INT NOT NULL, 
    [NroCertificacion] VARCHAR(250) NULL,
    [Balanza] VARCHAR(250) NULL,
    [IdScato] BIGINT,
    [PesadaTara] FLOAT NULL, 
    [PesadaNeto] FLOAT NULL, 
    [PesadaBruto] FLOAT NULL, 
    [UniMedCant] VARCHAR(50) NULL, 
    [MotivoRechazo] VARCHAR(50) NULL,
    [KmsARecorrer] VARCHAR(50),
    CONSTRAINT [FK_OrdenResiduos_ProveedorCliente] FOREIGN KEY ([ClienteId]) REFERENCES [Proveedor]([Id]), 
    CONSTRAINT [FK_OrdenResiduos_Material] FOREIGN KEY ([MaterialId]) REFERENCES [Material]([Id]), 
    CONSTRAINT [FK_OrdenResiduos_EstadoOrdenResiduos] FOREIGN KEY ([EstadoId]) REFERENCES [EstadoOrdenResiduos]([Id]), 
    CONSTRAINT [FK_OrdenResiduos_Almacen] FOREIGN KEY ([AlmacenId]) REFERENCES [Almacen]([Id])
)
