CREATE TABLE [dbo].[PaisesSAP](
	[Codigo] [varchar](3) NOT NULL,
	[DenominacionPais] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_PaisesSAP] PRIMARY KEY CLUSTERED 
(
	[Codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

