CREATE TABLE [dbo].[SecuenciaIngresosBrutosCoeficienteUnificado]
(
	[Id] INT IDENTITY(1,1) NOT NULL, 
	[Descripcion] VARCHAR(100) NOT NULL,
    CONSTRAINT [PK_dbo.SecuenciaIngresosBrutosCoeficienteUnificado] PRIMARY KEY CLUSTERED
	(
		[Id] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
