//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SustitucionMOAWS.PesificacionWebServiceMOA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:OPERACIONES", ConfigurationName="PesificacionWebServiceMOA.SI_MPMF_MOAOP_OBTENER_PEND_USD")]
    public interface SI_MPMF_MOAOP_OBTENER_PEND_USD {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:sap-com:document:sap:rfc:functions) of message SI_MPMF_MOAOP_OBTENER_PEND_USDRequest does not match the default value (urn:OPERACIONES)
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SustitucionMOAWS.PesificacionWebServiceMOA.SI_MPMF_MOAOP_OBTENER_PEND_USDResponse SI_MPMF_MOAOP_OBTENER_PEND_USD(SustitucionMOAWS.PesificacionWebServiceMOA.SI_MPMF_MOAOP_OBTENER_PEND_USDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SustitucionMOAWS.PesificacionWebServiceMOA.SI_MPMF_MOAOP_OBTENER_PEND_USDResponse> SI_MPMF_MOAOP_OBTENER_PEND_USDAsync(SustitucionMOAWS.PesificacionWebServiceMOA.SI_MPMF_MOAOP_OBTENER_PEND_USDRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES5470 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cONTRATOField;
        
        private string fIJACIONField;
        
        private string vENDEDORField;
        
        private string nOM_VENDField;
        
        private decimal cANT_PENDIENTEField;
        
        private bool cANT_PENDIENTEFieldSpecified;
        
        private decimal mONTO_PENDIENTEField;
        
        private bool mONTO_PENDIENTEFieldSpecified;
        
        private decimal pRECIOField;
        
        private bool pRECIOFieldSpecified;
        
        private string uNIDADField;
        
        private string mONEDAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CONTRATO {
            get {
                return this.cONTRATOField;
            }
            set {
                this.cONTRATOField = value;
                this.RaisePropertyChanged("CONTRATO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string FIJACION {
            get {
                return this.fIJACIONField;
            }
            set {
                this.fIJACIONField = value;
                this.RaisePropertyChanged("FIJACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string VENDEDOR {
            get {
                return this.vENDEDORField;
            }
            set {
                this.vENDEDORField = value;
                this.RaisePropertyChanged("VENDEDOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string NOM_VEND {
            get {
                return this.nOM_VENDField;
            }
            set {
                this.nOM_VENDField = value;
                this.RaisePropertyChanged("NOM_VEND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal CANT_PENDIENTE {
            get {
                return this.cANT_PENDIENTEField;
            }
            set {
                this.cANT_PENDIENTEField = value;
                this.RaisePropertyChanged("CANT_PENDIENTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CANT_PENDIENTESpecified {
            get {
                return this.cANT_PENDIENTEFieldSpecified;
            }
            set {
                this.cANT_PENDIENTEFieldSpecified = value;
                this.RaisePropertyChanged("CANT_PENDIENTESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal MONTO_PENDIENTE {
            get {
                return this.mONTO_PENDIENTEField;
            }
            set {
                this.mONTO_PENDIENTEField = value;
                this.RaisePropertyChanged("MONTO_PENDIENTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MONTO_PENDIENTESpecified {
            get {
                return this.mONTO_PENDIENTEFieldSpecified;
            }
            set {
                this.mONTO_PENDIENTEFieldSpecified = value;
                this.RaisePropertyChanged("MONTO_PENDIENTESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal PRECIO {
            get {
                return this.pRECIOField;
            }
            set {
                this.pRECIOField = value;
                this.RaisePropertyChanged("PRECIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PRECIOSpecified {
            get {
                return this.pRECIOFieldSpecified;
            }
            set {
                this.pRECIOFieldSpecified = value;
                this.RaisePropertyChanged("PRECIOSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string UNIDAD {
            get {
                return this.uNIDADField;
            }
            set {
                this.uNIDADField = value;
                this.RaisePropertyChanged("UNIDAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MONEDA {
            get {
                return this.mONEDAField;
            }
            set {
                this.mONEDAField = value;
                this.RaisePropertyChanged("MONEDA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MPMF_MOAOP_OBTENER_PEND_USD", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MPMF_MOAOP_OBTENER_PEND_USDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_PROVEEDOR;
        
        public SI_MPMF_MOAOP_OBTENER_PEND_USDRequest() {
        }
        
        public SI_MPMF_MOAOP_OBTENER_PEND_USDRequest(string IM_PROVEEDOR) {
            this.IM_PROVEEDOR = IM_PROVEEDOR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MPMF_MOAOP_OBTENER_PEND_USD.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MPMF_MOAOP_OBTENER_PEND_USDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.PesificacionWebServiceMOA.ZMPES5470[] EX_CONTRATOS;
        
        public SI_MPMF_MOAOP_OBTENER_PEND_USDResponse() {
        }
        
        public SI_MPMF_MOAOP_OBTENER_PEND_USDResponse(SustitucionMOAWS.PesificacionWebServiceMOA.ZMPES5470[] EX_CONTRATOS) {
            this.EX_CONTRATOS = EX_CONTRATOS;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_MPMF_MOAOP_OBTENER_PEND_USDChannel : SustitucionMOAWS.PesificacionWebServiceMOA.SI_MPMF_MOAOP_OBTENER_PEND_USD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_MPMF_MOAOP_OBTENER_PEND_USDClient : System.ServiceModel.ClientBase<SustitucionMOAWS.PesificacionWebServiceMOA.SI_MPMF_MOAOP_OBTENER_PEND_USD>, SustitucionMOAWS.PesificacionWebServiceMOA.SI_MPMF_MOAOP_OBTENER_PEND_USD {
        
        public SI_MPMF_MOAOP_OBTENER_PEND_USDClient() {
        }
        
        public SI_MPMF_MOAOP_OBTENER_PEND_USDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_MPMF_MOAOP_OBTENER_PEND_USDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MPMF_MOAOP_OBTENER_PEND_USDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MPMF_MOAOP_OBTENER_PEND_USDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SustitucionMOAWS.PesificacionWebServiceMOA.SI_MPMF_MOAOP_OBTENER_PEND_USDResponse SustitucionMOAWS.PesificacionWebServiceMOA.SI_MPMF_MOAOP_OBTENER_PEND_USD.SI_MPMF_MOAOP_OBTENER_PEND_USD(SustitucionMOAWS.PesificacionWebServiceMOA.SI_MPMF_MOAOP_OBTENER_PEND_USDRequest request) {
            return base.Channel.SI_MPMF_MOAOP_OBTENER_PEND_USD(request);
        }
        
        public SustitucionMOAWS.PesificacionWebServiceMOA.ZMPES5470[] SI_MPMF_MOAOP_OBTENER_PEND_USD(string IM_PROVEEDOR) {
            SustitucionMOAWS.PesificacionWebServiceMOA.SI_MPMF_MOAOP_OBTENER_PEND_USDRequest inValue = new SustitucionMOAWS.PesificacionWebServiceMOA.SI_MPMF_MOAOP_OBTENER_PEND_USDRequest();
            inValue.IM_PROVEEDOR = IM_PROVEEDOR;
            SustitucionMOAWS.PesificacionWebServiceMOA.SI_MPMF_MOAOP_OBTENER_PEND_USDResponse retVal = ((SustitucionMOAWS.PesificacionWebServiceMOA.SI_MPMF_MOAOP_OBTENER_PEND_USD)(this)).SI_MPMF_MOAOP_OBTENER_PEND_USD(inValue);
            return retVal.EX_CONTRATOS;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SustitucionMOAWS.PesificacionWebServiceMOA.SI_MPMF_MOAOP_OBTENER_PEND_USDResponse> SustitucionMOAWS.PesificacionWebServiceMOA.SI_MPMF_MOAOP_OBTENER_PEND_USD.SI_MPMF_MOAOP_OBTENER_PEND_USDAsync(SustitucionMOAWS.PesificacionWebServiceMOA.SI_MPMF_MOAOP_OBTENER_PEND_USDRequest request) {
            return base.Channel.SI_MPMF_MOAOP_OBTENER_PEND_USDAsync(request);
        }
        
        public System.Threading.Tasks.Task<SustitucionMOAWS.PesificacionWebServiceMOA.SI_MPMF_MOAOP_OBTENER_PEND_USDResponse> SI_MPMF_MOAOP_OBTENER_PEND_USDAsync(string IM_PROVEEDOR) {
            SustitucionMOAWS.PesificacionWebServiceMOA.SI_MPMF_MOAOP_OBTENER_PEND_USDRequest inValue = new SustitucionMOAWS.PesificacionWebServiceMOA.SI_MPMF_MOAOP_OBTENER_PEND_USDRequest();
            inValue.IM_PROVEEDOR = IM_PROVEEDOR;
            return ((SustitucionMOAWS.PesificacionWebServiceMOA.SI_MPMF_MOAOP_OBTENER_PEND_USD)(this)).SI_MPMF_MOAOP_OBTENER_PEND_USDAsync(inValue);
        }
    }
}
