//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SustitucionMOAWS.NoticiasDetalleWebServiceMOA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:OPERACIONES", ConfigurationName="NoticiasDetalleWebServiceMOA.SI_MPMF_MOAOP_DETALLES_NOTICIAS")]
    public interface SI_MPMF_MOAOP_DETALLES_NOTICIAS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SustitucionMOAWS.NoticiasDetalleWebServiceMOA.SI_MPMF_MOAOP_DETALLES_NOTICIASResponse SI_MPMF_MOAOP_DETALLES_NOTICIAS(SustitucionMOAWS.NoticiasDetalleWebServiceMOA.SI_MPMF_MOAOP_DETALLES_NOTICIASRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SustitucionMOAWS.NoticiasDetalleWebServiceMOA.SI_MPMF_MOAOP_DETALLES_NOTICIASResponse> SI_MPMF_MOAOP_DETALLES_NOTICIASAsync(SustitucionMOAWS.NoticiasDetalleWebServiceMOA.SI_MPMF_MOAOP_DETALLES_NOTICIASRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES4530 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string fECHAField;
        
        private string tITULOField;
        
        private string nUEVAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string FECHA {
            get {
                return this.fECHAField;
            }
            set {
                this.fECHAField = value;
                this.RaisePropertyChanged("FECHA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TITULO {
            get {
                return this.tITULOField;
            }
            set {
                this.tITULOField = value;
                this.RaisePropertyChanged("TITULO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string NUEVA {
            get {
                return this.nUEVAField;
            }
            set {
                this.nUEVAField = value;
                this.RaisePropertyChanged("NUEVA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES4920 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string tEXTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TEXTO {
            get {
                return this.tEXTOField;
            }
            set {
                this.tEXTOField = value;
                this.RaisePropertyChanged("TEXTO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES4910 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cODIGOField;
        
        private string dESCRIPCIONField;
        
        private string tIPOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CODIGO {
            get {
                return this.cODIGOField;
            }
            set {
                this.cODIGOField = value;
                this.RaisePropertyChanged("CODIGO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
                this.RaisePropertyChanged("DESCRIPCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TIPO {
            get {
                return this.tIPOField;
            }
            set {
                this.tIPOField = value;
                this.RaisePropertyChanged("TIPO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES4540 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nRO_LINEAField;
        
        private string cONTENIDOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=1)]
        public string NRO_LINEA {
            get {
                return this.nRO_LINEAField;
            }
            set {
                this.nRO_LINEAField = value;
                this.RaisePropertyChanged("NRO_LINEA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CONTENIDO {
            get {
                return this.cONTENIDOField;
            }
            set {
                this.cONTENIDOField = value;
                this.RaisePropertyChanged("CONTENIDO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MPMF_MOAOP_DETALLES_NOTICIAS", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MPMF_MOAOP_DETALLES_NOTICIASRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PE_FECHA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PE_PROVEEDOR;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=2)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.NoticiasDetalleWebServiceMOA.ZMPES4530[] T_CABECERA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=3)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.NoticiasDetalleWebServiceMOA.ZMPES4540[] T_CONTENIDO;
        
        public SI_MPMF_MOAOP_DETALLES_NOTICIASRequest() {
        }
        
        public SI_MPMF_MOAOP_DETALLES_NOTICIASRequest(string PE_FECHA, string PE_PROVEEDOR, SustitucionMOAWS.NoticiasDetalleWebServiceMOA.ZMPES4530[] T_CABECERA, SustitucionMOAWS.NoticiasDetalleWebServiceMOA.ZMPES4540[] T_CONTENIDO) {
            this.PE_FECHA = PE_FECHA;
            this.PE_PROVEEDOR = PE_PROVEEDOR;
            this.T_CABECERA = T_CABECERA;
            this.T_CONTENIDO = T_CONTENIDO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MPMF_MOAOP_DETALLES_NOTICIAS.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MPMF_MOAOP_DETALLES_NOTICIASResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SustitucionMOAWS.NoticiasDetalleWebServiceMOA.ZMPES4910 MENSAJE_ERROR;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.NoticiasDetalleWebServiceMOA.ZMPES4920[] T_SALIDA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=2)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.NoticiasDetalleWebServiceMOA.ZMPES4530[] T_CABECERA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=3)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.NoticiasDetalleWebServiceMOA.ZMPES4540[] T_CONTENIDO;
        
        public SI_MPMF_MOAOP_DETALLES_NOTICIASResponse() {
        }
        
        public SI_MPMF_MOAOP_DETALLES_NOTICIASResponse(SustitucionMOAWS.NoticiasDetalleWebServiceMOA.ZMPES4910 MENSAJE_ERROR, SustitucionMOAWS.NoticiasDetalleWebServiceMOA.ZMPES4920[] T_SALIDA, SustitucionMOAWS.NoticiasDetalleWebServiceMOA.ZMPES4530[] T_CABECERA, SustitucionMOAWS.NoticiasDetalleWebServiceMOA.ZMPES4540[] T_CONTENIDO) {
            this.MENSAJE_ERROR = MENSAJE_ERROR;
            this.T_SALIDA = T_SALIDA;
            this.T_CABECERA = T_CABECERA;
            this.T_CONTENIDO = T_CONTENIDO;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_MPMF_MOAOP_DETALLES_NOTICIASChannel : SustitucionMOAWS.NoticiasDetalleWebServiceMOA.SI_MPMF_MOAOP_DETALLES_NOTICIAS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_MPMF_MOAOP_DETALLES_NOTICIASClient : System.ServiceModel.ClientBase<SustitucionMOAWS.NoticiasDetalleWebServiceMOA.SI_MPMF_MOAOP_DETALLES_NOTICIAS>, SustitucionMOAWS.NoticiasDetalleWebServiceMOA.SI_MPMF_MOAOP_DETALLES_NOTICIAS {
        
        public SI_MPMF_MOAOP_DETALLES_NOTICIASClient() {
        }
        
        public SI_MPMF_MOAOP_DETALLES_NOTICIASClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_MPMF_MOAOP_DETALLES_NOTICIASClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MPMF_MOAOP_DETALLES_NOTICIASClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MPMF_MOAOP_DETALLES_NOTICIASClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SustitucionMOAWS.NoticiasDetalleWebServiceMOA.SI_MPMF_MOAOP_DETALLES_NOTICIASResponse SustitucionMOAWS.NoticiasDetalleWebServiceMOA.SI_MPMF_MOAOP_DETALLES_NOTICIAS.SI_MPMF_MOAOP_DETALLES_NOTICIAS(SustitucionMOAWS.NoticiasDetalleWebServiceMOA.SI_MPMF_MOAOP_DETALLES_NOTICIASRequest request) {
            return base.Channel.SI_MPMF_MOAOP_DETALLES_NOTICIAS(request);
        }
        
        public SustitucionMOAWS.NoticiasDetalleWebServiceMOA.ZMPES4910 SI_MPMF_MOAOP_DETALLES_NOTICIAS(string PE_FECHA, string PE_PROVEEDOR, ref SustitucionMOAWS.NoticiasDetalleWebServiceMOA.ZMPES4530[] T_CABECERA, ref SustitucionMOAWS.NoticiasDetalleWebServiceMOA.ZMPES4540[] T_CONTENIDO, out SustitucionMOAWS.NoticiasDetalleWebServiceMOA.ZMPES4920[] T_SALIDA) {
            SustitucionMOAWS.NoticiasDetalleWebServiceMOA.SI_MPMF_MOAOP_DETALLES_NOTICIASRequest inValue = new SustitucionMOAWS.NoticiasDetalleWebServiceMOA.SI_MPMF_MOAOP_DETALLES_NOTICIASRequest();
            inValue.PE_FECHA = PE_FECHA;
            inValue.PE_PROVEEDOR = PE_PROVEEDOR;
            inValue.T_CABECERA = T_CABECERA;
            inValue.T_CONTENIDO = T_CONTENIDO;
            SustitucionMOAWS.NoticiasDetalleWebServiceMOA.SI_MPMF_MOAOP_DETALLES_NOTICIASResponse retVal = ((SustitucionMOAWS.NoticiasDetalleWebServiceMOA.SI_MPMF_MOAOP_DETALLES_NOTICIAS)(this)).SI_MPMF_MOAOP_DETALLES_NOTICIAS(inValue);
            T_SALIDA = retVal.T_SALIDA;
            T_CABECERA = retVal.T_CABECERA;
            T_CONTENIDO = retVal.T_CONTENIDO;
            return retVal.MENSAJE_ERROR;
        }
        
        public System.Threading.Tasks.Task<SustitucionMOAWS.NoticiasDetalleWebServiceMOA.SI_MPMF_MOAOP_DETALLES_NOTICIASResponse> SI_MPMF_MOAOP_DETALLES_NOTICIASAsync(SustitucionMOAWS.NoticiasDetalleWebServiceMOA.SI_MPMF_MOAOP_DETALLES_NOTICIASRequest request) {
            return base.Channel.SI_MPMF_MOAOP_DETALLES_NOTICIASAsync(request);
        }
    }
}
