//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SustitucionMOAWS.FijacionDetalleWebServiceMOA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:OPERACIONES", ConfigurationName="FijacionDetalleWebServiceMOA.SI_MPMF_MOAOP_DET_FIJACIONES")]
    public interface SI_MPMF_MOAOP_DET_FIJACIONES {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SustitucionMOAWS.FijacionDetalleWebServiceMOA.SI_MPMF_MOAOP_DET_FIJACIONESResponse SI_MPMF_MOAOP_DET_FIJACIONES(SustitucionMOAWS.FijacionDetalleWebServiceMOA.SI_MPMF_MOAOP_DET_FIJACIONESRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SustitucionMOAWS.FijacionDetalleWebServiceMOA.SI_MPMF_MOAOP_DET_FIJACIONESResponse> SI_MPMF_MOAOP_DET_FIJACIONESAsync(SustitucionMOAWS.FijacionDetalleWebServiceMOA.SI_MPMF_MOAOP_DET_FIJACIONESRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES4680 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fECHA_DESCARGAField;
        
        private string cARTA_PORTEField;
        
        private decimal nETO_DESCONTADOField;
        
        private bool nETO_DESCONTADOFieldSpecified;
        
        private string nETO_UNIMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FECHA_DESCARGA {
            get {
                return this.fECHA_DESCARGAField;
            }
            set {
                this.fECHA_DESCARGAField = value;
                this.RaisePropertyChanged("FECHA_DESCARGA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CARTA_PORTE {
            get {
                return this.cARTA_PORTEField;
            }
            set {
                this.cARTA_PORTEField = value;
                this.RaisePropertyChanged("CARTA_PORTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal NETO_DESCONTADO {
            get {
                return this.nETO_DESCONTADOField;
            }
            set {
                this.nETO_DESCONTADOField = value;
                this.RaisePropertyChanged("NETO_DESCONTADO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NETO_DESCONTADOSpecified {
            get {
                return this.nETO_DESCONTADOFieldSpecified;
            }
            set {
                this.nETO_DESCONTADOFieldSpecified = value;
                this.RaisePropertyChanged("NETO_DESCONTADOSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string NETO_UNIME {
            get {
                return this.nETO_UNIMEField;
            }
            set {
                this.nETO_UNIMEField = value;
                this.RaisePropertyChanged("NETO_UNIME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES4910 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cODIGOField;
        
        private string dESCRIPCIONField;
        
        private string tIPOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CODIGO {
            get {
                return this.cODIGOField;
            }
            set {
                this.cODIGOField = value;
                this.RaisePropertyChanged("CODIGO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
                this.RaisePropertyChanged("DESCRIPCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TIPO {
            get {
                return this.tIPOField;
            }
            set {
                this.tIPOField = value;
                this.RaisePropertyChanged("TIPO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MPMF_MOAOP_DET_FIJACIONES", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MPMF_MOAOP_DET_FIJACIONESRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PE_CONTRATO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PE_FIJACION;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PE_PROVEEDOR;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=3)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.FijacionDetalleWebServiceMOA.ZMPES4680[] T_DETALLE_FIJACION;
        
        public SI_MPMF_MOAOP_DET_FIJACIONESRequest() {
        }
        
        public SI_MPMF_MOAOP_DET_FIJACIONESRequest(string PE_CONTRATO, string PE_FIJACION, string PE_PROVEEDOR, SustitucionMOAWS.FijacionDetalleWebServiceMOA.ZMPES4680[] T_DETALLE_FIJACION) {
            this.PE_CONTRATO = PE_CONTRATO;
            this.PE_FIJACION = PE_FIJACION;
            this.PE_PROVEEDOR = PE_PROVEEDOR;
            this.T_DETALLE_FIJACION = T_DETALLE_FIJACION;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MPMF_MOAOP_DET_FIJACIONES.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MPMF_MOAOP_DET_FIJACIONESResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SustitucionMOAWS.FijacionDetalleWebServiceMOA.ZMPES4910 MENSAJE_ERROR;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.FijacionDetalleWebServiceMOA.ZMPES4680[] T_DETALLE_FIJACION;
        
        public SI_MPMF_MOAOP_DET_FIJACIONESResponse() {
        }
        
        public SI_MPMF_MOAOP_DET_FIJACIONESResponse(SustitucionMOAWS.FijacionDetalleWebServiceMOA.ZMPES4910 MENSAJE_ERROR, SustitucionMOAWS.FijacionDetalleWebServiceMOA.ZMPES4680[] T_DETALLE_FIJACION) {
            this.MENSAJE_ERROR = MENSAJE_ERROR;
            this.T_DETALLE_FIJACION = T_DETALLE_FIJACION;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_MPMF_MOAOP_DET_FIJACIONESChannel : SustitucionMOAWS.FijacionDetalleWebServiceMOA.SI_MPMF_MOAOP_DET_FIJACIONES, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_MPMF_MOAOP_DET_FIJACIONESClient : System.ServiceModel.ClientBase<SustitucionMOAWS.FijacionDetalleWebServiceMOA.SI_MPMF_MOAOP_DET_FIJACIONES>, SustitucionMOAWS.FijacionDetalleWebServiceMOA.SI_MPMF_MOAOP_DET_FIJACIONES {
        
        public SI_MPMF_MOAOP_DET_FIJACIONESClient() {
        }
        
        public SI_MPMF_MOAOP_DET_FIJACIONESClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_MPMF_MOAOP_DET_FIJACIONESClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MPMF_MOAOP_DET_FIJACIONESClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MPMF_MOAOP_DET_FIJACIONESClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SustitucionMOAWS.FijacionDetalleWebServiceMOA.SI_MPMF_MOAOP_DET_FIJACIONESResponse SustitucionMOAWS.FijacionDetalleWebServiceMOA.SI_MPMF_MOAOP_DET_FIJACIONES.SI_MPMF_MOAOP_DET_FIJACIONES(SustitucionMOAWS.FijacionDetalleWebServiceMOA.SI_MPMF_MOAOP_DET_FIJACIONESRequest request) {
            return base.Channel.SI_MPMF_MOAOP_DET_FIJACIONES(request);
        }
        
        public SustitucionMOAWS.FijacionDetalleWebServiceMOA.ZMPES4910 SI_MPMF_MOAOP_DET_FIJACIONES(string PE_CONTRATO, string PE_FIJACION, string PE_PROVEEDOR, ref SustitucionMOAWS.FijacionDetalleWebServiceMOA.ZMPES4680[] T_DETALLE_FIJACION) {
            SustitucionMOAWS.FijacionDetalleWebServiceMOA.SI_MPMF_MOAOP_DET_FIJACIONESRequest inValue = new SustitucionMOAWS.FijacionDetalleWebServiceMOA.SI_MPMF_MOAOP_DET_FIJACIONESRequest();
            inValue.PE_CONTRATO = PE_CONTRATO;
            inValue.PE_FIJACION = PE_FIJACION;
            inValue.PE_PROVEEDOR = PE_PROVEEDOR;
            inValue.T_DETALLE_FIJACION = T_DETALLE_FIJACION;
            SustitucionMOAWS.FijacionDetalleWebServiceMOA.SI_MPMF_MOAOP_DET_FIJACIONESResponse retVal = ((SustitucionMOAWS.FijacionDetalleWebServiceMOA.SI_MPMF_MOAOP_DET_FIJACIONES)(this)).SI_MPMF_MOAOP_DET_FIJACIONES(inValue);
            T_DETALLE_FIJACION = retVal.T_DETALLE_FIJACION;
            return retVal.MENSAJE_ERROR;
        }
        
        public System.Threading.Tasks.Task<SustitucionMOAWS.FijacionDetalleWebServiceMOA.SI_MPMF_MOAOP_DET_FIJACIONESResponse> SI_MPMF_MOAOP_DET_FIJACIONESAsync(SustitucionMOAWS.FijacionDetalleWebServiceMOA.SI_MPMF_MOAOP_DET_FIJACIONESRequest request) {
            return base.Channel.SI_MPMF_MOAOP_DET_FIJACIONESAsync(request);
        }
    }
}
