export enum Permiso {
    AbmAppCCPP = "ABM APLICACIONES CCPP",
    AdjudicarDentroDelPlazoDeOfertas = "ADJUDICAR DENTRO DEL PLAZO DE OFERTAS",
    AdminAppCCPP = "ADMIN APLICACIONES CCPP",
    AdministrarCursos = "ADMINISTRAR CURSOS",
    AltaInternaGranos = "ALTA INTERNA GRANOS",
    AltaInternaNoGranos = "ALTA INTERNA NO GRANOS",
    ComercialCamposSustentables = "COMERCIAL CAMPOS SUSTENTABLES",
    ComprasRRHH = "COMPRAS RRHH",
    EnviarSAP = "ENVIAR A SAP",
    FasModificarCampoReventa = "FAS - MODIFICAR CAMPO REVENTA",
    FasonModificarCampoReventa = "FASON - MODIFICAR CAMPO REVENTA",
    FasonVerOrdenesDeCarga = "VER ORDENES DE CARGA FASON",
    FasonVerOrdenesDeCargaAdmin = "VER ORDENES DE CARGA FASON ADMIN",
    FasVerOrdenesComerciales = "VER ORDENES DE CARGA PARA COMERCIALES",
    FasVerTodasOrdenes = "VER TODAS ORDENES DE CARGA",
    FleteMOA = "FASON - MODIFICA FLETE MOA",
    ReporteFacturasCertificaciones = "REPORTE FACTURAS CERTIFICACIONES",
    ResiduosVerOrdenesDeCarga = "VER ORDENES DE CARGA RESIDUOS",
    ResiduosVerOrdenesDeCargaAdmin = "VER ORDENES DE CARGA RESIDUOS ADMIN",
    VerComoAuditor = "VER COMO AUDITOR"
}