IF NOT EXISTS (SELECT TOP 1 1 FROM Rol WHERE Codigo = 'OBI') 
BEGIN
    INSERT Rol (Codigo, Nombre, EsEditable) VALUES ('OBI', 'OCULTAR BUSCADOR INTELIGENTE', 1)
END
GO

IF NOT EXISTS (SELECT TOP 1 1 FROM PermisoPorRol WHERE Permiso = 'OCULTAR BUSCADOR INTELIGENTE') 
BEGIN
    INSERT PermisoPorRol (Permiso) VALUES ('OCULTAR BUSCADOR INTELIGENTE')
END
GO

DECLARE @IdRol INT = (SELECT TOP 1 Id FROM Rol WHERE Codigo = 'OBI')
DECLARE @IdPermisoPorRol INT = (SELECT TOP 1 Id FROM PermisoPorRol WHERE Permiso = 'OCULTAR BUSCADOR INTELIGENTE')

IF NOT EXISTS (SELECT TOP 1 1 FROM RolPermisoPorRol WHERE Rol_Id = @IdRol AND PermisoPorRol_Id = @IdPermisoPorRol) 
BEGIN
    INSERT RolPermisoPorRol (Rol_Id, PermisoPorRol_Id) VALUES (@IdRol, @IdPermisoPorRol)
END
GO