IF NOT EXISTS(SELECT TOP 1 1 FROM PermisoPorRol WHERE Permiso = 'VER SOLPS COMPRADOR')
BEGIN

	INSERT INTO PermisoPorRol
	VALUES ( 'VER SOLPS COMPRADOR' ) 

	DECLARE @PermisoId INT = SCOPE_IDENTITY()

	INSERT INTO Rol
	VALUES ('COMPRADOR', 'COMPRADOR', 1)

	DECLARE @RolId INT = SCOPE_IDENTITY()

	INSERT INTO RolPermisoPorRol
	VALUES(@RolId, @PermisoId)

	INSERT INTO RolPermisoPorRol
	SELECT @rolId, PermisoPorRol_ID
	FROM RolPermisoPorRol
	Where Rol_Id = (SELECT ID FROM Rol WHERE Nombre = 'COMPRADOR')
END	
