BEGIN TRAN
SET NOCOUNT ON
IF NOT EXISTS (SELECT TOP 1 1 FROM PermisoPorRol WHERE Permiso = 'VER PESIFICACIONES')
BEGIN
    INSERT INTO PermisoPorRol (Permiso)
    VALUES ('VER PESIFICACIONES')
END

IF NOT EXISTS (SELECT TOP 1 1 FROM PermisoPorRol WHERE Permiso = 'ELEGIR TODOS VENDEDORES')
BEGIN
    INSERT INTO PermisoPorRol (Permiso)
    VALUES ('ELEGIR TODOS VENDEDORES')
END


DECLARE @tempTablePermisos TABLE (IdPermiso INT)

INSERT INTO @tempTablePermisos
SELECT Id From PermisoPorRol 
WHERE  Permiso IN (
''
,'CONSULTAR CARTAS PORTE'
,'CONSULTAR CARTAS PORTE DETALLE'
,'CONSULTAR COMPROBANTES'
,'CONSULTAR CONTRATO DETALLE'
,'CONSULTAR CONTRATOS'
,'CONSULTAR CUENTA CORRIENTE'
,'CONSULTAR DATOS FISCALES'
,'CONSULTAR DOCUMENTACION'
,'CONSULTAR HOME'
,'CONSULTAR LIQUIDACIONES'
,'CONSULTAR PAGOS'
,'CONSULTAR PAGOS DETALLE'
,'CONSULTAR VENDEDOR STATUS'
,'CONSULTAR VENDEDORES'
,'CONTACTO MAIL'
,'DESCARGAR CARTAS PORTE'
,'DESCARGAR CARTAS PORTE DETALLE'
,'DESCARGAR COMPROBANTES'
,'DESCARGAR CONTRATOS'
,'DESCARGAR CUENTA CORRIENTE'
,'DESCARGAR DOCUMENTO'
,'DESCARGAR LIQUIDACIONES'
,'DESCARGAR PAGOS'
,'SELECCIONAR VENDEDOR'
,'ABM EMPRESAS'
,'MENU'
,'VER ALTAS GRANOS'
,'VER PESIFICACIONES'
,'ELEGIR TODOS VENDEDORES'
)


IF NOT EXISTS (SELECT TOP 1 1 from Rol WHERE Codigo = 'COMERCIAL')
BEGIN
    Declare @rolId INT = 0
    INSERT INTO ROL (Codigo, Nombre)
    Values ('COMERCIAL', 'COMERCIAL')

    SET @rolId = SCOPE_IDENTITY()

    INSERT INTO RolPermisoPorRol
    SELECT @rolId, IdPermiso From @tempTablePermisos
END


COMMIT TRAN