//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SustitucionMOAWS.ComprobantesNGWebServiceMOA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:OPERACIONES", ConfigurationName="ComprobantesNGWebServiceMOA.SI_MPMF_MOAOP_COMPROB_NOGRANOS")]
    public interface SI_MPMF_MOAOP_COMPROB_NOGRANOS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SustitucionMOAWS.ComprobantesNGWebServiceMOA.SI_MPMF_MOAOP_COMPROB_NOGRANOSResponse SI_MPMF_MOAOP_COMPROB_NOGRANOS(SustitucionMOAWS.ComprobantesNGWebServiceMOA.SI_MPMF_MOAOP_COMPROB_NOGRANOSRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SustitucionMOAWS.ComprobantesNGWebServiceMOA.SI_MPMF_MOAOP_COMPROB_NOGRANOSResponse> SI_MPMF_MOAOP_COMPROB_NOGRANOSAsync(SustitucionMOAWS.ComprobantesNGWebServiceMOA.SI_MPMF_MOAOP_COMPROB_NOGRANOSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES4100 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fECHA_OPField;
        
        private string fECHA_OP_HASTAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FECHA_OP {
            get {
                return this.fECHA_OPField;
            }
            set {
                this.fECHA_OPField = value;
                this.RaisePropertyChanged("FECHA_OP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string FECHA_OP_HASTA {
            get {
                return this.fECHA_OP_HASTAField;
            }
            set {
                this.fECHA_OP_HASTAField = value;
                this.RaisePropertyChanged("FECHA_OP_HASTA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPIRET2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        private string lOG_NOField;
        
        private string lOG_MSG_NOField;
        
        private string mESSAGE_V1Field;
        
        private string mESSAGE_V2Field;
        
        private string mESSAGE_V3Field;
        
        private string mESSAGE_V4Field;
        
        private string pARAMETERField;
        
        private string rOWField;
        
        private string fIELDField;
        
        private string sYSTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NUMBER {
            get {
                return this.nUMBERField;
            }
            set {
                this.nUMBERField = value;
                this.RaisePropertyChanged("NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LOG_NO {
            get {
                return this.lOG_NOField;
            }
            set {
                this.lOG_NOField = value;
                this.RaisePropertyChanged("LOG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LOG_MSG_NO {
            get {
                return this.lOG_MSG_NOField;
            }
            set {
                this.lOG_MSG_NOField = value;
                this.RaisePropertyChanged("LOG_MSG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MESSAGE_V1 {
            get {
                return this.mESSAGE_V1Field;
            }
            set {
                this.mESSAGE_V1Field = value;
                this.RaisePropertyChanged("MESSAGE_V1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MESSAGE_V2 {
            get {
                return this.mESSAGE_V2Field;
            }
            set {
                this.mESSAGE_V2Field = value;
                this.RaisePropertyChanged("MESSAGE_V2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MESSAGE_V3 {
            get {
                return this.mESSAGE_V3Field;
            }
            set {
                this.mESSAGE_V3Field = value;
                this.RaisePropertyChanged("MESSAGE_V3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MESSAGE_V4 {
            get {
                return this.mESSAGE_V4Field;
            }
            set {
                this.mESSAGE_V4Field = value;
                this.RaisePropertyChanged("MESSAGE_V4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PARAMETER {
            get {
                return this.pARAMETERField;
            }
            set {
                this.pARAMETERField = value;
                this.RaisePropertyChanged("PARAMETER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=11)]
        public string ROW {
            get {
                return this.rOWField;
            }
            set {
                this.rOWField = value;
                this.RaisePropertyChanged("ROW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string FIELD {
            get {
                return this.fIELDField;
            }
            set {
                this.fIELDField = value;
                this.RaisePropertyChanged("FIELD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string SYSTEM {
            get {
                return this.sYSTEMField;
            }
            set {
                this.sYSTEMField = value;
                this.RaisePropertyChanged("SYSTEM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES5940 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bUKRSField;
        
        private string lIFNRField;
        
        private string vEND_NAMEField;
        
        private string bLDATField;
        
        private string bLARTField;
        
        private string lTEXTField;
        
        private string xBLNRField;
        
        private string sTATUSField;
        
        private string cURR_ROLEField;
        
        private string dELREASONField;
        
        private string eBELNField;
        
        private decimal nET_AMOUNTField;
        
        private bool nET_AMOUNTFieldSpecified;
        
        private decimal vAT_AMOUNTField;
        
        private bool vAT_AMOUNTFieldSpecified;
        
        private decimal gROSS_AMOUNTField;
        
        private bool gROSS_AMOUNTFieldSpecified;
        
        private string wAERSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
                this.RaisePropertyChanged("BUKRS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
                this.RaisePropertyChanged("LIFNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string VEND_NAME {
            get {
                return this.vEND_NAMEField;
            }
            set {
                this.vEND_NAMEField = value;
                this.RaisePropertyChanged("VEND_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string BLDAT {
            get {
                return this.bLDATField;
            }
            set {
                this.bLDATField = value;
                this.RaisePropertyChanged("BLDAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string BLART {
            get {
                return this.bLARTField;
            }
            set {
                this.bLARTField = value;
                this.RaisePropertyChanged("BLART");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LTEXT {
            get {
                return this.lTEXTField;
            }
            set {
                this.lTEXTField = value;
                this.RaisePropertyChanged("LTEXT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string XBLNR {
            get {
                return this.xBLNRField;
            }
            set {
                this.xBLNRField = value;
                this.RaisePropertyChanged("XBLNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
                this.RaisePropertyChanged("STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string CURR_ROLE {
            get {
                return this.cURR_ROLEField;
            }
            set {
                this.cURR_ROLEField = value;
                this.RaisePropertyChanged("CURR_ROLE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string DELREASON {
            get {
                return this.dELREASONField;
            }
            set {
                this.dELREASONField = value;
                this.RaisePropertyChanged("DELREASON");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string EBELN {
            get {
                return this.eBELNField;
            }
            set {
                this.eBELNField = value;
                this.RaisePropertyChanged("EBELN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal NET_AMOUNT {
            get {
                return this.nET_AMOUNTField;
            }
            set {
                this.nET_AMOUNTField = value;
                this.RaisePropertyChanged("NET_AMOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NET_AMOUNTSpecified {
            get {
                return this.nET_AMOUNTFieldSpecified;
            }
            set {
                this.nET_AMOUNTFieldSpecified = value;
                this.RaisePropertyChanged("NET_AMOUNTSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public decimal VAT_AMOUNT {
            get {
                return this.vAT_AMOUNTField;
            }
            set {
                this.vAT_AMOUNTField = value;
                this.RaisePropertyChanged("VAT_AMOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VAT_AMOUNTSpecified {
            get {
                return this.vAT_AMOUNTFieldSpecified;
            }
            set {
                this.vAT_AMOUNTFieldSpecified = value;
                this.RaisePropertyChanged("VAT_AMOUNTSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public decimal GROSS_AMOUNT {
            get {
                return this.gROSS_AMOUNTField;
            }
            set {
                this.gROSS_AMOUNTField = value;
                this.RaisePropertyChanged("GROSS_AMOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GROSS_AMOUNTSpecified {
            get {
                return this.gROSS_AMOUNTFieldSpecified;
            }
            set {
                this.gROSS_AMOUNTFieldSpecified = value;
                this.RaisePropertyChanged("GROSS_AMOUNTSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string WAERS {
            get {
                return this.wAERSField;
            }
            set {
                this.wAERSField = value;
                this.RaisePropertyChanged("WAERS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MPRFC_MOAOP_COMPROB_NOGRANOS", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MPMF_MOAOP_COMPROB_NOGRANOSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.ComprobantesNGWebServiceMOA.ZMPES4100[] IM_FECHA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_PROVEEDOR;
        
        public SI_MPMF_MOAOP_COMPROB_NOGRANOSRequest() {
        }
        
        public SI_MPMF_MOAOP_COMPROB_NOGRANOSRequest(SustitucionMOAWS.ComprobantesNGWebServiceMOA.ZMPES4100[] IM_FECHA, string IM_PROVEEDOR) {
            this.IM_FECHA = IM_FECHA;
            this.IM_PROVEEDOR = IM_PROVEEDOR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MPRFC_MOAOP_COMPROB_NOGRANOS.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MPMF_MOAOP_COMPROB_NOGRANOSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.ComprobantesNGWebServiceMOA.ZMPES5940[] EX_COMPRB;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.ComprobantesNGWebServiceMOA.BAPIRET2[] EX_RETURN;
        
        public SI_MPMF_MOAOP_COMPROB_NOGRANOSResponse() {
        }
        
        public SI_MPMF_MOAOP_COMPROB_NOGRANOSResponse(SustitucionMOAWS.ComprobantesNGWebServiceMOA.ZMPES5940[] EX_COMPRB, SustitucionMOAWS.ComprobantesNGWebServiceMOA.BAPIRET2[] EX_RETURN) {
            this.EX_COMPRB = EX_COMPRB;
            this.EX_RETURN = EX_RETURN;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_MPMF_MOAOP_COMPROB_NOGRANOSChannel : SustitucionMOAWS.ComprobantesNGWebServiceMOA.SI_MPMF_MOAOP_COMPROB_NOGRANOS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_MPMF_MOAOP_COMPROB_NOGRANOSClient : System.ServiceModel.ClientBase<SustitucionMOAWS.ComprobantesNGWebServiceMOA.SI_MPMF_MOAOP_COMPROB_NOGRANOS>, SustitucionMOAWS.ComprobantesNGWebServiceMOA.SI_MPMF_MOAOP_COMPROB_NOGRANOS {
        
        public SI_MPMF_MOAOP_COMPROB_NOGRANOSClient() {
        }
        
        public SI_MPMF_MOAOP_COMPROB_NOGRANOSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_MPMF_MOAOP_COMPROB_NOGRANOSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MPMF_MOAOP_COMPROB_NOGRANOSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MPMF_MOAOP_COMPROB_NOGRANOSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SustitucionMOAWS.ComprobantesNGWebServiceMOA.SI_MPMF_MOAOP_COMPROB_NOGRANOSResponse SustitucionMOAWS.ComprobantesNGWebServiceMOA.SI_MPMF_MOAOP_COMPROB_NOGRANOS.SI_MPMF_MOAOP_COMPROB_NOGRANOS(SustitucionMOAWS.ComprobantesNGWebServiceMOA.SI_MPMF_MOAOP_COMPROB_NOGRANOSRequest request) {
            return base.Channel.SI_MPMF_MOAOP_COMPROB_NOGRANOS(request);
        }
        
        public SustitucionMOAWS.ComprobantesNGWebServiceMOA.ZMPES5940[] SI_MPMF_MOAOP_COMPROB_NOGRANOS(SustitucionMOAWS.ComprobantesNGWebServiceMOA.ZMPES4100[] IM_FECHA, string IM_PROVEEDOR, out SustitucionMOAWS.ComprobantesNGWebServiceMOA.BAPIRET2[] EX_RETURN) {
            SustitucionMOAWS.ComprobantesNGWebServiceMOA.SI_MPMF_MOAOP_COMPROB_NOGRANOSRequest inValue = new SustitucionMOAWS.ComprobantesNGWebServiceMOA.SI_MPMF_MOAOP_COMPROB_NOGRANOSRequest();
            inValue.IM_FECHA = IM_FECHA;
            inValue.IM_PROVEEDOR = IM_PROVEEDOR;
            SustitucionMOAWS.ComprobantesNGWebServiceMOA.SI_MPMF_MOAOP_COMPROB_NOGRANOSResponse retVal = ((SustitucionMOAWS.ComprobantesNGWebServiceMOA.SI_MPMF_MOAOP_COMPROB_NOGRANOS)(this)).SI_MPMF_MOAOP_COMPROB_NOGRANOS(inValue);
            EX_RETURN = retVal.EX_RETURN;
            return retVal.EX_COMPRB;
        }
        
        public System.Threading.Tasks.Task<SustitucionMOAWS.ComprobantesNGWebServiceMOA.SI_MPMF_MOAOP_COMPROB_NOGRANOSResponse> SI_MPMF_MOAOP_COMPROB_NOGRANOSAsync(SustitucionMOAWS.ComprobantesNGWebServiceMOA.SI_MPMF_MOAOP_COMPROB_NOGRANOSRequest request) {
            return base.Channel.SI_MPMF_MOAOP_COMPROB_NOGRANOSAsync(request);
        }
    }
}
