//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SustitucionMOAWS.OrdenesDeCompraParaSolpWebServiceMOA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Z_MMRFC_OC_PARA_SOLP.PortType", Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="OrdenesDeCompraParaSolpWebServiceMOA.Z_MMRFC_OC_PARA_SOLPPortType")]
    public interface Z_MMRFC_OC_PARA_SOLPPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SustitucionMOAWS.OrdenesDeCompraParaSolpWebServiceMOA.Z_MMRFC_OC_PARA_SOLPResponse Z_MMRFC_OC_PARA_SOLP(SustitucionMOAWS.OrdenesDeCompraParaSolpWebServiceMOA.Z_MMRFC_OC_PARA_SOLPRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SustitucionMOAWS.OrdenesDeCompraParaSolpWebServiceMOA.Z_MMRFC_OC_PARA_SOLPResponse> Z_MMRFC_OC_PARA_SOLPAsync(SustitucionMOAWS.OrdenesDeCompraParaSolpWebServiceMOA.Z_MMRFC_OC_PARA_SOLPRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMMES0027 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bANFNField;
        
        private string bNFPOField;
        
        private string eBELNField;
        
        private string eBELPField;
        
        private string eTENRField;
        
        private string bSTYPField;
        
        private string bSARTField;
        
        private string aEDATField;
        
        private string eRNAMField;
        
        private string bEDATField;
        
        private string lIFNRField;
        
        private string nAME1Field;
        
        private string sTCD1Field;
        
        private string wAERSField;
        
        private decimal nETWRField;
        
        private bool nETWRFieldSpecified;
        
        private string pSTYPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string BANFN {
            get {
                return this.bANFNField;
            }
            set {
                this.bANFNField = value;
                this.RaisePropertyChanged("BANFN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string BNFPO {
            get {
                return this.bNFPOField;
            }
            set {
                this.bNFPOField = value;
                this.RaisePropertyChanged("BNFPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string EBELN {
            get {
                return this.eBELNField;
            }
            set {
                this.eBELNField = value;
                this.RaisePropertyChanged("EBELN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string EBELP {
            get {
                return this.eBELPField;
            }
            set {
                this.eBELPField = value;
                this.RaisePropertyChanged("EBELP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ETENR {
            get {
                return this.eTENRField;
            }
            set {
                this.eTENRField = value;
                this.RaisePropertyChanged("ETENR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string BSTYP {
            get {
                return this.bSTYPField;
            }
            set {
                this.bSTYPField = value;
                this.RaisePropertyChanged("BSTYP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string BSART {
            get {
                return this.bSARTField;
            }
            set {
                this.bSARTField = value;
                this.RaisePropertyChanged("BSART");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string AEDAT {
            get {
                return this.aEDATField;
            }
            set {
                this.aEDATField = value;
                this.RaisePropertyChanged("AEDAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string ERNAM {
            get {
                return this.eRNAMField;
            }
            set {
                this.eRNAMField = value;
                this.RaisePropertyChanged("ERNAM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string BEDAT {
            get {
                return this.bEDATField;
            }
            set {
                this.bEDATField = value;
                this.RaisePropertyChanged("BEDAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
                this.RaisePropertyChanged("LIFNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string NAME1 {
            get {
                return this.nAME1Field;
            }
            set {
                this.nAME1Field = value;
                this.RaisePropertyChanged("NAME1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string STCD1 {
            get {
                return this.sTCD1Field;
            }
            set {
                this.sTCD1Field = value;
                this.RaisePropertyChanged("STCD1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string WAERS {
            get {
                return this.wAERSField;
            }
            set {
                this.wAERSField = value;
                this.RaisePropertyChanged("WAERS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public decimal NETWR {
            get {
                return this.nETWRField;
            }
            set {
                this.nETWRField = value;
                this.RaisePropertyChanged("NETWR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NETWRSpecified {
            get {
                return this.nETWRFieldSpecified;
            }
            set {
                this.nETWRFieldSpecified = value;
                this.RaisePropertyChanged("NETWRSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string PSTYP {
            get {
                return this.pSTYPField;
            }
            set {
                this.pSTYPField = value;
                this.RaisePropertyChanged("PSTYP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MMRFC_OC_PARA_SOLP", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class Z_MMRFC_OC_PARA_SOLPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_POSICION;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_SOLPED;
        
        public Z_MMRFC_OC_PARA_SOLPRequest() {
        }
        
        public Z_MMRFC_OC_PARA_SOLPRequest(string IM_POSICION, string IM_SOLPED) {
            this.IM_POSICION = IM_POSICION;
            this.IM_SOLPED = IM_SOLPED;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MMRFC_OC_PARA_SOLP.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class Z_MMRFC_OC_PARA_SOLPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.OrdenesDeCompraParaSolpWebServiceMOA.ZMMES0027[] EX_DATOS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EX_EXITO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EX_RETURN;
        
        public Z_MMRFC_OC_PARA_SOLPResponse() {
        }
        
        public Z_MMRFC_OC_PARA_SOLPResponse(SustitucionMOAWS.OrdenesDeCompraParaSolpWebServiceMOA.ZMMES0027[] EX_DATOS, string EX_EXITO, string EX_RETURN) {
            this.EX_DATOS = EX_DATOS;
            this.EX_EXITO = EX_EXITO;
            this.EX_RETURN = EX_RETURN;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Z_MMRFC_OC_PARA_SOLPPortTypeChannel : SustitucionMOAWS.OrdenesDeCompraParaSolpWebServiceMOA.Z_MMRFC_OC_PARA_SOLPPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Z_MMRFC_OC_PARA_SOLPPortTypeClient : System.ServiceModel.ClientBase<SustitucionMOAWS.OrdenesDeCompraParaSolpWebServiceMOA.Z_MMRFC_OC_PARA_SOLPPortType>, SustitucionMOAWS.OrdenesDeCompraParaSolpWebServiceMOA.Z_MMRFC_OC_PARA_SOLPPortType {
        
        public Z_MMRFC_OC_PARA_SOLPPortTypeClient() {
        }
        
        public Z_MMRFC_OC_PARA_SOLPPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Z_MMRFC_OC_PARA_SOLPPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Z_MMRFC_OC_PARA_SOLPPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Z_MMRFC_OC_PARA_SOLPPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SustitucionMOAWS.OrdenesDeCompraParaSolpWebServiceMOA.Z_MMRFC_OC_PARA_SOLPResponse SustitucionMOAWS.OrdenesDeCompraParaSolpWebServiceMOA.Z_MMRFC_OC_PARA_SOLPPortType.Z_MMRFC_OC_PARA_SOLP(SustitucionMOAWS.OrdenesDeCompraParaSolpWebServiceMOA.Z_MMRFC_OC_PARA_SOLPRequest request) {
            return base.Channel.Z_MMRFC_OC_PARA_SOLP(request);
        }
        
        public SustitucionMOAWS.OrdenesDeCompraParaSolpWebServiceMOA.ZMMES0027[] Z_MMRFC_OC_PARA_SOLP(string IM_POSICION, string IM_SOLPED, out string EX_EXITO, out string EX_RETURN) {
            SustitucionMOAWS.OrdenesDeCompraParaSolpWebServiceMOA.Z_MMRFC_OC_PARA_SOLPRequest inValue = new SustitucionMOAWS.OrdenesDeCompraParaSolpWebServiceMOA.Z_MMRFC_OC_PARA_SOLPRequest();
            inValue.IM_POSICION = IM_POSICION;
            inValue.IM_SOLPED = IM_SOLPED;
            SustitucionMOAWS.OrdenesDeCompraParaSolpWebServiceMOA.Z_MMRFC_OC_PARA_SOLPResponse retVal = ((SustitucionMOAWS.OrdenesDeCompraParaSolpWebServiceMOA.Z_MMRFC_OC_PARA_SOLPPortType)(this)).Z_MMRFC_OC_PARA_SOLP(inValue);
            EX_EXITO = retVal.EX_EXITO;
            EX_RETURN = retVal.EX_RETURN;
            return retVal.EX_DATOS;
        }
        
        public System.Threading.Tasks.Task<SustitucionMOAWS.OrdenesDeCompraParaSolpWebServiceMOA.Z_MMRFC_OC_PARA_SOLPResponse> Z_MMRFC_OC_PARA_SOLPAsync(SustitucionMOAWS.OrdenesDeCompraParaSolpWebServiceMOA.Z_MMRFC_OC_PARA_SOLPRequest request) {
            return base.Channel.Z_MMRFC_OC_PARA_SOLPAsync(request);
        }
    }
}
