export enum EstadoOrdenDeCarga {
    Pendiente = 0,
    Confirmado = 1,
    PendienteAprobacionCredito = 2,
    EntregaGenerada = 3,
    Anulada = 4,
    Entregada = 5,
    Vencida = 6,
    EntregaPendiente = 7,
    AnuladaPorVencimiento = 8,
    ErrorDeCarga = 9,
    //EdicionSolicitada = 10,
    //AnulacionSolicitada = 11,
    ContratoVencido = 12,
    EdicionRechazada = 13,
    SinEnviarASAP = 14,
    SinEstado = 15,
    EntregaAnuladaPedidoPendienteAnulacion = 16,
    PendienteCompensacion = 17
}
