//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SustitucionMOAWS.ObtenerPDFOrdenCompraWebServiceMOA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:OPERACIONES", ConfigurationName="ObtenerPDFOrdenCompraWebServiceMOA.SI_MMRFC_ENVIAR_PDF_OC")]
    public interface SI_MMRFC_ENVIAR_PDF_OC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SustitucionMOAWS.ObtenerPDFOrdenCompraWebServiceMOA.SI_MMRFC_ENVIAR_PDF_OCResponse SI_MMRFC_ENVIAR_PDF_OC(SustitucionMOAWS.ObtenerPDFOrdenCompraWebServiceMOA.SI_MMRFC_ENVIAR_PDF_OCRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SustitucionMOAWS.ObtenerPDFOrdenCompraWebServiceMOA.SI_MMRFC_ENVIAR_PDF_OCResponse> SI_MMRFC_ENVIAR_PDF_OCAsync(SustitucionMOAWS.ObtenerPDFOrdenCompraWebServiceMOA.SI_MMRFC_ENVIAR_PDF_OCRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MMRFC_ENVIAR_PDF_OC", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MMRFC_ENVIAR_PDF_OCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_ORDEN_COMPRA;
        
        public SI_MMRFC_ENVIAR_PDF_OCRequest() {
        }
        
        public SI_MMRFC_ENVIAR_PDF_OCRequest(string IM_ORDEN_COMPRA) {
            this.IM_ORDEN_COMPRA = IM_ORDEN_COMPRA;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MMRFC_ENVIAR_PDF_OC.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MMRFC_ENVIAR_PDF_OCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EX_EXITO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] EX_PDF;
        
        public SI_MMRFC_ENVIAR_PDF_OCResponse() {
        }
        
        public SI_MMRFC_ENVIAR_PDF_OCResponse(string EX_EXITO, byte[] EX_PDF) {
            this.EX_EXITO = EX_EXITO;
            this.EX_PDF = EX_PDF;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_MMRFC_ENVIAR_PDF_OCChannel : SustitucionMOAWS.ObtenerPDFOrdenCompraWebServiceMOA.SI_MMRFC_ENVIAR_PDF_OC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_MMRFC_ENVIAR_PDF_OCClient : System.ServiceModel.ClientBase<SustitucionMOAWS.ObtenerPDFOrdenCompraWebServiceMOA.SI_MMRFC_ENVIAR_PDF_OC>, SustitucionMOAWS.ObtenerPDFOrdenCompraWebServiceMOA.SI_MMRFC_ENVIAR_PDF_OC {
        
        public SI_MMRFC_ENVIAR_PDF_OCClient() {
        }
        
        public SI_MMRFC_ENVIAR_PDF_OCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_MMRFC_ENVIAR_PDF_OCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MMRFC_ENVIAR_PDF_OCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MMRFC_ENVIAR_PDF_OCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SustitucionMOAWS.ObtenerPDFOrdenCompraWebServiceMOA.SI_MMRFC_ENVIAR_PDF_OCResponse SustitucionMOAWS.ObtenerPDFOrdenCompraWebServiceMOA.SI_MMRFC_ENVIAR_PDF_OC.SI_MMRFC_ENVIAR_PDF_OC(SustitucionMOAWS.ObtenerPDFOrdenCompraWebServiceMOA.SI_MMRFC_ENVIAR_PDF_OCRequest request) {
            return base.Channel.SI_MMRFC_ENVIAR_PDF_OC(request);
        }
        
        public string SI_MMRFC_ENVIAR_PDF_OC(string IM_ORDEN_COMPRA, out byte[] EX_PDF) {
            SustitucionMOAWS.ObtenerPDFOrdenCompraWebServiceMOA.SI_MMRFC_ENVIAR_PDF_OCRequest inValue = new SustitucionMOAWS.ObtenerPDFOrdenCompraWebServiceMOA.SI_MMRFC_ENVIAR_PDF_OCRequest();
            inValue.IM_ORDEN_COMPRA = IM_ORDEN_COMPRA;
            SustitucionMOAWS.ObtenerPDFOrdenCompraWebServiceMOA.SI_MMRFC_ENVIAR_PDF_OCResponse retVal = ((SustitucionMOAWS.ObtenerPDFOrdenCompraWebServiceMOA.SI_MMRFC_ENVIAR_PDF_OC)(this)).SI_MMRFC_ENVIAR_PDF_OC(inValue);
            EX_PDF = retVal.EX_PDF;
            return retVal.EX_EXITO;
        }
        
        public System.Threading.Tasks.Task<SustitucionMOAWS.ObtenerPDFOrdenCompraWebServiceMOA.SI_MMRFC_ENVIAR_PDF_OCResponse> SI_MMRFC_ENVIAR_PDF_OCAsync(SustitucionMOAWS.ObtenerPDFOrdenCompraWebServiceMOA.SI_MMRFC_ENVIAR_PDF_OCRequest request) {
            return base.Channel.SI_MMRFC_ENVIAR_PDF_OCAsync(request);
        }
    }
}
