//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SustitucionMOAWS.CuentaCorrienteWebServiceMOA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:OPERACIONES", ConfigurationName="CuentaCorrienteWebServiceMOA.SI_MPMF_MOAOP_CUENTA_CORRIENTE")]
    public interface SI_MPMF_MOAOP_CUENTA_CORRIENTE {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SustitucionMOAWS.CuentaCorrienteWebServiceMOA.SI_MPMF_MOAOP_CUENTA_CORRIENTEResponse SI_MPMF_MOAOP_CUENTA_CORRIENTE(SustitucionMOAWS.CuentaCorrienteWebServiceMOA.SI_MPMF_MOAOP_CUENTA_CORRIENTERequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SustitucionMOAWS.CuentaCorrienteWebServiceMOA.SI_MPMF_MOAOP_CUENTA_CORRIENTEResponse> SI_MPMF_MOAOP_CUENTA_CORRIENTEAsync(SustitucionMOAWS.CuentaCorrienteWebServiceMOA.SI_MPMF_MOAOP_CUENTA_CORRIENTERequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES4100 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fECHA_OPField;
        
        private string fECHA_OP_HASTAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FECHA_OP {
            get {
                return this.fECHA_OPField;
            }
            set {
                this.fECHA_OPField = value;
                this.RaisePropertyChanged("FECHA_OP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string FECHA_OP_HASTA {
            get {
                return this.fECHA_OP_HASTAField;
            }
            set {
                this.fECHA_OP_HASTAField = value;
                this.RaisePropertyChanged("FECHA_OP_HASTA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES6120 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aGRUPADORField;
        
        private string aUGBLField;
        
        private string cONTRATOField;
        
        private string mONEDAField;
        
        private decimal dEBEField;
        
        private bool dEBEFieldSpecified;
        
        private string dESCRIPField;
        
        private string dOC_DATEField;
        
        private string fEC_VTOField;
        
        private decimal hABERField;
        
        private bool hABERFieldSpecified;
        
        private decimal iMPORTE_ARPField;
        
        private bool iMPORTE_ARPFieldSpecified;
        
        private decimal sALDOField;
        
        private bool sALDOFieldSpecified;
        
        private decimal uKURSField;
        
        private bool uKURSFieldSpecified;
        
        private string xBLNRField;
        
        private string dOC_NOField;
        
        private string fISC_YEARField;
        
        private string cON_PRECIOField;
        
        private string pAGO_DIF_ARPField;
        
        private string dOC_PAGO_DIF_ARPField;
        
        private string fECHA_PAGO_DIF_ARPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string AGRUPADOR {
            get {
                return this.aGRUPADORField;
            }
            set {
                this.aGRUPADORField = value;
                this.RaisePropertyChanged("AGRUPADOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string AUGBL {
            get {
                return this.aUGBLField;
            }
            set {
                this.aUGBLField = value;
                this.RaisePropertyChanged("AUGBL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CONTRATO {
            get {
                return this.cONTRATOField;
            }
            set {
                this.cONTRATOField = value;
                this.RaisePropertyChanged("CONTRATO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MONEDA {
            get {
                return this.mONEDAField;
            }
            set {
                this.mONEDAField = value;
                this.RaisePropertyChanged("MONEDA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal DEBE {
            get {
                return this.dEBEField;
            }
            set {
                this.dEBEField = value;
                this.RaisePropertyChanged("DEBE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DEBESpecified {
            get {
                return this.dEBEFieldSpecified;
            }
            set {
                this.dEBEFieldSpecified = value;
                this.RaisePropertyChanged("DEBESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string DESCRIP {
            get {
                return this.dESCRIPField;
            }
            set {
                this.dESCRIPField = value;
                this.RaisePropertyChanged("DESCRIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string DOC_DATE {
            get {
                return this.dOC_DATEField;
            }
            set {
                this.dOC_DATEField = value;
                this.RaisePropertyChanged("DOC_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string FEC_VTO {
            get {
                return this.fEC_VTOField;
            }
            set {
                this.fEC_VTOField = value;
                this.RaisePropertyChanged("FEC_VTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal HABER {
            get {
                return this.hABERField;
            }
            set {
                this.hABERField = value;
                this.RaisePropertyChanged("HABER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HABERSpecified {
            get {
                return this.hABERFieldSpecified;
            }
            set {
                this.hABERFieldSpecified = value;
                this.RaisePropertyChanged("HABERSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal IMPORTE_ARP {
            get {
                return this.iMPORTE_ARPField;
            }
            set {
                this.iMPORTE_ARPField = value;
                this.RaisePropertyChanged("IMPORTE_ARP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IMPORTE_ARPSpecified {
            get {
                return this.iMPORTE_ARPFieldSpecified;
            }
            set {
                this.iMPORTE_ARPFieldSpecified = value;
                this.RaisePropertyChanged("IMPORTE_ARPSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal SALDO {
            get {
                return this.sALDOField;
            }
            set {
                this.sALDOField = value;
                this.RaisePropertyChanged("SALDO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SALDOSpecified {
            get {
                return this.sALDOFieldSpecified;
            }
            set {
                this.sALDOFieldSpecified = value;
                this.RaisePropertyChanged("SALDOSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal UKURS {
            get {
                return this.uKURSField;
            }
            set {
                this.uKURSField = value;
                this.RaisePropertyChanged("UKURS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UKURSSpecified {
            get {
                return this.uKURSFieldSpecified;
            }
            set {
                this.uKURSFieldSpecified = value;
                this.RaisePropertyChanged("UKURSSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string XBLNR {
            get {
                return this.xBLNRField;
            }
            set {
                this.xBLNRField = value;
                this.RaisePropertyChanged("XBLNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string DOC_NO {
            get {
                return this.dOC_NOField;
            }
            set {
                this.dOC_NOField = value;
                this.RaisePropertyChanged("DOC_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string FISC_YEAR {
            get {
                return this.fISC_YEARField;
            }
            set {
                this.fISC_YEARField = value;
                this.RaisePropertyChanged("FISC_YEAR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string CON_PRECIO {
            get {
                return this.cON_PRECIOField;
            }
            set {
                this.cON_PRECIOField = value;
                this.RaisePropertyChanged("CON_PRECIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string PAGO_DIF_ARP {
            get {
                return this.pAGO_DIF_ARPField;
            }
            set {
                this.pAGO_DIF_ARPField = value;
                this.RaisePropertyChanged("PAGO_DIF_ARP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string DOC_PAGO_DIF_ARP {
            get {
                return this.dOC_PAGO_DIF_ARPField;
            }
            set {
                this.dOC_PAGO_DIF_ARPField = value;
                this.RaisePropertyChanged("DOC_PAGO_DIF_ARP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string FECHA_PAGO_DIF_ARP {
            get {
                return this.fECHA_PAGO_DIF_ARPField;
            }
            set {
                this.fECHA_PAGO_DIF_ARPField = value;
                this.RaisePropertyChanged("FECHA_PAGO_DIF_ARP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES4910 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cODIGOField;
        
        private string dESCRIPCIONField;
        
        private string tIPOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CODIGO {
            get {
                return this.cODIGOField;
            }
            set {
                this.cODIGOField = value;
                this.RaisePropertyChanged("CODIGO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
                this.RaisePropertyChanged("DESCRIPCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TIPO {
            get {
                return this.tIPOField;
            }
            set {
                this.tIPOField = value;
                this.RaisePropertyChanged("TIPO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MPMF_MOAOP_CUENTA_CORRIENTE", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MPMF_MOAOP_CUENTA_CORRIENTERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PE_COMPENSA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PE_CONTRATO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SustitucionMOAWS.CuentaCorrienteWebServiceMOA.ZMPES4100 PE_FECHA_IN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PE_IDPAGO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PE_PROVEEDOR;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PE_RETENCION;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PE_SOCIEDAD;
        
        public SI_MPMF_MOAOP_CUENTA_CORRIENTERequest() {
        }
        
        public SI_MPMF_MOAOP_CUENTA_CORRIENTERequest(string PE_COMPENSA, string PE_CONTRATO, SustitucionMOAWS.CuentaCorrienteWebServiceMOA.ZMPES4100 PE_FECHA_IN, string PE_IDPAGO, string PE_PROVEEDOR, string PE_RETENCION, string PE_SOCIEDAD) {
            this.PE_COMPENSA = PE_COMPENSA;
            this.PE_CONTRATO = PE_CONTRATO;
            this.PE_FECHA_IN = PE_FECHA_IN;
            this.PE_IDPAGO = PE_IDPAGO;
            this.PE_PROVEEDOR = PE_PROVEEDOR;
            this.PE_RETENCION = PE_RETENCION;
            this.PE_SOCIEDAD = PE_SOCIEDAD;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MPMF_MOAOP_CUENTA_CORRIENTE.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MPMF_MOAOP_CUENTA_CORRIENTEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SustitucionMOAWS.CuentaCorrienteWebServiceMOA.ZMPES4910 MENSAJE_ERROR;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.CuentaCorrienteWebServiceMOA.ZMPES6120[] T_SALIDA;
        
        public SI_MPMF_MOAOP_CUENTA_CORRIENTEResponse() {
        }
        
        public SI_MPMF_MOAOP_CUENTA_CORRIENTEResponse(SustitucionMOAWS.CuentaCorrienteWebServiceMOA.ZMPES4910 MENSAJE_ERROR, SustitucionMOAWS.CuentaCorrienteWebServiceMOA.ZMPES6120[] T_SALIDA) {
            this.MENSAJE_ERROR = MENSAJE_ERROR;
            this.T_SALIDA = T_SALIDA;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_MPMF_MOAOP_CUENTA_CORRIENTEChannel : SustitucionMOAWS.CuentaCorrienteWebServiceMOA.SI_MPMF_MOAOP_CUENTA_CORRIENTE, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_MPMF_MOAOP_CUENTA_CORRIENTEClient : System.ServiceModel.ClientBase<SustitucionMOAWS.CuentaCorrienteWebServiceMOA.SI_MPMF_MOAOP_CUENTA_CORRIENTE>, SustitucionMOAWS.CuentaCorrienteWebServiceMOA.SI_MPMF_MOAOP_CUENTA_CORRIENTE {
        
        public SI_MPMF_MOAOP_CUENTA_CORRIENTEClient() {
        }
        
        public SI_MPMF_MOAOP_CUENTA_CORRIENTEClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_MPMF_MOAOP_CUENTA_CORRIENTEClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MPMF_MOAOP_CUENTA_CORRIENTEClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MPMF_MOAOP_CUENTA_CORRIENTEClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SustitucionMOAWS.CuentaCorrienteWebServiceMOA.SI_MPMF_MOAOP_CUENTA_CORRIENTEResponse SustitucionMOAWS.CuentaCorrienteWebServiceMOA.SI_MPMF_MOAOP_CUENTA_CORRIENTE.SI_MPMF_MOAOP_CUENTA_CORRIENTE(SustitucionMOAWS.CuentaCorrienteWebServiceMOA.SI_MPMF_MOAOP_CUENTA_CORRIENTERequest request) {
            return base.Channel.SI_MPMF_MOAOP_CUENTA_CORRIENTE(request);
        }
        
        public SustitucionMOAWS.CuentaCorrienteWebServiceMOA.ZMPES4910 SI_MPMF_MOAOP_CUENTA_CORRIENTE(string PE_COMPENSA, string PE_CONTRATO, SustitucionMOAWS.CuentaCorrienteWebServiceMOA.ZMPES4100 PE_FECHA_IN, string PE_IDPAGO, string PE_PROVEEDOR, string PE_RETENCION, string PE_SOCIEDAD, out SustitucionMOAWS.CuentaCorrienteWebServiceMOA.ZMPES6120[] T_SALIDA) {
            SustitucionMOAWS.CuentaCorrienteWebServiceMOA.SI_MPMF_MOAOP_CUENTA_CORRIENTERequest inValue = new SustitucionMOAWS.CuentaCorrienteWebServiceMOA.SI_MPMF_MOAOP_CUENTA_CORRIENTERequest();
            inValue.PE_COMPENSA = PE_COMPENSA;
            inValue.PE_CONTRATO = PE_CONTRATO;
            inValue.PE_FECHA_IN = PE_FECHA_IN;
            inValue.PE_IDPAGO = PE_IDPAGO;
            inValue.PE_PROVEEDOR = PE_PROVEEDOR;
            inValue.PE_RETENCION = PE_RETENCION;
            inValue.PE_SOCIEDAD = PE_SOCIEDAD;
            SustitucionMOAWS.CuentaCorrienteWebServiceMOA.SI_MPMF_MOAOP_CUENTA_CORRIENTEResponse retVal = ((SustitucionMOAWS.CuentaCorrienteWebServiceMOA.SI_MPMF_MOAOP_CUENTA_CORRIENTE)(this)).SI_MPMF_MOAOP_CUENTA_CORRIENTE(inValue);
            T_SALIDA = retVal.T_SALIDA;
            return retVal.MENSAJE_ERROR;
        }
        
        public System.Threading.Tasks.Task<SustitucionMOAWS.CuentaCorrienteWebServiceMOA.SI_MPMF_MOAOP_CUENTA_CORRIENTEResponse> SI_MPMF_MOAOP_CUENTA_CORRIENTEAsync(SustitucionMOAWS.CuentaCorrienteWebServiceMOA.SI_MPMF_MOAOP_CUENTA_CORRIENTERequest request) {
            return base.Channel.SI_MPMF_MOAOP_CUENTA_CORRIENTEAsync(request);
        }
    }
}
