//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SustitucionMOAWS.AplicacionCartaPortePendienteAplicarWebServiceMOA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:OPERACIONES", ConfigurationName="AplicacionCartaPortePendienteAplicarWebServiceMOA.SI_MPMF_MOAOP_PENDIENTE_APLICAR" +
        "")]
    public interface SI_MPMF_MOAOP_PENDIENTE_APLICAR {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SustitucionMOAWS.AplicacionCartaPortePendienteAplicarWebServiceMOA.SI_MPMF_MOAOP_PENDIENTE_APLICARResponse SI_MPMF_MOAOP_PENDIENTE_APLICAR(SustitucionMOAWS.AplicacionCartaPortePendienteAplicarWebServiceMOA.SI_MPMF_MOAOP_PENDIENTE_APLICARRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SustitucionMOAWS.AplicacionCartaPortePendienteAplicarWebServiceMOA.SI_MPMF_MOAOP_PENDIENTE_APLICARResponse> SI_MPMF_MOAOP_PENDIENTE_APLICARAsync(SustitucionMOAWS.AplicacionCartaPortePendienteAplicarWebServiceMOA.SI_MPMF_MOAOP_PENDIENTE_APLICARRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES7070 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pROVEEDORField;
        
        private string cORREDORField;
        
        private string aGENTE_COMPRAField;
        
        private string cCPPField;
        
        private string mATERIALField;
        
        private string cENTROField;
        
        private decimal cANTIDADField;
        
        private bool cANTIDADFieldSpecified;
        
        private string aLMACENField;
        
        private string fECHA_NETOField;
        
        private string fECHA_INGRESOField;
        
        private string cTGField;
        
        private string cUIT_SOLICITANTEField;
        
        private string cONTRATOField;
        
        private decimal kILOS_CONTField;
        
        private bool kILOS_CONTFieldSpecified;
        
        private string ePAField;
        
        private string rEGIONField;
        
        private string sUSTENTABLEField;
        
        private string cD_CGField;
        
        private string wARRANTField;
        
        private string cANJEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PROVEEDOR {
            get {
                return this.pROVEEDORField;
            }
            set {
                this.pROVEEDORField = value;
                this.RaisePropertyChanged("PROVEEDOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CORREDOR {
            get {
                return this.cORREDORField;
            }
            set {
                this.cORREDORField = value;
                this.RaisePropertyChanged("CORREDOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string AGENTE_COMPRA {
            get {
                return this.aGENTE_COMPRAField;
            }
            set {
                this.aGENTE_COMPRAField = value;
                this.RaisePropertyChanged("AGENTE_COMPRA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CCPP {
            get {
                return this.cCPPField;
            }
            set {
                this.cCPPField = value;
                this.RaisePropertyChanged("CCPP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string MATERIAL {
            get {
                return this.mATERIALField;
            }
            set {
                this.mATERIALField = value;
                this.RaisePropertyChanged("MATERIAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string CENTRO {
            get {
                return this.cENTROField;
            }
            set {
                this.cENTROField = value;
                this.RaisePropertyChanged("CENTRO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal CANTIDAD {
            get {
                return this.cANTIDADField;
            }
            set {
                this.cANTIDADField = value;
                this.RaisePropertyChanged("CANTIDAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CANTIDADSpecified {
            get {
                return this.cANTIDADFieldSpecified;
            }
            set {
                this.cANTIDADFieldSpecified = value;
                this.RaisePropertyChanged("CANTIDADSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ALMACEN {
            get {
                return this.aLMACENField;
            }
            set {
                this.aLMACENField = value;
                this.RaisePropertyChanged("ALMACEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string FECHA_NETO {
            get {
                return this.fECHA_NETOField;
            }
            set {
                this.fECHA_NETOField = value;
                this.RaisePropertyChanged("FECHA_NETO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string FECHA_INGRESO {
            get {
                return this.fECHA_INGRESOField;
            }
            set {
                this.fECHA_INGRESOField = value;
                this.RaisePropertyChanged("FECHA_INGRESO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string CTG {
            get {
                return this.cTGField;
            }
            set {
                this.cTGField = value;
                this.RaisePropertyChanged("CTG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string CUIT_SOLICITANTE {
            get {
                return this.cUIT_SOLICITANTEField;
            }
            set {
                this.cUIT_SOLICITANTEField = value;
                this.RaisePropertyChanged("CUIT_SOLICITANTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string CONTRATO {
            get {
                return this.cONTRATOField;
            }
            set {
                this.cONTRATOField = value;
                this.RaisePropertyChanged("CONTRATO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public decimal KILOS_CONT {
            get {
                return this.kILOS_CONTField;
            }
            set {
                this.kILOS_CONTField = value;
                this.RaisePropertyChanged("KILOS_CONT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KILOS_CONTSpecified {
            get {
                return this.kILOS_CONTFieldSpecified;
            }
            set {
                this.kILOS_CONTFieldSpecified = value;
                this.RaisePropertyChanged("KILOS_CONTSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string EPA {
            get {
                return this.ePAField;
            }
            set {
                this.ePAField = value;
                this.RaisePropertyChanged("EPA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string REGION {
            get {
                return this.rEGIONField;
            }
            set {
                this.rEGIONField = value;
                this.RaisePropertyChanged("REGION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string SUSTENTABLE {
            get {
                return this.sUSTENTABLEField;
            }
            set {
                this.sUSTENTABLEField = value;
                this.RaisePropertyChanged("SUSTENTABLE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string CD_CG {
            get {
                return this.cD_CGField;
            }
            set {
                this.cD_CGField = value;
                this.RaisePropertyChanged("CD_CG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string WARRANT {
            get {
                return this.wARRANTField;
            }
            set {
                this.wARRANTField = value;
                this.RaisePropertyChanged("WARRANT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string CANJE {
            get {
                return this.cANJEField;
            }
            set {
                this.cANJEField = value;
                this.RaisePropertyChanged("CANJE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MPMF_MOAOP_PENDIENTE_APLICAR", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MPMF_MOAOP_PENDIENTE_APLICARRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_CORREDOR;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_MATERIAL;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_PROVEEDOR;
        
        public SI_MPMF_MOAOP_PENDIENTE_APLICARRequest() {
        }
        
        public SI_MPMF_MOAOP_PENDIENTE_APLICARRequest(string IM_CORREDOR, string IM_MATERIAL, string IM_PROVEEDOR) {
            this.IM_CORREDOR = IM_CORREDOR;
            this.IM_MATERIAL = IM_MATERIAL;
            this.IM_PROVEEDOR = IM_PROVEEDOR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MPMF_MOAOP_PENDIENTE_APLICAR.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MPMF_MOAOP_PENDIENTE_APLICARResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EX_MENSAJE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.AplicacionCartaPortePendienteAplicarWebServiceMOA.ZMPES7070[] EX_SALIDA;
        
        public SI_MPMF_MOAOP_PENDIENTE_APLICARResponse() {
        }
        
        public SI_MPMF_MOAOP_PENDIENTE_APLICARResponse(string EX_MENSAJE, SustitucionMOAWS.AplicacionCartaPortePendienteAplicarWebServiceMOA.ZMPES7070[] EX_SALIDA) {
            this.EX_MENSAJE = EX_MENSAJE;
            this.EX_SALIDA = EX_SALIDA;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_MPMF_MOAOP_PENDIENTE_APLICARChannel : SustitucionMOAWS.AplicacionCartaPortePendienteAplicarWebServiceMOA.SI_MPMF_MOAOP_PENDIENTE_APLICAR, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_MPMF_MOAOP_PENDIENTE_APLICARClient : System.ServiceModel.ClientBase<SustitucionMOAWS.AplicacionCartaPortePendienteAplicarWebServiceMOA.SI_MPMF_MOAOP_PENDIENTE_APLICAR>, SustitucionMOAWS.AplicacionCartaPortePendienteAplicarWebServiceMOA.SI_MPMF_MOAOP_PENDIENTE_APLICAR {
        
        public SI_MPMF_MOAOP_PENDIENTE_APLICARClient() {
        }
        
        public SI_MPMF_MOAOP_PENDIENTE_APLICARClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_MPMF_MOAOP_PENDIENTE_APLICARClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MPMF_MOAOP_PENDIENTE_APLICARClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MPMF_MOAOP_PENDIENTE_APLICARClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SustitucionMOAWS.AplicacionCartaPortePendienteAplicarWebServiceMOA.SI_MPMF_MOAOP_PENDIENTE_APLICARResponse SustitucionMOAWS.AplicacionCartaPortePendienteAplicarWebServiceMOA.SI_MPMF_MOAOP_PENDIENTE_APLICAR.SI_MPMF_MOAOP_PENDIENTE_APLICAR(SustitucionMOAWS.AplicacionCartaPortePendienteAplicarWebServiceMOA.SI_MPMF_MOAOP_PENDIENTE_APLICARRequest request) {
            return base.Channel.SI_MPMF_MOAOP_PENDIENTE_APLICAR(request);
        }
        
        public string SI_MPMF_MOAOP_PENDIENTE_APLICAR(string IM_CORREDOR, string IM_MATERIAL, string IM_PROVEEDOR, out SustitucionMOAWS.AplicacionCartaPortePendienteAplicarWebServiceMOA.ZMPES7070[] EX_SALIDA) {
            SustitucionMOAWS.AplicacionCartaPortePendienteAplicarWebServiceMOA.SI_MPMF_MOAOP_PENDIENTE_APLICARRequest inValue = new SustitucionMOAWS.AplicacionCartaPortePendienteAplicarWebServiceMOA.SI_MPMF_MOAOP_PENDIENTE_APLICARRequest();
            inValue.IM_CORREDOR = IM_CORREDOR;
            inValue.IM_MATERIAL = IM_MATERIAL;
            inValue.IM_PROVEEDOR = IM_PROVEEDOR;
            SustitucionMOAWS.AplicacionCartaPortePendienteAplicarWebServiceMOA.SI_MPMF_MOAOP_PENDIENTE_APLICARResponse retVal = ((SustitucionMOAWS.AplicacionCartaPortePendienteAplicarWebServiceMOA.SI_MPMF_MOAOP_PENDIENTE_APLICAR)(this)).SI_MPMF_MOAOP_PENDIENTE_APLICAR(inValue);
            EX_SALIDA = retVal.EX_SALIDA;
            return retVal.EX_MENSAJE;
        }
        
        public System.Threading.Tasks.Task<SustitucionMOAWS.AplicacionCartaPortePendienteAplicarWebServiceMOA.SI_MPMF_MOAOP_PENDIENTE_APLICARResponse> SI_MPMF_MOAOP_PENDIENTE_APLICARAsync(SustitucionMOAWS.AplicacionCartaPortePendienteAplicarWebServiceMOA.SI_MPMF_MOAOP_PENDIENTE_APLICARRequest request) {
            return base.Channel.SI_MPMF_MOAOP_PENDIENTE_APLICARAsync(request);
        }
    }
}
