//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SustitucionMOAWS.ListarPesificaciones {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:OPERACIONES", ConfigurationName="ListarPesificaciones.SI_MPMF_MOAOP_LISTAR_PESIF")]
    public interface SI_MPMF_MOAOP_LISTAR_PESIF {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:sap-com:document:sap:rfc:functions) of message SI_MPMF_MOAOP_LISTAR_PESIFRequest does not match the default value (urn:OPERACIONES)
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SustitucionMOAWS.ListarPesificaciones.SI_MPMF_MOAOP_LISTAR_PESIFResponse SI_MPMF_MOAOP_LISTAR_PESIF(SustitucionMOAWS.ListarPesificaciones.SI_MPMF_MOAOP_LISTAR_PESIFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SustitucionMOAWS.ListarPesificaciones.SI_MPMF_MOAOP_LISTAR_PESIFResponse> SI_MPMF_MOAOP_LISTAR_PESIFAsync(SustitucionMOAWS.ListarPesificaciones.SI_MPMF_MOAOP_LISTAR_PESIFRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES6500 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fECHA_CARGAField;
        
        private string cONTRATOField;
        
        private string fIJACIONField;
        
        private decimal kILOSField;
        
        private bool kILOSFieldSpecified;
        
        private decimal pRECIOField;
        
        private bool pRECIOFieldSpecified;
        
        private string fECHA_PESIFICACIONField;
        
        private decimal tIPO_CAMBIOField;
        
        private bool tIPO_CAMBIOFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FECHA_CARGA {
            get {
                return this.fECHA_CARGAField;
            }
            set {
                this.fECHA_CARGAField = value;
                this.RaisePropertyChanged("FECHA_CARGA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CONTRATO {
            get {
                return this.cONTRATOField;
            }
            set {
                this.cONTRATOField = value;
                this.RaisePropertyChanged("CONTRATO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string FIJACION {
            get {
                return this.fIJACIONField;
            }
            set {
                this.fIJACIONField = value;
                this.RaisePropertyChanged("FIJACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal KILOS {
            get {
                return this.kILOSField;
            }
            set {
                this.kILOSField = value;
                this.RaisePropertyChanged("KILOS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KILOSSpecified {
            get {
                return this.kILOSFieldSpecified;
            }
            set {
                this.kILOSFieldSpecified = value;
                this.RaisePropertyChanged("KILOSSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal PRECIO {
            get {
                return this.pRECIOField;
            }
            set {
                this.pRECIOField = value;
                this.RaisePropertyChanged("PRECIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PRECIOSpecified {
            get {
                return this.pRECIOFieldSpecified;
            }
            set {
                this.pRECIOFieldSpecified = value;
                this.RaisePropertyChanged("PRECIOSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string FECHA_PESIFICACION {
            get {
                return this.fECHA_PESIFICACIONField;
            }
            set {
                this.fECHA_PESIFICACIONField = value;
                this.RaisePropertyChanged("FECHA_PESIFICACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal TIPO_CAMBIO {
            get {
                return this.tIPO_CAMBIOField;
            }
            set {
                this.tIPO_CAMBIOField = value;
                this.RaisePropertyChanged("TIPO_CAMBIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TIPO_CAMBIOSpecified {
            get {
                return this.tIPO_CAMBIOFieldSpecified;
            }
            set {
                this.tIPO_CAMBIOFieldSpecified = value;
                this.RaisePropertyChanged("TIPO_CAMBIOSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MPMF_MOAOP_LISTAR_PESIF", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MPMF_MOAOP_LISTAR_PESIFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_LIFNR;
        
        public SI_MPMF_MOAOP_LISTAR_PESIFRequest() {
        }
        
        public SI_MPMF_MOAOP_LISTAR_PESIFRequest(string IM_LIFNR) {
            this.IM_LIFNR = IM_LIFNR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MPMF_MOAOP_LISTAR_PESIF.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MPMF_MOAOP_LISTAR_PESIFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.ListarPesificaciones.ZMPES6500[] EX_SALIDA;
        
        public SI_MPMF_MOAOP_LISTAR_PESIFResponse() {
        }
        
        public SI_MPMF_MOAOP_LISTAR_PESIFResponse(SustitucionMOAWS.ListarPesificaciones.ZMPES6500[] EX_SALIDA) {
            this.EX_SALIDA = EX_SALIDA;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_MPMF_MOAOP_LISTAR_PESIFChannel : SustitucionMOAWS.ListarPesificaciones.SI_MPMF_MOAOP_LISTAR_PESIF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_MPMF_MOAOP_LISTAR_PESIFClient : System.ServiceModel.ClientBase<SustitucionMOAWS.ListarPesificaciones.SI_MPMF_MOAOP_LISTAR_PESIF>, SustitucionMOAWS.ListarPesificaciones.SI_MPMF_MOAOP_LISTAR_PESIF {
        
        public SI_MPMF_MOAOP_LISTAR_PESIFClient() {
        }
        
        public SI_MPMF_MOAOP_LISTAR_PESIFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_MPMF_MOAOP_LISTAR_PESIFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MPMF_MOAOP_LISTAR_PESIFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MPMF_MOAOP_LISTAR_PESIFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SustitucionMOAWS.ListarPesificaciones.SI_MPMF_MOAOP_LISTAR_PESIFResponse SustitucionMOAWS.ListarPesificaciones.SI_MPMF_MOAOP_LISTAR_PESIF.SI_MPMF_MOAOP_LISTAR_PESIF(SustitucionMOAWS.ListarPesificaciones.SI_MPMF_MOAOP_LISTAR_PESIFRequest request) {
            return base.Channel.SI_MPMF_MOAOP_LISTAR_PESIF(request);
        }
        
        public SustitucionMOAWS.ListarPesificaciones.ZMPES6500[] SI_MPMF_MOAOP_LISTAR_PESIF(string IM_LIFNR) {
            SustitucionMOAWS.ListarPesificaciones.SI_MPMF_MOAOP_LISTAR_PESIFRequest inValue = new SustitucionMOAWS.ListarPesificaciones.SI_MPMF_MOAOP_LISTAR_PESIFRequest();
            inValue.IM_LIFNR = IM_LIFNR;
            SustitucionMOAWS.ListarPesificaciones.SI_MPMF_MOAOP_LISTAR_PESIFResponse retVal = ((SustitucionMOAWS.ListarPesificaciones.SI_MPMF_MOAOP_LISTAR_PESIF)(this)).SI_MPMF_MOAOP_LISTAR_PESIF(inValue);
            return retVal.EX_SALIDA;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SustitucionMOAWS.ListarPesificaciones.SI_MPMF_MOAOP_LISTAR_PESIFResponse> SustitucionMOAWS.ListarPesificaciones.SI_MPMF_MOAOP_LISTAR_PESIF.SI_MPMF_MOAOP_LISTAR_PESIFAsync(SustitucionMOAWS.ListarPesificaciones.SI_MPMF_MOAOP_LISTAR_PESIFRequest request) {
            return base.Channel.SI_MPMF_MOAOP_LISTAR_PESIFAsync(request);
        }
        
        public System.Threading.Tasks.Task<SustitucionMOAWS.ListarPesificaciones.SI_MPMF_MOAOP_LISTAR_PESIFResponse> SI_MPMF_MOAOP_LISTAR_PESIFAsync(string IM_LIFNR) {
            SustitucionMOAWS.ListarPesificaciones.SI_MPMF_MOAOP_LISTAR_PESIFRequest inValue = new SustitucionMOAWS.ListarPesificaciones.SI_MPMF_MOAOP_LISTAR_PESIFRequest();
            inValue.IM_LIFNR = IM_LIFNR;
            return ((SustitucionMOAWS.ListarPesificaciones.SI_MPMF_MOAOP_LISTAR_PESIF)(this)).SI_MPMF_MOAOP_LISTAR_PESIFAsync(inValue);
        }
    }
}
