//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SustitucionMOAWS.UsuariosWebServiceMOA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:OPERACIONES", ConfigurationName="UsuariosWebServiceMOA.SI_MPMF_MOAOP_USUARIOS")]
    public interface SI_MPMF_MOAOP_USUARIOS {
        
        // CODEGEN: Generating message contract since the operation SI_MPMF_MOAOP_USUARIOS is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SustitucionMOAWS.UsuariosWebServiceMOA.SI_MPMF_MOAOP_USUARIOSResponse SI_MPMF_MOAOP_USUARIOS(SustitucionMOAWS.UsuariosWebServiceMOA.SI_MPMF_MOAOP_USUARIOSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SustitucionMOAWS.UsuariosWebServiceMOA.SI_MPMF_MOAOP_USUARIOSResponse> SI_MPMF_MOAOP_USUARIOSAsync(SustitucionMOAWS.UsuariosWebServiceMOA.SI_MPMF_MOAOP_USUARIOSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES6060 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uSUARIOField;
        
        private string vENDEDORField;
        
        private string idField;
        
        private string tIPOField;
        
        private string bLOQUEOField;
        
        private string eSTADOField;
        
        private string dESCRIPCIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string USUARIO {
            get {
                return this.uSUARIOField;
            }
            set {
                this.uSUARIOField = value;
                this.RaisePropertyChanged("USUARIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string VENDEDOR {
            get {
                return this.vENDEDORField;
            }
            set {
                this.vENDEDORField = value;
                this.RaisePropertyChanged("VENDEDOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TIPO {
            get {
                return this.tIPOField;
            }
            set {
                this.tIPOField = value;
                this.RaisePropertyChanged("TIPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string BLOQUEO {
            get {
                return this.bLOQUEOField;
            }
            set {
                this.bLOQUEOField = value;
                this.RaisePropertyChanged("BLOQUEO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
                this.RaisePropertyChanged("ESTADO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
                this.RaisePropertyChanged("DESCRIPCION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPMF_MOAOP_USUARIOSResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZMPES6060[] uSUARIOSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMPES6060[] USUARIOS {
            get {
                return this.uSUARIOSField;
            }
            set {
                this.uSUARIOSField = value;
                this.RaisePropertyChanged("USUARIOS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_MPMF_MOAOP_USUARIOSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public object Z_MPMF_MOAOP_USUARIOS;
        
        public SI_MPMF_MOAOP_USUARIOSRequest() {
        }
        
        public SI_MPMF_MOAOP_USUARIOSRequest(object Z_MPMF_MOAOP_USUARIOS) {
            this.Z_MPMF_MOAOP_USUARIOS = Z_MPMF_MOAOP_USUARIOS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_MPMF_MOAOP_USUARIOSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Z_MPMF_MOAOP_USUARIOS.Response", Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Z_MPMF_MOAOP_USUARIOS.Response")]
        public SustitucionMOAWS.UsuariosWebServiceMOA.Z_MPMF_MOAOP_USUARIOSResponse Z_MPMF_MOAOP_USUARIOSResponse;
        
        public SI_MPMF_MOAOP_USUARIOSResponse() {
        }
        
        public SI_MPMF_MOAOP_USUARIOSResponse(SustitucionMOAWS.UsuariosWebServiceMOA.Z_MPMF_MOAOP_USUARIOSResponse Z_MPMF_MOAOP_USUARIOSResponse) {
            this.Z_MPMF_MOAOP_USUARIOSResponse = Z_MPMF_MOAOP_USUARIOSResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_MPMF_MOAOP_USUARIOSChannel : SustitucionMOAWS.UsuariosWebServiceMOA.SI_MPMF_MOAOP_USUARIOS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_MPMF_MOAOP_USUARIOSClient : System.ServiceModel.ClientBase<SustitucionMOAWS.UsuariosWebServiceMOA.SI_MPMF_MOAOP_USUARIOS>, SustitucionMOAWS.UsuariosWebServiceMOA.SI_MPMF_MOAOP_USUARIOS {
        
        public SI_MPMF_MOAOP_USUARIOSClient() {
        }
        
        public SI_MPMF_MOAOP_USUARIOSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_MPMF_MOAOP_USUARIOSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MPMF_MOAOP_USUARIOSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MPMF_MOAOP_USUARIOSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SustitucionMOAWS.UsuariosWebServiceMOA.SI_MPMF_MOAOP_USUARIOSResponse SustitucionMOAWS.UsuariosWebServiceMOA.SI_MPMF_MOAOP_USUARIOS.SI_MPMF_MOAOP_USUARIOS(SustitucionMOAWS.UsuariosWebServiceMOA.SI_MPMF_MOAOP_USUARIOSRequest request) {
            return base.Channel.SI_MPMF_MOAOP_USUARIOS(request);
        }
        
        public SustitucionMOAWS.UsuariosWebServiceMOA.Z_MPMF_MOAOP_USUARIOSResponse SI_MPMF_MOAOP_USUARIOS(object Z_MPMF_MOAOP_USUARIOS) {
            SustitucionMOAWS.UsuariosWebServiceMOA.SI_MPMF_MOAOP_USUARIOSRequest inValue = new SustitucionMOAWS.UsuariosWebServiceMOA.SI_MPMF_MOAOP_USUARIOSRequest();
            inValue.Z_MPMF_MOAOP_USUARIOS = Z_MPMF_MOAOP_USUARIOS;
            SustitucionMOAWS.UsuariosWebServiceMOA.SI_MPMF_MOAOP_USUARIOSResponse retVal = ((SustitucionMOAWS.UsuariosWebServiceMOA.SI_MPMF_MOAOP_USUARIOS)(this)).SI_MPMF_MOAOP_USUARIOS(inValue);
            return retVal.Z_MPMF_MOAOP_USUARIOSResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SustitucionMOAWS.UsuariosWebServiceMOA.SI_MPMF_MOAOP_USUARIOSResponse> SustitucionMOAWS.UsuariosWebServiceMOA.SI_MPMF_MOAOP_USUARIOS.SI_MPMF_MOAOP_USUARIOSAsync(SustitucionMOAWS.UsuariosWebServiceMOA.SI_MPMF_MOAOP_USUARIOSRequest request) {
            return base.Channel.SI_MPMF_MOAOP_USUARIOSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SustitucionMOAWS.UsuariosWebServiceMOA.SI_MPMF_MOAOP_USUARIOSResponse> SI_MPMF_MOAOP_USUARIOSAsync(object Z_MPMF_MOAOP_USUARIOS) {
            SustitucionMOAWS.UsuariosWebServiceMOA.SI_MPMF_MOAOP_USUARIOSRequest inValue = new SustitucionMOAWS.UsuariosWebServiceMOA.SI_MPMF_MOAOP_USUARIOSRequest();
            inValue.Z_MPMF_MOAOP_USUARIOS = Z_MPMF_MOAOP_USUARIOS;
            return ((SustitucionMOAWS.UsuariosWebServiceMOA.SI_MPMF_MOAOP_USUARIOS)(this)).SI_MPMF_MOAOP_USUARIOSAsync(inValue);
        }
    }
}
