-- Verifica que la tabla esté vacía antes de insertar
IF NOT EXISTS (SELECT 1 FROM dbo.TipoRetencion)
BEGIN

	INSERT INTO dbo.TipoRetencion (Id, DenominacionActual, DescripcionWeb)
	VALUES ('B1', 'RETENCIÓN IIBB BUENOS AIRES 01/2004', 'IB Bs As - Productor'),
	('B2', 'RETENCIÓN IIBB CORDOBA 443/2004', 'NO ACTIVO'),
	('B3', 'RETENCIÓN IIBB SANTA FE 15/1997', 'IB Sta fe - Productor'),
	('B4', 'RETENCIÓN IIBB CORDOBA 443/2004', 'NO ACTIVO'),
	('B5', 'RETENCIÓN IIBB BUENOS AIRES 01/2002', 'NO ACTIVO'),
	('B6', 'RETENCIÓN IIBB SANTA FE 15/1997', 'IB Sta Fe  - No productor'),
	('B7', 'RETENCIÓN IIBB SGO. ESTERO 08/2012', 'NO ACTIVO'),
	('B8', 'RETENCIÓN IIBB SGO. ESTERO 08/2012', 'NO ACTIVO'),
	('B9', 'RETENCIÓN IIBB ENTRE RIOS', 'NO ACTIVO'),
	('BA', 'RETENCIÓN IIBB INSC. SGO. ESTERO 08/2012', 'NO ACTIVO'),
	('BJ', 'RETENCIÓN IIBB SAN JUAN Res3236', 'NO ACTIVO'),
	('BL', 'RETENCIÓN IIBB SAN LUIS 15/2000', 'NO ACTIVO'),
	('CO', 'Retención Seg. Social - Subcontratistas', 'SUSS - Seguridad Social'),
	('CT', 'RETENCIÓN IIBB TUCUMÁN 111/2006', 'NO ACTIVO'),
	('EA', 'Ret.Seg. Social - Emplead.event.anexo', 'SUSS - Seguridad Social'),
	('EE', 'Retención Seg. Social - Empleados event.', 'SUSS - Seguridad Social'),
	('EM', 'RG 2682 Proveedores Normales Ingenieria', 'SUSS - Seguridad Social'),
	('EN', 'RG 2682 Proveedores Normales Arquitectur', 'SUSS - Seguridad Social'),
	('EP', 'Retención Seg.Social - General', 'SUSS - Seguridad Social'),
	('ES', 'Retención Seg.Social - Empr.de Seguridad', 'SUSS - Seguridad Social'),
	('EU', 'RG 2682 Proveedores ÚTES Arquitectura', 'NO ACTIVO'),
	('EV', 'RG 2682 Proveedores ÚTES Ingeniería', 'NO ACTIVO'),
	('G1', 'RG 830/00 - Ret. Imp.a las Ganancias RNI', 'NO ACTIVO'),
	('GA', 'RG 830/00 - Ret. Imp. a las Ganancias RI', 'Ganancias'),
	('GB', 'RG 830/00-RI  P.FIS(AXI)/P.JURIDICA', 'NO ACTIVO'),
	('GC', 'RG 830 -Ret.Imp.a las Ganancias RNI-F.Cr', 'NO ACTIVO'),
	('GD', 'RETENCIÓN GANANCIAS 2118/2006', 'NO ACTIVO'),
	('GE', 'RETENCIÓN GANANCIAS 4325/2018', 'NO ACTIVO'),
	('GF', 'RG 830 -Ret.Imp.a las Ganancias RI-F.Cr', 'NO ACTIVO'),
	('GH', 'RETENCIÓN GANANCIAS 2118/2006', 'NO ACTIVO'),
	('GI', 'RETENCIÓN GANANCIAS 4325/2018', 'NO ACTIVO'),
	('GJ', 'RETENCIÓN GANANCIAS 2118/2006', 'NO ACTIVO'),
	('GK', 'RETENCIÓN GANANCIAS 4325/2018', 'NO ACTIVO'),
	('GL', 'RG 1575 - Ret. Ganancias RI - Factura M', 'NO ACTIVO'),
	('GM', 'RG 884/00 - Ret. Imp. a las Ganancias RI', 'NO ACTIVO'),
	('GN', 'RETENCIÓN GANANCIAS 4325/2018', 'NO ACTIVO'),
	('GP', 'RETENCIÓN GANANCIAS 2118/2006', 'NO ACTIVO'),
	('GQ', 'RETENCIÓN GANANCIAS 4325/2018-Imp Neto', 'NO ACTIVO'),
	('GR', 'RETENCIÓN GANANCIAS 4325/2018', 'NO ACTIVO'),
	('GS', 'RG 2549 Ret Gcias Monotributistas', 'Ganancias - Monotributo'),
	('GU', 'RG 830 -Ret.Imp.a las Ganancias RI-Gr.up', 'NO ACTIVO'),
	('GV', 'Ret. Imp. a las Ganancias RG3594/2014', 'NO ACTIVO'),
	('GZ', 'RETENCIÓN GANANCIAS 4325/2018', 'NO ACTIVO'),
	('I0', 'RETENCIÓN IIBB SAN LUIS 15/2000', 'NO ACTIVO'),
	('I1', 'RETENCIÓN IIBB BUENOS AIRES 01/2002', 'NO ACTIVO'),
	('I2', 'RETENCIÓN IIBB CORDOBA 443/2004', 'NO ACTIVO'),
	('I3', 'RETENCIÓN IIBB SANTA FE 15/1997', 'NO ACTIVO'),
	('I4', 'RETENCIÓN IIBB CHACO 1214/1994', 'IB Chaco'),
	('I5', 'RETENCIÓN IIBB MISIONES 03/1993', 'NO ACTIVO'),
	('I6', 'RETENCIÓN IIBB CORRIENTES 165/2000', 'NO ACTIVO'),
	('I7', 'RETENCIÓN IIBB LA PAMPA 273/2002', 'IB La Pampa'),
	('I8', 'RETENCIÓN IIBB CAPITAL FEDERAL 533/2000', 'NO ACTIVO'),
	('I9', 'RETENCIÓN IIBB JUJUY 993/2001', 'NO ACTIVO'),
	('IA', 'Ret.IVA para Sujetos No Categorizados', 'NO ACTIVO'),
	('IB', 'RETENCIÓN IIBB', 'NO ACTIVO'),
	('IC', 'RETENCIÓN IIBB SANTA FE 15/1997', 'NO ACTIVO'),
	('ID', 'Ret.de IIBB - San Luis', 'NO ACTIVO'),
	('IE', 'RETENCIÓN IVA COMISIÓN 18/1997', 'NO ACTIVO'),
	('IF', 'RETENCIÓN IVA RG 4248/2018', 'NO ACTIVO'),
	('IG', 'Retención de IVA SOBRE CPRA GRANOS', 'NO ACTIVO'),
	('IH', 'RETENCIÓN  IVA CANJE 17/1997', 'NO ACTIVO'),
	('II', 'RETENCIÓN IIBB SANTA FE 15/1997', 'IB Sta Fe - Rg Gral. - CM y No inscripto'),
	('IJ', 'RG 1575 - Retención IVA -RI- Factura M', 'NO ACTIVO'),
	('IK', 'RETENCIÓN IIBB CORRIENTES 165/2000', 'NO ACTIVO'),
	('IL', 'Ret.Ingresos Brutos - San Luis - S/B', 'NO ACTIVO'),
	('IM', 'RETENCIÓN IIBB MENDOZA 31/2003', 'NO ACTIVO'),
	('IN', 'Ret.de IIBB - Río Negro', 'NO ACTIVO'),
	('IO', 'RETENCIÓN IIBB CAPITAL FEDERAL 251/2008', 'NO ACTIVO'),
	('IP', 'Retención de IVA Promoción industrial', 'NO ACTIVO'),
	('IQ', 'RETENCIÓN IIBB SALTA 08/2003', 'IB Salta'),
	('IR', 'Ret.de IIBB - La Rioja -S/B', 'NO ACTIVO'),
	('IS', 'IVA s/Importación de Servicios', 'NO ACTIVO'),
	('IT', 'RETENCIÓN IIBB TUCUMÁN 111/2006', 'NO ACTIVO'),
	('IU', 'RETENCIÓN IIBB TUCUMÁN 111/2006', 'NO ACTIVO'),
	('IV', 'RETENCIÓN  IVA  17/1997', 'IVA'),
	('IW', 'RETENCIÓN  IVA  18/1997', 'NO ACTIVO'),
	('IX', 'Retención de IVA Leche Fluida', 'NO ACTIVO'),
	('IY', 'RETENCIÓN IIBB BUENOS AIRES 70/2007', 'IB Bs As - Reg Gral'),
	('IZ', 'Retención de Ingresos Brutos - Región ge', 'NO ACTIVO'),
	('J1', 'RETENCIÓN IIBB SANTA FE (Base Neta)', 'NO ACTIVO'),
	('J2', 'RETENCIÓN IIBB SANTA FE 15/1997 (MP)', 'NO ACTIVO'),
	('J4', 'RETENCIÓN IIBB CHACO NI 1749/2013', 'NO ACTIVO'),
	('JI', 'RETENCIÓN IIBB SANTA FE 15/1997 - neto', 'IB Sta Fe - Rg Gral - Insc. Local'),
	('L1', 'RG 177 Pequeños Contrib. Ret IIBB CF', 'NO ACTIVO'),
	('LB', 'RETENCIÓN IIBB SAN LUIS 15/2000', 'NO ACTIVO'),
	('TU', 'Subsidio Investigación Prov. Tucuman', 'NO ACTIVO'),
	('TX', 'Retención DREI San Lorenzo', 'DREI - San Lorenzo'),
	('V1', 'RG 2549 Ret IVA Monotributistas', 'NO ACTIVO'),
	('V2', 'RETENCION IVA 3164/2011 RI', 'NO ACTIVO'),
	('V3', 'RETENCION IVA 3164/2011 RNI', 'NO ACTIVO'),
	('V4', 'RETENCIÓN  IVA  RG3594/2014', 'NO ACTIVO'),
	('V5', 'RETENCIÓN  IVA  2854/2010', 'NO ACTIVO'),
	('V6', 'RETENCIÓN  IVA  RG 4627 Op Suj a Ret', 'NO ACTIVO')
	
END
