import { DatePipe } from '@angular/common';
import { Component, OnInit, ViewChild } from '@angular/core';
import { ActivatedRoute, Params } from '@angular/router';
import { OrdenDeCargaFasonDto } from '../../common/models/ordenes-de-carga-fason/ordenDeCargaFasonDto';
import { FloatMsgService } from '../../common/services/FloatMsgService';
import { ModalService } from '../../common/services/ModalService';
import { NavService } from '../../common/services/NavService';
import { SecurityService } from '../../common/services/SecurityService';
import { SessionDataService } from '../../common/services/SessionDataService';
import { NgBlockUI, BlockUI } from 'ng-block-ui';
import { ConfirmationService } from 'primeng/api';
import { OrdenesDeCargaFasonService } from '../ordenes-de-carga-fason.service';
import { ListBaseComponent } from '../../common/base-components/list-base-component';
import { EstadoOrdenDeCargaFason } from '../../common/models/ordenes-de-carga-fason/estadoOrdenDeCargaFason';
import { Rol } from '../../common/enums/Roles';
import { Permiso } from '../../common/enums/Permisos';
import { finalize } from 'rxjs/operators';

export interface BotonesDetalleFason {
    editar: boolean;
    verificarTransporte: boolean;
    anular: boolean;
    verificarCuitsTercero: boolean;
}


@Component({
    selector: 'app-detalle',
    templateUrl: './ordenes-de-carga-fason.detalle.component.html',
    styleUrls: ['./ordenes-de-carga-fason.detalle.component.css', '../listado/ordenes-de-carga-fason.listado.component.css']
})
export class OrdenesDeCargaFasonDetalleComponent extends ListBaseComponent implements OnInit {

    @BlockUI() blockUI: NgBlockUI;

    ordenDeCargaFason: OrdenDeCargaFasonDto = new OrdenDeCargaFasonDto();
    ordenDeCargaFasonId: number = 0;

    botones: BotonesDetalleFason = {} as BotonesDetalleFason;
    mensajeError: string = "";

    corredores: Map<number, string>;
    corredorSeleccionado: number;

    esTercero: boolean = this.isAuthorized(Permiso.FasonVerOrdenesDeCarga);
    esAdmin: boolean = this.isAuthorized(Permiso.FasonVerOrdenesDeCargaAdmin);
    esClienteFason = !this.esAdmin && this.esTercero;
    esCorredor: boolean = sessionStorage.getItem("tipoUsuario") === Rol.Corredor;

    estadoOrdenDeCargaFason = EstadoOrdenDeCargaFason;

    validaCPEDG = false;
    validandoEstadoScato = false;

    activaEnScato = false;

    estadosPermitenEdicion = [
        EstadoOrdenDeCargaFason.Generada,
        EstadoOrdenDeCargaFason.PendienteContabilizacion,
        EstadoOrdenDeCargaFason.Pendiente,
        EstadoOrdenDeCargaFason.PendienteCompensacion,
        EstadoOrdenDeCargaFason.Vencida,
    ];

    constructor(private route: ActivatedRoute, protected service: OrdenesDeCargaFasonService, protected navService: NavService,
        protected sessionDataService: SessionDataService, protected securytiService: SecurityService,
        protected floatMsgService: FloatMsgService, protected modalService: ModalService,
        public datepipe: DatePipe,
        private confirmationService: ConfirmationService) {
        super(service, navService, sessionDataService, securytiService, floatMsgService, modalService);
    }

    ngOnInit() {
        this.route.params.forEach((params: Params) => {
            if (params["id"] > 0) this.ordenDeCargaFasonId = params["id"];
        });

        this.navService.setSeccionList([]);
        this.obtenerOrdenDeCargaFason();

        this.verificarOrdenActivaScato()
    }

    verificarBotones() {
        this.botones = {} as BotonesDetalleFason;

        this.botones.verificarTransporte = this.esAdmin && !this.ordenDeCargaFason.TransporteExiste;

        this.botones.editar = this.estadosPermitenEdicion.includes(this.ordenDeCargaFason.Estado);

        this.botones.anular = this.ordenDeCargaFason.Estado != EstadoOrdenDeCargaFason.Entregada && this.ordenDeCargaFason.Estado != EstadoOrdenDeCargaFason.Anulada;

        this.botones.aprobarRechazarAnulacion = this.esAdmin && this.ordenDeCargaFason.Estado == EstadoOrdenDeCargaFason.AnulacionSolicitada;

        this.botones.aprobarRechazarEdicion = this.esAdmin && this.ordenDeCargaFason.Estado == EstadoOrdenDeCargaFason.EdicionSolicitada;

        this.botones.solicitarAnulacion = this.esClienteFason && this.estadosPermitenSolicitarAnulacion.includes(this.ordenDeCargaFason.Estado)

        this.botones.anular = this.esAdmin && this.ordenDeCargaFason.Estado != EstadoOrdenDeCargaFason.Entregada && this.ordenDeCargaFason.Estado != EstadoOrdenDeCargaFason.Anulada;
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PRE

        this.botones.verificarCuitsTercero = this.esAdmin && this.ordenDeCargaFason.NecesitaVerificarCuitsTerceros;
    }


    obtenerOrdenDeCargaFason() {
        try {
            this.unsubscribe();
            this.subscriptionDropDowns = this.service.getOrdenDeCargaFason(this.ordenDeCargaFasonId).subscribe(
                result => {
                    if (result.logout == true) {
                        this.sessionDataService.logout();
                    } else if (result.error != undefined && result.error != "") {
                    } else if (result.info != undefined) {
                    } else {
                        this.ordenDeCargaFason = result.data.Response;
                        this.validaCPEDG = this.ordenDeCargaFason.ValidaSisaRuca;
                        this.verificarBotones();
                    }
                },
                error => {
                    this.blockUI.stop();
                    this.mensajeComponent.setErrorMsg(error.message);
                }
            );
        } catch (e) {
        }
    }


    editarOrden() {
        if (this.validandoEstadoScato) {
            return;
        }
        if (!this.activaEnScato) {
            this.goToSeccion('/ordenes-de-carga-fason/alta/' + this.ordenDeCargaFason.Id);
        } else {
            this.confirmationService.confirm({
                key: 'confirmarEdicionActiva',
                message: `La orden está activa en SCATO, ¿seguro que quiere continuar con la edición?`,
                accept: () => {
                    this.goToSeccion('/ordenes-de-carga-fason/alta/' + this.ordenDeCargaFason.Id);
                },
                reject: () => {
                }
            })
        }
    }

    verificarTransporte() {
        this.mensajeComponent.setMsgsEmpty();
        this.spinnerComponent.showIt();
        this.unsubscribe();
        this.blockUI.start('Procesando...');
        try {
            this.subscriptionDropDowns = this.service.verificarTransporte(this.ordenDeCargaFason.Id).subscribe(
                result => {
                    this.blockUI.stop();
                    this.spinnerComponent.hideIt();
                    if (result.logout == true) {
                        this.sessionDataService.logout();
                    } else if (result.error != undefined && result.error != "") {
                        this.mensajeComponent.setErrorMsg(result.error);
                    } else if (result.info != undefined) {
                        this.mensajeComponent.setInfoMsg(result.info);
                    } else if (result.data) {
                        this.ordenDeCargaFason = result.data;
                    } else {
                        this.obtenerOrdenDeCargaFason();
                    }
                    this.verificarBotones();

                },
                error => {
                    this.blockUI.stop();
                    this.mensajeComponent.setErrorMsg(error.message);
                }
            );
        } catch (e) {
            this.mensajeComponent.setErrorMsg(e);
        }
    }
    
    confirmarAnulacion() {
        this.confirmationService.confirm({
            key: 'confirmarAnular',
            message: '¿Desea anular la orden?',
            accept: () => {
                this.anularOrden()
            },
            reject: () => {
            }
        });
    }
    
    anularOrden() {
        this.mensajeComponent.setMsgsEmpty();
        this.spinnerComponent.showIt();
        this.unsubscribe();
        this.blockUI.start('Procesando...');
        try {
            this.service.anularOrden(this.ordenDeCargaFason.Id).subscribe(
                result => {
                    this.blockUI.stop();
                    this.spinnerComponent.hideIt();
                    if (result.logout == true) {
                        this.sessionDataService.logout();
                    } else if (result.error != undefined && result.error != "") {
                        this.mensajeComponent.setErrorMsg(result.error);
                    } else if (result.info != undefined) {
                        this.mensajeComponent.setInfoMsg(result.info);
                    } else if (result.data) {
                        this.ordenDeCargaFason = result.data;
                    } else {
                        this.obtenerOrdenDeCargaFason();
                    }
                    this.verificarBotones();
                },
                error => {
                    this.blockUI.stop();
                    this.mensajeComponent.setErrorMsg(error.message);
                }
            );
        } catch (e) {
            this.mensajeComponent.setErrorMsg(e);
        }
    }

    verificarCuitsTerceros() {
        this.mensajeComponent.setMsgsEmpty();
        this.spinnerComponent.showIt();
        this.unsubscribe();
        this.blockUI.start('Procesando...');
        try {
            this.subscriptionDropDowns = this.service.verificarCuitsTerceros(this.ordenDeCargaFasonId).subscribe(
                result => {
                    this.blockUI.stop();
                    this.spinnerComponent.hideIt();
                    if (result.logout == true) {
                        this.sessionDataService.logout();
                    } else if (result.error != undefined && result.error != "") {
                        this.mensajeComponent.setErrorMsg(result.error);
                    } else if (result.info != undefined) {
                        this.mensajeComponent.setInfoMsg(result.info);
                    } else {
                        this.mensajeComponent.setMsgsEmpty();
                        this.obtenerOrdenDeCargaFason();
                    }
                },
                error => {
                    this.blockUI.stop();
                    this.mensajeComponent.setErrorMsg(error.message);
                }
            );
        } catch (e) {
            this.mensajeComponent.setErrorMsg(e);
        }
    }

    verificarOrdenActivaScato() {
        this.validandoEstadoScato = true;
        this.spinnerComponent.showIt();
        try {
            this.service.validarOrdenActivaScato(this.ordenDeCargaFasonId).pipe(
                finalize(() => { this.blockUI.stop(); this.spinnerComponent.hideIt(); this.validandoEstadoScato = false; })
            ).subscribe(
                result => {
                    const estadoEnScato = this.manejarApiResponse(result, this.sessionDataService, this.mensajeComponent)
                    this.activaEnScato = !!estadoEnScato
                },
                error => {
                    this.mensajeComponent.setErrorMsg(error.message);
                }
            );
        } catch (e) {
            this.spinnerComponent.hideIt();
            this.blockUI.stop();
        }
    }
}
