//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SustitucionMOAWS.ObtenerUnidadesDeMedidaAlternativasWebServiceMOA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:OPERACIONES", ConfigurationName="ObtenerUnidadesDeMedidaAlternativasWebServiceMOA.SI_MMRFC_UM_ALTERNATIVAS")]
    public interface SI_MMRFC_UM_ALTERNATIVAS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SustitucionMOAWS.ObtenerUnidadesDeMedidaAlternativasWebServiceMOA.SI_MMRFC_UM_ALTERNATIVASResponse SI_MMRFC_UM_ALTERNATIVAS(SustitucionMOAWS.ObtenerUnidadesDeMedidaAlternativasWebServiceMOA.SI_MMRFC_UM_ALTERNATIVASRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SustitucionMOAWS.ObtenerUnidadesDeMedidaAlternativasWebServiceMOA.SI_MMRFC_UM_ALTERNATIVASResponse> SI_MMRFC_UM_ALTERNATIVASAsync(SustitucionMOAWS.ObtenerUnidadesDeMedidaAlternativasWebServiceMOA.SI_MMRFC_UM_ALTERNATIVASRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class WSELMATNR : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sIGNField;
        
        private string oPTIONField;
        
        private string lOWField;
        
        private string hIGHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SIGN {
            get {
                return this.sIGNField;
            }
            set {
                this.sIGNField = value;
                this.RaisePropertyChanged("SIGN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string OPTION {
            get {
                return this.oPTIONField;
            }
            set {
                this.oPTIONField = value;
                this.RaisePropertyChanged("OPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string LOW {
            get {
                return this.lOWField;
            }
            set {
                this.lOWField = value;
                this.RaisePropertyChanged("LOW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string HIGH {
            get {
                return this.hIGHField;
            }
            set {
                this.hIGHField = value;
                this.RaisePropertyChanged("HIGH");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMMTT_UM_ALT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mANDTField;
        
        private string mATERIALField;
        
        private string umField;
        
        private decimal nUMERADORField;
        
        private bool nUMERADORFieldSpecified;
        
        private decimal dENOMINADORField;
        
        private bool dENOMINADORFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MANDT {
            get {
                return this.mANDTField;
            }
            set {
                this.mANDTField = value;
                this.RaisePropertyChanged("MANDT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MATERIAL {
            get {
                return this.mATERIALField;
            }
            set {
                this.mATERIALField = value;
                this.RaisePropertyChanged("MATERIAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string UM {
            get {
                return this.umField;
            }
            set {
                this.umField = value;
                this.RaisePropertyChanged("UM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal NUMERADOR {
            get {
                return this.nUMERADORField;
            }
            set {
                this.nUMERADORField = value;
                this.RaisePropertyChanged("NUMERADOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NUMERADORSpecified {
            get {
                return this.nUMERADORFieldSpecified;
            }
            set {
                this.nUMERADORFieldSpecified = value;
                this.RaisePropertyChanged("NUMERADORSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal DENOMINADOR {
            get {
                return this.dENOMINADORField;
            }
            set {
                this.dENOMINADORField = value;
                this.RaisePropertyChanged("DENOMINADOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DENOMINADORSpecified {
            get {
                return this.dENOMINADORFieldSpecified;
            }
            set {
                this.dENOMINADORFieldSpecified = value;
                this.RaisePropertyChanged("DENOMINADORSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MMRFC_UM_ALTERNATIVAS", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MMRFC_UM_ALTERNATIVASRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.ObtenerUnidadesDeMedidaAlternativasWebServiceMOA.WSELMATNR[] IM_MATERIAL;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.ObtenerUnidadesDeMedidaAlternativasWebServiceMOA.ZMMTT_UM_ALT[] EX_UM_ALT;
        
        public SI_MMRFC_UM_ALTERNATIVASRequest() {
        }
        
        public SI_MMRFC_UM_ALTERNATIVASRequest(SustitucionMOAWS.ObtenerUnidadesDeMedidaAlternativasWebServiceMOA.WSELMATNR[] IM_MATERIAL, SustitucionMOAWS.ObtenerUnidadesDeMedidaAlternativasWebServiceMOA.ZMMTT_UM_ALT[] EX_UM_ALT) {
            this.IM_MATERIAL = IM_MATERIAL;
            this.EX_UM_ALT = EX_UM_ALT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MMRFC_UM_ALTERNATIVAS.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MMRFC_UM_ALTERNATIVASResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public byte EX_EXITO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.ObtenerUnidadesDeMedidaAlternativasWebServiceMOA.ZMMTT_UM_ALT[] EX_UM_ALT;
        
        public SI_MMRFC_UM_ALTERNATIVASResponse() {
        }
        
        public SI_MMRFC_UM_ALTERNATIVASResponse(byte EX_EXITO, SustitucionMOAWS.ObtenerUnidadesDeMedidaAlternativasWebServiceMOA.ZMMTT_UM_ALT[] EX_UM_ALT) {
            this.EX_EXITO = EX_EXITO;
            this.EX_UM_ALT = EX_UM_ALT;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_MMRFC_UM_ALTERNATIVASChannel : SustitucionMOAWS.ObtenerUnidadesDeMedidaAlternativasWebServiceMOA.SI_MMRFC_UM_ALTERNATIVAS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_MMRFC_UM_ALTERNATIVASClient : System.ServiceModel.ClientBase<SustitucionMOAWS.ObtenerUnidadesDeMedidaAlternativasWebServiceMOA.SI_MMRFC_UM_ALTERNATIVAS>, SustitucionMOAWS.ObtenerUnidadesDeMedidaAlternativasWebServiceMOA.SI_MMRFC_UM_ALTERNATIVAS {
        
        public SI_MMRFC_UM_ALTERNATIVASClient() {
        }
        
        public SI_MMRFC_UM_ALTERNATIVASClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_MMRFC_UM_ALTERNATIVASClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MMRFC_UM_ALTERNATIVASClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MMRFC_UM_ALTERNATIVASClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SustitucionMOAWS.ObtenerUnidadesDeMedidaAlternativasWebServiceMOA.SI_MMRFC_UM_ALTERNATIVASResponse SustitucionMOAWS.ObtenerUnidadesDeMedidaAlternativasWebServiceMOA.SI_MMRFC_UM_ALTERNATIVAS.SI_MMRFC_UM_ALTERNATIVAS(SustitucionMOAWS.ObtenerUnidadesDeMedidaAlternativasWebServiceMOA.SI_MMRFC_UM_ALTERNATIVASRequest request) {
            return base.Channel.SI_MMRFC_UM_ALTERNATIVAS(request);
        }
        
        public byte SI_MMRFC_UM_ALTERNATIVAS(SustitucionMOAWS.ObtenerUnidadesDeMedidaAlternativasWebServiceMOA.WSELMATNR[] IM_MATERIAL, ref SustitucionMOAWS.ObtenerUnidadesDeMedidaAlternativasWebServiceMOA.ZMMTT_UM_ALT[] EX_UM_ALT) {
            SustitucionMOAWS.ObtenerUnidadesDeMedidaAlternativasWebServiceMOA.SI_MMRFC_UM_ALTERNATIVASRequest inValue = new SustitucionMOAWS.ObtenerUnidadesDeMedidaAlternativasWebServiceMOA.SI_MMRFC_UM_ALTERNATIVASRequest();
            inValue.IM_MATERIAL = IM_MATERIAL;
            inValue.EX_UM_ALT = EX_UM_ALT;
            SustitucionMOAWS.ObtenerUnidadesDeMedidaAlternativasWebServiceMOA.SI_MMRFC_UM_ALTERNATIVASResponse retVal = ((SustitucionMOAWS.ObtenerUnidadesDeMedidaAlternativasWebServiceMOA.SI_MMRFC_UM_ALTERNATIVAS)(this)).SI_MMRFC_UM_ALTERNATIVAS(inValue);
            EX_UM_ALT = retVal.EX_UM_ALT;
            return retVal.EX_EXITO;
        }
        
        public System.Threading.Tasks.Task<SustitucionMOAWS.ObtenerUnidadesDeMedidaAlternativasWebServiceMOA.SI_MMRFC_UM_ALTERNATIVASResponse> SI_MMRFC_UM_ALTERNATIVASAsync(SustitucionMOAWS.ObtenerUnidadesDeMedidaAlternativasWebServiceMOA.SI_MMRFC_UM_ALTERNATIVASRequest request) {
            return base.Channel.SI_MMRFC_UM_ALTERNATIVASAsync(request);
        }
    }
}
