//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:OPERACIONES", ConfigurationName="EcheqVisualizarPendientePagoWebServiceMOA.SI_MPRFC_VISU_PENDIENTE_PAGO")]
    public interface SI_MPRFC_VISU_PENDIENTE_PAGO {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:sap-com:document:sap:rfc:functions) of message SI_MPRFC_VISU_PENDIENTE_PAGORequest does not match the default value (urn:OPERACIONES)
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA.SI_MPRFC_VISU_PENDIENTE_PAGOResponse SI_MPRFC_VISU_PENDIENTE_PAGO(SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA.SI_MPRFC_VISU_PENDIENTE_PAGORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA.SI_MPRFC_VISU_PENDIENTE_PAGOResponse> SI_MPRFC_VISU_PENDIENTE_PAGOAsync(SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA.SI_MPRFC_VISU_PENDIENTE_PAGORequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES4100 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fECHA_OPField;
        
        private string fECHA_OP_HASTAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FECHA_OP {
            get {
                return this.fECHA_OPField;
            }
            set {
                this.fECHA_OPField = value;
                this.RaisePropertyChanged("FECHA_OP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string FECHA_OP_HASTA {
            get {
                return this.fECHA_OP_HASTAField;
            }
            set {
                this.fECHA_OP_HASTAField = value;
                this.RaisePropertyChanged("FECHA_OP_HASTA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES6890 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cONTRATOField;
        
        private string pEDIDOField;
        
        private string sOCIEDADField;
        
        private string dOCUMENTOField;
        
        private string eJERCICIOField;
        
        private string fECHAField;
        
        private string xBLNRField;
        
        private string sOLAPAField;
        
        private decimal wRBTRField;
        
        private bool wRBTRFieldSpecified;
        
        private decimal dMBTRField;
        
        private bool dMBTRFieldSpecified;
        
        private string mONEDAField;
        
        private string cLASIFICACIONField;
        
        private string zLSCHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CONTRATO {
            get {
                return this.cONTRATOField;
            }
            set {
                this.cONTRATOField = value;
                this.RaisePropertyChanged("CONTRATO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PEDIDO {
            get {
                return this.pEDIDOField;
            }
            set {
                this.pEDIDOField = value;
                this.RaisePropertyChanged("PEDIDO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string SOCIEDAD {
            get {
                return this.sOCIEDADField;
            }
            set {
                this.sOCIEDADField = value;
                this.RaisePropertyChanged("SOCIEDAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DOCUMENTO {
            get {
                return this.dOCUMENTOField;
            }
            set {
                this.dOCUMENTOField = value;
                this.RaisePropertyChanged("DOCUMENTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string EJERCICIO {
            get {
                return this.eJERCICIOField;
            }
            set {
                this.eJERCICIOField = value;
                this.RaisePropertyChanged("EJERCICIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string FECHA {
            get {
                return this.fECHAField;
            }
            set {
                this.fECHAField = value;
                this.RaisePropertyChanged("FECHA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string XBLNR {
            get {
                return this.xBLNRField;
            }
            set {
                this.xBLNRField = value;
                this.RaisePropertyChanged("XBLNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string SOLAPA {
            get {
                return this.sOLAPAField;
            }
            set {
                this.sOLAPAField = value;
                this.RaisePropertyChanged("SOLAPA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal WRBTR {
            get {
                return this.wRBTRField;
            }
            set {
                this.wRBTRField = value;
                this.RaisePropertyChanged("WRBTR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WRBTRSpecified {
            get {
                return this.wRBTRFieldSpecified;
            }
            set {
                this.wRBTRFieldSpecified = value;
                this.RaisePropertyChanged("WRBTRSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal DMBTR {
            get {
                return this.dMBTRField;
            }
            set {
                this.dMBTRField = value;
                this.RaisePropertyChanged("DMBTR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DMBTRSpecified {
            get {
                return this.dMBTRFieldSpecified;
            }
            set {
                this.dMBTRFieldSpecified = value;
                this.RaisePropertyChanged("DMBTRSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string MONEDA {
            get {
                return this.mONEDAField;
            }
            set {
                this.mONEDAField = value;
                this.RaisePropertyChanged("MONEDA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string CLASIFICACION {
            get {
                return this.cLASIFICACIONField;
            }
            set {
                this.cLASIFICACIONField = value;
                this.RaisePropertyChanged("CLASIFICACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string ZLSCH {
            get {
                return this.zLSCHField;
            }
            set {
                this.zLSCHField = value;
                this.RaisePropertyChanged("ZLSCH");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES6900 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cONTRATOField;
        
        private string pEDIDOField;
        
        private decimal kILOSField;
        
        private bool kILOSFieldSpecified;
        
        private decimal kILOS_PAGADOSField;
        
        private bool kILOS_PAGADOSFieldSpecified;
        
        private decimal pRECIOField;
        
        private bool pRECIOFieldSpecified;
        
        private string mONEDAField;
        
        private string mATERIALField;
        
        private string dESC_MATERIALField;
        
        private string fECHAField;
        
        private string zLSCHField;
        
        private ZMPES6890[] dOCUMENTOSField;
        
        private string cLASIFICACIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CONTRATO {
            get {
                return this.cONTRATOField;
            }
            set {
                this.cONTRATOField = value;
                this.RaisePropertyChanged("CONTRATO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PEDIDO {
            get {
                return this.pEDIDOField;
            }
            set {
                this.pEDIDOField = value;
                this.RaisePropertyChanged("PEDIDO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal KILOS {
            get {
                return this.kILOSField;
            }
            set {
                this.kILOSField = value;
                this.RaisePropertyChanged("KILOS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KILOSSpecified {
            get {
                return this.kILOSFieldSpecified;
            }
            set {
                this.kILOSFieldSpecified = value;
                this.RaisePropertyChanged("KILOSSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal KILOS_PAGADOS {
            get {
                return this.kILOS_PAGADOSField;
            }
            set {
                this.kILOS_PAGADOSField = value;
                this.RaisePropertyChanged("KILOS_PAGADOS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KILOS_PAGADOSSpecified {
            get {
                return this.kILOS_PAGADOSFieldSpecified;
            }
            set {
                this.kILOS_PAGADOSFieldSpecified = value;
                this.RaisePropertyChanged("KILOS_PAGADOSSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal PRECIO {
            get {
                return this.pRECIOField;
            }
            set {
                this.pRECIOField = value;
                this.RaisePropertyChanged("PRECIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PRECIOSpecified {
            get {
                return this.pRECIOFieldSpecified;
            }
            set {
                this.pRECIOFieldSpecified = value;
                this.RaisePropertyChanged("PRECIOSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string MONEDA {
            get {
                return this.mONEDAField;
            }
            set {
                this.mONEDAField = value;
                this.RaisePropertyChanged("MONEDA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MATERIAL {
            get {
                return this.mATERIALField;
            }
            set {
                this.mATERIALField = value;
                this.RaisePropertyChanged("MATERIAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string DESC_MATERIAL {
            get {
                return this.dESC_MATERIALField;
            }
            set {
                this.dESC_MATERIALField = value;
                this.RaisePropertyChanged("DESC_MATERIAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string FECHA {
            get {
                return this.fECHAField;
            }
            set {
                this.fECHAField = value;
                this.RaisePropertyChanged("FECHA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ZLSCH {
            get {
                return this.zLSCHField;
            }
            set {
                this.zLSCHField = value;
                this.RaisePropertyChanged("ZLSCH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMPES6890[] DOCUMENTOS {
            get {
                return this.dOCUMENTOSField;
            }
            set {
                this.dOCUMENTOSField = value;
                this.RaisePropertyChanged("DOCUMENTOS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string CLASIFICACION {
            get {
                return this.cLASIFICACIONField;
            }
            set {
                this.cLASIFICACIONField = value;
                this.RaisePropertyChanged("CLASIFICACION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MPRFC_VISU_PENDIENTE_PAGO", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MPRFC_VISU_PENDIENTE_PAGORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_CONTRATO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA.ZMPES4100[] IM_FECHA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_PROVEEDOR;
        
        public SI_MPRFC_VISU_PENDIENTE_PAGORequest() {
        }
        
        public SI_MPRFC_VISU_PENDIENTE_PAGORequest(string IM_CONTRATO, SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA.ZMPES4100[] IM_FECHA, string IM_PROVEEDOR) {
            this.IM_CONTRATO = IM_CONTRATO;
            this.IM_FECHA = IM_FECHA;
            this.IM_PROVEEDOR = IM_PROVEEDOR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MPRFC_VISU_PENDIENTE_PAGO.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MPRFC_VISU_PENDIENTE_PAGOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA.ZMPES6900[] EX_SALIDA;
        
        public SI_MPRFC_VISU_PENDIENTE_PAGOResponse() {
        }
        
        public SI_MPRFC_VISU_PENDIENTE_PAGOResponse(SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA.ZMPES6900[] EX_SALIDA) {
            this.EX_SALIDA = EX_SALIDA;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_MPRFC_VISU_PENDIENTE_PAGOChannel : SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA.SI_MPRFC_VISU_PENDIENTE_PAGO, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_MPRFC_VISU_PENDIENTE_PAGOClient : System.ServiceModel.ClientBase<SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA.SI_MPRFC_VISU_PENDIENTE_PAGO>, SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA.SI_MPRFC_VISU_PENDIENTE_PAGO {
        
        public SI_MPRFC_VISU_PENDIENTE_PAGOClient() {
        }
        
        public SI_MPRFC_VISU_PENDIENTE_PAGOClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_MPRFC_VISU_PENDIENTE_PAGOClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MPRFC_VISU_PENDIENTE_PAGOClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MPRFC_VISU_PENDIENTE_PAGOClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA.SI_MPRFC_VISU_PENDIENTE_PAGOResponse SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA.SI_MPRFC_VISU_PENDIENTE_PAGO.SI_MPRFC_VISU_PENDIENTE_PAGO(SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA.SI_MPRFC_VISU_PENDIENTE_PAGORequest request) {
            return base.Channel.SI_MPRFC_VISU_PENDIENTE_PAGO(request);
        }
        
        public SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA.ZMPES6900[] SI_MPRFC_VISU_PENDIENTE_PAGO(string IM_CONTRATO, SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA.ZMPES4100[] IM_FECHA, string IM_PROVEEDOR) {
            SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA.SI_MPRFC_VISU_PENDIENTE_PAGORequest inValue = new SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA.SI_MPRFC_VISU_PENDIENTE_PAGORequest();
            inValue.IM_CONTRATO = IM_CONTRATO;
            inValue.IM_FECHA = IM_FECHA;
            inValue.IM_PROVEEDOR = IM_PROVEEDOR;
            SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA.SI_MPRFC_VISU_PENDIENTE_PAGOResponse retVal = ((SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA.SI_MPRFC_VISU_PENDIENTE_PAGO)(this)).SI_MPRFC_VISU_PENDIENTE_PAGO(inValue);
            return retVal.EX_SALIDA;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA.SI_MPRFC_VISU_PENDIENTE_PAGOResponse> SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA.SI_MPRFC_VISU_PENDIENTE_PAGO.SI_MPRFC_VISU_PENDIENTE_PAGOAsync(SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA.SI_MPRFC_VISU_PENDIENTE_PAGORequest request) {
            return base.Channel.SI_MPRFC_VISU_PENDIENTE_PAGOAsync(request);
        }
        
        public System.Threading.Tasks.Task<SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA.SI_MPRFC_VISU_PENDIENTE_PAGOResponse> SI_MPRFC_VISU_PENDIENTE_PAGOAsync(string IM_CONTRATO, SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA.ZMPES4100[] IM_FECHA, string IM_PROVEEDOR) {
            SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA.SI_MPRFC_VISU_PENDIENTE_PAGORequest inValue = new SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA.SI_MPRFC_VISU_PENDIENTE_PAGORequest();
            inValue.IM_CONTRATO = IM_CONTRATO;
            inValue.IM_FECHA = IM_FECHA;
            inValue.IM_PROVEEDOR = IM_PROVEEDOR;
            return ((SustitucionMOAWS.EcheqVisualizarPendientePagoWebServiceMOA.SI_MPRFC_VISU_PENDIENTE_PAGO)(this)).SI_MPRFC_VISU_PENDIENTE_PAGOAsync(inValue);
        }
    }
}
