//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="WS_GAQ_sin_PI_DIRECT_PANOL.Z_WS_PANOL_DIRECT")]
    public interface Z_WS_PANOL_DIRECT {
        
        // CODEGEN: Generating message contract since the operation Z_MMRFC_LISTADO_MAT_PAN is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:Z_WS_PANOL_DIRECT:Z_MMRFC_LISTADO_MAT_PANR" +
            "equest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_LISTADO_MAT_PANResponse1 Z_MMRFC_LISTADO_MAT_PAN(SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_LISTADO_MAT_PANRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:Z_WS_PANOL_DIRECT:Z_MMRFC_LISTADO_MAT_PANR" +
            "equest", ReplyAction="*")]
        System.Threading.Tasks.Task<SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_LISTADO_MAT_PANResponse1> Z_MMRFC_LISTADO_MAT_PANAsync(SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_LISTADO_MAT_PANRequest request);
        
        // CODEGEN: Generating message contract since the operation Z_MMRFC_OBT_INSUMO_PAN is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:Z_WS_PANOL_DIRECT:Z_MMRFC_OBT_INSUMO_PANRe" +
            "quest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_OBT_INSUMO_PANResponse1 Z_MMRFC_OBT_INSUMO_PAN(SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_OBT_INSUMO_PANRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:Z_WS_PANOL_DIRECT:Z_MMRFC_OBT_INSUMO_PANRe" +
            "quest", ReplyAction="*")]
        System.Threading.Tasks.Task<SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_OBT_INSUMO_PANResponse1> Z_MMRFC_OBT_INSUMO_PANAsync(SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_OBT_INSUMO_PANRequest request);
        
        // CODEGEN: Generating message contract since the operation Z_MMRFC_GEN_MOVSTK_PAN is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:Z_WS_PANOL_DIRECT:Z_MMRFC_GEN_MOVSTK_PANRe" +
            "quest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_GEN_MOVSTK_PANResponse1 Z_MMRFC_GEN_MOVSTK_PAN(SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_GEN_MOVSTK_PANRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:Z_WS_PANOL_DIRECT:Z_MMRFC_GEN_MOVSTK_PANRe" +
            "quest", ReplyAction="*")]
        System.Threading.Tasks.Task<SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_GEN_MOVSTK_PANResponse1> Z_MMRFC_GEN_MOVSTK_PANAsync(SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_GEN_MOVSTK_PANRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MMRFC_LISTADO_MAT_PAN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iM_ALMACENField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IM_ALMACEN {
            get {
                return this.iM_ALMACENField;
            }
            set {
                this.iM_ALMACENField = value;
                this.RaisePropertyChanged("IM_ALMACEN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPIRET2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        private string lOG_NOField;
        
        private string lOG_MSG_NOField;
        
        private string mESSAGE_V1Field;
        
        private string mESSAGE_V2Field;
        
        private string mESSAGE_V3Field;
        
        private string mESSAGE_V4Field;
        
        private string pARAMETERField;
        
        private int rOWField;
        
        private string fIELDField;
        
        private string sYSTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NUMBER {
            get {
                return this.nUMBERField;
            }
            set {
                this.nUMBERField = value;
                this.RaisePropertyChanged("NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LOG_NO {
            get {
                return this.lOG_NOField;
            }
            set {
                this.lOG_NOField = value;
                this.RaisePropertyChanged("LOG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LOG_MSG_NO {
            get {
                return this.lOG_MSG_NOField;
            }
            set {
                this.lOG_MSG_NOField = value;
                this.RaisePropertyChanged("LOG_MSG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MESSAGE_V1 {
            get {
                return this.mESSAGE_V1Field;
            }
            set {
                this.mESSAGE_V1Field = value;
                this.RaisePropertyChanged("MESSAGE_V1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MESSAGE_V2 {
            get {
                return this.mESSAGE_V2Field;
            }
            set {
                this.mESSAGE_V2Field = value;
                this.RaisePropertyChanged("MESSAGE_V2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MESSAGE_V3 {
            get {
                return this.mESSAGE_V3Field;
            }
            set {
                this.mESSAGE_V3Field = value;
                this.RaisePropertyChanged("MESSAGE_V3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MESSAGE_V4 {
            get {
                return this.mESSAGE_V4Field;
            }
            set {
                this.mESSAGE_V4Field = value;
                this.RaisePropertyChanged("MESSAGE_V4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PARAMETER {
            get {
                return this.pARAMETERField;
            }
            set {
                this.pARAMETERField = value;
                this.RaisePropertyChanged("PARAMETER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int ROW {
            get {
                return this.rOWField;
            }
            set {
                this.rOWField = value;
                this.RaisePropertyChanged("ROW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string FIELD {
            get {
                return this.fIELDField;
            }
            set {
                this.fIELDField = value;
                this.RaisePropertyChanged("FIELD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string SYSTEM {
            get {
                return this.sYSTEMField;
            }
            set {
                this.sYSTEMField = value;
                this.RaisePropertyChanged("SYSTEM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPI2017_GM_HEAD_RET : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mAT_DOCField;
        
        private string dOC_YEARField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MAT_DOC {
            get {
                return this.mAT_DOCField;
            }
            set {
                this.mAT_DOCField = value;
                this.RaisePropertyChanged("MAT_DOC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DOC_YEAR {
            get {
                return this.dOC_YEARField;
            }
            set {
                this.dOC_YEARField = value;
                this.RaisePropertyChanged("DOC_YEAR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES5960 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mATERIALField;
        
        private string cLASE_VALField;
        
        private string aLMACENField;
        
        private string cLSMOVField;
        
        private decimal cANTIDADField;
        
        private string cECOField;
        
        private string oRDENField;
        
        private string uSUARIOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MATERIAL {
            get {
                return this.mATERIALField;
            }
            set {
                this.mATERIALField = value;
                this.RaisePropertyChanged("MATERIAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CLASE_VAL {
            get {
                return this.cLASE_VALField;
            }
            set {
                this.cLASE_VALField = value;
                this.RaisePropertyChanged("CLASE_VAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ALMACEN {
            get {
                return this.aLMACENField;
            }
            set {
                this.aLMACENField = value;
                this.RaisePropertyChanged("ALMACEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CLSMOV {
            get {
                return this.cLSMOVField;
            }
            set {
                this.cLSMOVField = value;
                this.RaisePropertyChanged("CLSMOV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal CANTIDAD {
            get {
                return this.cANTIDADField;
            }
            set {
                this.cANTIDADField = value;
                this.RaisePropertyChanged("CANTIDAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string CECO {
            get {
                return this.cECOField;
            }
            set {
                this.cECOField = value;
                this.RaisePropertyChanged("CECO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ORDEN {
            get {
                return this.oRDENField;
            }
            set {
                this.oRDENField = value;
                this.RaisePropertyChanged("ORDEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string USUARIO {
            get {
                return this.uSUARIOField;
            }
            set {
                this.uSUARIOField = value;
                this.RaisePropertyChanged("USUARIO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES5950 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mATERIALField;
        
        private string mATL_DESCField;
        
        private string aLMACENField;
        
        private string vAL_TYPEField;
        
        private decimal sTOCK_LUField;
        
        private string uBICACIONField;
        
        private string uNIDAD_MEDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MATERIAL {
            get {
                return this.mATERIALField;
            }
            set {
                this.mATERIALField = value;
                this.RaisePropertyChanged("MATERIAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MATL_DESC {
            get {
                return this.mATL_DESCField;
            }
            set {
                this.mATL_DESCField = value;
                this.RaisePropertyChanged("MATL_DESC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ALMACEN {
            get {
                return this.aLMACENField;
            }
            set {
                this.aLMACENField = value;
                this.RaisePropertyChanged("ALMACEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string VAL_TYPE {
            get {
                return this.vAL_TYPEField;
            }
            set {
                this.vAL_TYPEField = value;
                this.RaisePropertyChanged("VAL_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal STOCK_LU {
            get {
                return this.sTOCK_LUField;
            }
            set {
                this.sTOCK_LUField = value;
                this.RaisePropertyChanged("STOCK_LU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string UBICACION {
            get {
                return this.uBICACIONField;
            }
            set {
                this.uBICACIONField = value;
                this.RaisePropertyChanged("UBICACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string UNIDAD_MED {
            get {
                return this.uNIDAD_MEDField;
            }
            set {
                this.uNIDAD_MEDField = value;
                this.RaisePropertyChanged("UNIDAD_MED");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPIRETURN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string cODEField;
        
        private string mESSAGEField;
        
        private string lOG_NOField;
        
        private string lOG_MSG_NOField;
        
        private string mESSAGE_V1Field;
        
        private string mESSAGE_V2Field;
        
        private string mESSAGE_V3Field;
        
        private string mESSAGE_V4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CODE {
            get {
                return this.cODEField;
            }
            set {
                this.cODEField = value;
                this.RaisePropertyChanged("CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string LOG_NO {
            get {
                return this.lOG_NOField;
            }
            set {
                this.lOG_NOField = value;
                this.RaisePropertyChanged("LOG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LOG_MSG_NO {
            get {
                return this.lOG_MSG_NOField;
            }
            set {
                this.lOG_MSG_NOField = value;
                this.RaisePropertyChanged("LOG_MSG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string MESSAGE_V1 {
            get {
                return this.mESSAGE_V1Field;
            }
            set {
                this.mESSAGE_V1Field = value;
                this.RaisePropertyChanged("MESSAGE_V1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MESSAGE_V2 {
            get {
                return this.mESSAGE_V2Field;
            }
            set {
                this.mESSAGE_V2Field = value;
                this.RaisePropertyChanged("MESSAGE_V2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MESSAGE_V3 {
            get {
                return this.mESSAGE_V3Field;
            }
            set {
                this.mESSAGE_V3Field = value;
                this.RaisePropertyChanged("MESSAGE_V3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MESSAGE_V4 {
            get {
                return this.mESSAGE_V4Field;
            }
            set {
                this.mESSAGE_V4Field = value;
                this.RaisePropertyChanged("MESSAGE_V4");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES6910 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mATERIALField;
        
        private string mATL_DESCField;
        
        private string aLMACENField;
        
        private string vAL_TYPEField;
        
        private decimal sTOCK_LUField;
        
        private string uBICACIONField;
        
        private string uNIDAD_MEDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MATERIAL {
            get {
                return this.mATERIALField;
            }
            set {
                this.mATERIALField = value;
                this.RaisePropertyChanged("MATERIAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MATL_DESC {
            get {
                return this.mATL_DESCField;
            }
            set {
                this.mATL_DESCField = value;
                this.RaisePropertyChanged("MATL_DESC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ALMACEN {
            get {
                return this.aLMACENField;
            }
            set {
                this.aLMACENField = value;
                this.RaisePropertyChanged("ALMACEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string VAL_TYPE {
            get {
                return this.vAL_TYPEField;
            }
            set {
                this.vAL_TYPEField = value;
                this.RaisePropertyChanged("VAL_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal STOCK_LU {
            get {
                return this.sTOCK_LUField;
            }
            set {
                this.sTOCK_LUField = value;
                this.RaisePropertyChanged("STOCK_LU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string UBICACION {
            get {
                return this.uBICACIONField;
            }
            set {
                this.uBICACIONField = value;
                this.RaisePropertyChanged("UBICACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string UNIDAD_MED {
            get {
                return this.uNIDAD_MEDField;
            }
            set {
                this.uNIDAD_MEDField = value;
                this.RaisePropertyChanged("UNIDAD_MED");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MMRFC_LISTADO_MAT_PANResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eX_EXITOField;
        
        private ZMPES6910[] eX_MATERIALESField;
        
        private BAPIRETURN eX_RETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EX_EXITO {
            get {
                return this.eX_EXITOField;
            }
            set {
                this.eX_EXITOField = value;
                this.RaisePropertyChanged("EX_EXITO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMPES6910[] EX_MATERIALES {
            get {
                return this.eX_MATERIALESField;
            }
            set {
                this.eX_MATERIALESField = value;
                this.RaisePropertyChanged("EX_MATERIALES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public BAPIRETURN EX_RETURN {
            get {
                return this.eX_RETURNField;
            }
            set {
                this.eX_RETURNField = value;
                this.RaisePropertyChanged("EX_RETURN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_MMRFC_LISTADO_MAT_PANRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_LISTADO_MAT_PAN Z_MMRFC_LISTADO_MAT_PAN;
        
        public Z_MMRFC_LISTADO_MAT_PANRequest() {
        }
        
        public Z_MMRFC_LISTADO_MAT_PANRequest(SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_LISTADO_MAT_PAN Z_MMRFC_LISTADO_MAT_PAN) {
            this.Z_MMRFC_LISTADO_MAT_PAN = Z_MMRFC_LISTADO_MAT_PAN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_MMRFC_LISTADO_MAT_PANResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_LISTADO_MAT_PANResponse Z_MMRFC_LISTADO_MAT_PANResponse;
        
        public Z_MMRFC_LISTADO_MAT_PANResponse1() {
        }
        
        public Z_MMRFC_LISTADO_MAT_PANResponse1(SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_LISTADO_MAT_PANResponse Z_MMRFC_LISTADO_MAT_PANResponse) {
            this.Z_MMRFC_LISTADO_MAT_PANResponse = Z_MMRFC_LISTADO_MAT_PANResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MMRFC_OBT_INSUMO_PAN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iM_ALMACENField;
        
        private string iM_CLASE_VALField;
        
        private string iM_MATERIALField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IM_ALMACEN {
            get {
                return this.iM_ALMACENField;
            }
            set {
                this.iM_ALMACENField = value;
                this.RaisePropertyChanged("IM_ALMACEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IM_CLASE_VAL {
            get {
                return this.iM_CLASE_VALField;
            }
            set {
                this.iM_CLASE_VALField = value;
                this.RaisePropertyChanged("IM_CLASE_VAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IM_MATERIAL {
            get {
                return this.iM_MATERIALField;
            }
            set {
                this.iM_MATERIALField = value;
                this.RaisePropertyChanged("IM_MATERIAL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MMRFC_OBT_INSUMO_PANResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eX_EXITOField;
        
        private ZMPES5950 eX_INSUMOField;
        
        private BAPIRETURN eX_RETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EX_EXITO {
            get {
                return this.eX_EXITOField;
            }
            set {
                this.eX_EXITOField = value;
                this.RaisePropertyChanged("EX_EXITO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ZMPES5950 EX_INSUMO {
            get {
                return this.eX_INSUMOField;
            }
            set {
                this.eX_INSUMOField = value;
                this.RaisePropertyChanged("EX_INSUMO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public BAPIRETURN EX_RETURN {
            get {
                return this.eX_RETURNField;
            }
            set {
                this.eX_RETURNField = value;
                this.RaisePropertyChanged("EX_RETURN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_MMRFC_OBT_INSUMO_PANRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_OBT_INSUMO_PAN Z_MMRFC_OBT_INSUMO_PAN;
        
        public Z_MMRFC_OBT_INSUMO_PANRequest() {
        }
        
        public Z_MMRFC_OBT_INSUMO_PANRequest(SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_OBT_INSUMO_PAN Z_MMRFC_OBT_INSUMO_PAN) {
            this.Z_MMRFC_OBT_INSUMO_PAN = Z_MMRFC_OBT_INSUMO_PAN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_MMRFC_OBT_INSUMO_PANResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_OBT_INSUMO_PANResponse Z_MMRFC_OBT_INSUMO_PANResponse;
        
        public Z_MMRFC_OBT_INSUMO_PANResponse1() {
        }
        
        public Z_MMRFC_OBT_INSUMO_PANResponse1(SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_OBT_INSUMO_PANResponse Z_MMRFC_OBT_INSUMO_PANResponse) {
            this.Z_MMRFC_OBT_INSUMO_PANResponse = Z_MMRFC_OBT_INSUMO_PANResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MMRFC_GEN_MOVSTK_PAN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZMPES5960[] iM_POSICIONESField;
        
        private string iM_TEXTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMPES5960[] IM_POSICIONES {
            get {
                return this.iM_POSICIONESField;
            }
            set {
                this.iM_POSICIONESField = value;
                this.RaisePropertyChanged("IM_POSICIONES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IM_TEXTO {
            get {
                return this.iM_TEXTOField;
            }
            set {
                this.iM_TEXTOField = value;
                this.RaisePropertyChanged("IM_TEXTO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MMRFC_GEN_MOVSTK_PANResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BAPI2017_GM_HEAD_RET eX_DOCMATField;
        
        private string eX_EXITOField;
        
        private BAPIRET2[] eX_RETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public BAPI2017_GM_HEAD_RET EX_DOCMAT {
            get {
                return this.eX_DOCMATField;
            }
            set {
                this.eX_DOCMATField = value;
                this.RaisePropertyChanged("EX_DOCMAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string EX_EXITO {
            get {
                return this.eX_EXITOField;
            }
            set {
                this.eX_EXITOField = value;
                this.RaisePropertyChanged("EX_EXITO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPIRET2[] EX_RETURN {
            get {
                return this.eX_RETURNField;
            }
            set {
                this.eX_RETURNField = value;
                this.RaisePropertyChanged("EX_RETURN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_MMRFC_GEN_MOVSTK_PANRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_GEN_MOVSTK_PAN Z_MMRFC_GEN_MOVSTK_PAN;
        
        public Z_MMRFC_GEN_MOVSTK_PANRequest() {
        }
        
        public Z_MMRFC_GEN_MOVSTK_PANRequest(SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_GEN_MOVSTK_PAN Z_MMRFC_GEN_MOVSTK_PAN) {
            this.Z_MMRFC_GEN_MOVSTK_PAN = Z_MMRFC_GEN_MOVSTK_PAN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_MMRFC_GEN_MOVSTK_PANResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_GEN_MOVSTK_PANResponse Z_MMRFC_GEN_MOVSTK_PANResponse;
        
        public Z_MMRFC_GEN_MOVSTK_PANResponse1() {
        }
        
        public Z_MMRFC_GEN_MOVSTK_PANResponse1(SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_GEN_MOVSTK_PANResponse Z_MMRFC_GEN_MOVSTK_PANResponse) {
            this.Z_MMRFC_GEN_MOVSTK_PANResponse = Z_MMRFC_GEN_MOVSTK_PANResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Z_WS_PANOL_DIRECTChannel : SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_WS_PANOL_DIRECT, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Z_WS_PANOL_DIRECTClient : System.ServiceModel.ClientBase<SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_WS_PANOL_DIRECT>, SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_WS_PANOL_DIRECT {
        
        public Z_WS_PANOL_DIRECTClient() {
        }
        
        public Z_WS_PANOL_DIRECTClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Z_WS_PANOL_DIRECTClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Z_WS_PANOL_DIRECTClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Z_WS_PANOL_DIRECTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_LISTADO_MAT_PANResponse1 SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_WS_PANOL_DIRECT.Z_MMRFC_LISTADO_MAT_PAN(SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_LISTADO_MAT_PANRequest request) {
            return base.Channel.Z_MMRFC_LISTADO_MAT_PAN(request);
        }
        
        public SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_LISTADO_MAT_PANResponse Z_MMRFC_LISTADO_MAT_PAN(SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_LISTADO_MAT_PAN Z_MMRFC_LISTADO_MAT_PAN1) {
            SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_LISTADO_MAT_PANRequest inValue = new SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_LISTADO_MAT_PANRequest();
            inValue.Z_MMRFC_LISTADO_MAT_PAN = Z_MMRFC_LISTADO_MAT_PAN1;
            SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_LISTADO_MAT_PANResponse1 retVal = ((SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_WS_PANOL_DIRECT)(this)).Z_MMRFC_LISTADO_MAT_PAN(inValue);
            return retVal.Z_MMRFC_LISTADO_MAT_PANResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_LISTADO_MAT_PANResponse1> SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_WS_PANOL_DIRECT.Z_MMRFC_LISTADO_MAT_PANAsync(SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_LISTADO_MAT_PANRequest request) {
            return base.Channel.Z_MMRFC_LISTADO_MAT_PANAsync(request);
        }
        
        public System.Threading.Tasks.Task<SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_LISTADO_MAT_PANResponse1> Z_MMRFC_LISTADO_MAT_PANAsync(SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_LISTADO_MAT_PAN Z_MMRFC_LISTADO_MAT_PAN) {
            SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_LISTADO_MAT_PANRequest inValue = new SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_LISTADO_MAT_PANRequest();
            inValue.Z_MMRFC_LISTADO_MAT_PAN = Z_MMRFC_LISTADO_MAT_PAN;
            return ((SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_WS_PANOL_DIRECT)(this)).Z_MMRFC_LISTADO_MAT_PANAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_OBT_INSUMO_PANResponse1 SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_WS_PANOL_DIRECT.Z_MMRFC_OBT_INSUMO_PAN(SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_OBT_INSUMO_PANRequest request) {
            return base.Channel.Z_MMRFC_OBT_INSUMO_PAN(request);
        }
        
        public SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_OBT_INSUMO_PANResponse Z_MMRFC_OBT_INSUMO_PAN(SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_OBT_INSUMO_PAN Z_MMRFC_OBT_INSUMO_PAN1) {
            SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_OBT_INSUMO_PANRequest inValue = new SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_OBT_INSUMO_PANRequest();
            inValue.Z_MMRFC_OBT_INSUMO_PAN = Z_MMRFC_OBT_INSUMO_PAN1;
            SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_OBT_INSUMO_PANResponse1 retVal = ((SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_WS_PANOL_DIRECT)(this)).Z_MMRFC_OBT_INSUMO_PAN(inValue);
            return retVal.Z_MMRFC_OBT_INSUMO_PANResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_OBT_INSUMO_PANResponse1> SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_WS_PANOL_DIRECT.Z_MMRFC_OBT_INSUMO_PANAsync(SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_OBT_INSUMO_PANRequest request) {
            return base.Channel.Z_MMRFC_OBT_INSUMO_PANAsync(request);
        }
        
        public System.Threading.Tasks.Task<SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_OBT_INSUMO_PANResponse1> Z_MMRFC_OBT_INSUMO_PANAsync(SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_OBT_INSUMO_PAN Z_MMRFC_OBT_INSUMO_PAN) {
            SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_OBT_INSUMO_PANRequest inValue = new SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_OBT_INSUMO_PANRequest();
            inValue.Z_MMRFC_OBT_INSUMO_PAN = Z_MMRFC_OBT_INSUMO_PAN;
            return ((SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_WS_PANOL_DIRECT)(this)).Z_MMRFC_OBT_INSUMO_PANAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_GEN_MOVSTK_PANResponse1 SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_WS_PANOL_DIRECT.Z_MMRFC_GEN_MOVSTK_PAN(SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_GEN_MOVSTK_PANRequest request) {
            return base.Channel.Z_MMRFC_GEN_MOVSTK_PAN(request);
        }
        
        public SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_GEN_MOVSTK_PANResponse Z_MMRFC_GEN_MOVSTK_PAN(SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_GEN_MOVSTK_PAN Z_MMRFC_GEN_MOVSTK_PAN1) {
            SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_GEN_MOVSTK_PANRequest inValue = new SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_GEN_MOVSTK_PANRequest();
            inValue.Z_MMRFC_GEN_MOVSTK_PAN = Z_MMRFC_GEN_MOVSTK_PAN1;
            SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_GEN_MOVSTK_PANResponse1 retVal = ((SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_WS_PANOL_DIRECT)(this)).Z_MMRFC_GEN_MOVSTK_PAN(inValue);
            return retVal.Z_MMRFC_GEN_MOVSTK_PANResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_GEN_MOVSTK_PANResponse1> SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_WS_PANOL_DIRECT.Z_MMRFC_GEN_MOVSTK_PANAsync(SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_GEN_MOVSTK_PANRequest request) {
            return base.Channel.Z_MMRFC_GEN_MOVSTK_PANAsync(request);
        }
        
        public System.Threading.Tasks.Task<SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_GEN_MOVSTK_PANResponse1> Z_MMRFC_GEN_MOVSTK_PANAsync(SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_GEN_MOVSTK_PAN Z_MMRFC_GEN_MOVSTK_PAN) {
            SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_GEN_MOVSTK_PANRequest inValue = new SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_MMRFC_GEN_MOVSTK_PANRequest();
            inValue.Z_MMRFC_GEN_MOVSTK_PAN = Z_MMRFC_GEN_MOVSTK_PAN;
            return ((SustitucionMOAWS.WS_GAQ_sin_PI_DIRECT_PANOL.Z_WS_PANOL_DIRECT)(this)).Z_MMRFC_GEN_MOVSTK_PANAsync(inValue);
        }
    }
}
