export interface POPosicionDto {
    Id: number,
    NroSolp: number,
    Indice: string,
    Codigo: number,
    Tarea: string,
    CentroComprasDescripcion: string,
    AlmacenComprasDescripcion: string,
    TextoSuministro: string,
    Modelo: string,
    GrupoComprasDescripcion: string,
    Cantidad: number,
    UnidadComprasDescripcion: string,
    MonedaComprasDescripcion: string,
    FechaEntregaServicio: any,
    PlazoEntrega: Date,
    FechaOferta: Date,
    TieneCotizacion: boolean,
    Selected: boolean,
    TodasPosicionesSeleccionadas: boolean,
    ListaPO?:  string[],
}