IF NOT EXISTS(SELECT 1 FROM CategoriaRol inner join Categoria on categoria.Id = CategoriaRol.Categoria_Id inner join Rol on Rol.Id = CategoriaRol.Rol_Id WHERE Rol.Nombre = 'BOLETOS' and Categoria.Nombre = 'Boletos') BEGIN insert into categoriarol values ((select id from rol where rol.Nombre = 'BOLETOS'),(select id from Categoria where Categoria.Nombre = 'Boletos')) END
IF NOT EXISTS(SELECT 1 FROM CategoriaRol inner join Categoria on categoria.Id = CategoriaRol.Categoria_Id inner join Rol on Rol.Id = CategoriaRol.Rol_Id WHERE Rol.Nombre = 'RECLAMO IMPOSITIVO' and Categoria.Nombre = 'Reclamo Impositivo') BEGIN insert into categoriarol values ((select id from rol where rol.Nombre = 'RECLAMO IMPOSITIVO'),(select id from Categoria where Categoria.Nombre = 'Reclamo Impositivo')) END
IF NOT EXISTS(SELECT 1 FROM CategoriaRol inner join Categoria on categoria.Id = CategoriaRol.Categoria_Id inner join Rol on Rol.Id = CategoriaRol.Rol_Id WHERE Rol.Nombre = 'ACTUALIZACIÓN' and Categoria.Nombre = 'Actualización') BEGIN insert into categoriarol values ((select id from rol where rol.Nombre = 'ACTUALIZACIÓN'),(select id from Categoria where Categoria.Nombre = 'Actualización')) END
IF NOT EXISTS(SELECT 1 FROM CategoriaRol inner join Categoria on categoria.Id = CategoriaRol.Categoria_Id inner join Rol on Rol.Id = CategoriaRol.Rol_Id WHERE Rol.Nombre = 'PARCIAL DIRECTO' and Categoria.Nombre = 'Parcial Directo') BEGIN insert into categoriarol values ((select id from rol where rol.Nombre = 'PARCIAL DIRECTO'),(select id from Categoria where Categoria.Nombre = 'Parcial Directo')) END
IF NOT EXISTS(SELECT 1 FROM CategoriaRol inner join Categoria on categoria.Id = CategoriaRol.Categoria_Id inner join Rol on Rol.Id = CategoriaRol.Rol_Id WHERE Rol.Nombre = 'PARCIAL CORREDOR' and Categoria.Nombre = 'Parcial Corredor') BEGIN insert into categoriarol values ((select id from rol where rol.Nombre = 'PARCIAL CORREDOR'),(select id from Categoria where Categoria.Nombre = 'Parcial Corredor')) END
IF NOT EXISTS(SELECT 1 FROM CategoriaRol inner join Categoria on categoria.Id = CategoriaRol.Categoria_Id inner join Rol on Rol.Id = CategoriaRol.Rol_Id WHERE Rol.Nombre = 'FINAL DIRECTO' and Categoria.Nombre = 'Final Directo') BEGIN insert into categoriarol values ((select id from rol where rol.Nombre = 'FINAL DIRECTO'),(select id from Categoria where Categoria.Nombre = 'Final Directo')) END
IF NOT EXISTS(SELECT 1 FROM CategoriaRol inner join Categoria on categoria.Id = CategoriaRol.Categoria_Id inner join Rol on Rol.Id = CategoriaRol.Rol_Id WHERE Rol.Nombre = 'FINAL CORREDOR' and Categoria.Nombre = 'Final Corredor') BEGIN insert into categoriarol values ((select id from rol where rol.Nombre = 'FINAL CORREDOR'),(select id from Categoria where Categoria.Nombre = 'Final Corredor')) END
IF NOT EXISTS(SELECT 1 FROM CategoriaRol inner join Categoria on categoria.Id = CategoriaRol.Categoria_Id inner join Rol on Rol.Id = CategoriaRol.Rol_Id WHERE Rol.Nombre = 'CALIDADES' and Categoria.Nombre = 'Calidades') BEGIN insert into categoriarol values ((select id from rol where rol.Nombre = 'CALIDADES'),(select id from Categoria where Categoria.Nombre = 'Calidades')) END
IF NOT EXISTS(SELECT 1 FROM CategoriaRol inner join Categoria on categoria.Id = CategoriaRol.Categoria_Id inner join Rol on Rol.Id = CategoriaRol.Rol_Id WHERE Rol.Nombre = 'COMISIONES' and Categoria.Nombre = 'Comisiones') BEGIN insert into categoriarol values ((select id from rol where rol.Nombre = 'COMISIONES'),(select id from Categoria where Categoria.Nombre = 'Comisiones')) END
IF NOT EXISTS(SELECT 1 FROM CategoriaRol inner join Categoria on categoria.Id = CategoriaRol.Categoria_Id inner join Rol on Rol.Id = CategoriaRol.Rol_Id WHERE Rol.Nombre = 'COMPROBANTES' and Categoria.Nombre = 'Solicitud de comprobantes') BEGIN insert into categoriarol values ((select id from rol where rol.Nombre = 'COMPROBANTES'),(select id from Categoria where Categoria.Nombre = 'Solicitud de comprobantes')) END
IF NOT EXISTS(SELECT 1 FROM CategoriaRol inner join Categoria on categoria.Id = CategoriaRol.Categoria_Id inner join Rol on Rol.Id = CategoriaRol.Rol_Id WHERE Rol.Nombre = 'APLICACIONES' and Categoria.Nombre = 'Aplicaciones') BEGIN insert into categoriarol values ((select id from rol where rol.Nombre = 'APLICACIONES'),(select id from Categoria where Categoria.Nombre = 'Aplicaciones')) END
IF NOT EXISTS(SELECT 1 FROM CategoriaRol inner join Categoria on categoria.Id = CategoriaRol.Categoria_Id inner join Rol on Rol.Id = CategoriaRol.Rol_Id WHERE Rol.Nombre = 'PESIFICACIONES' and Categoria.Nombre = 'Pesificaciones') BEGIN insert into categoriarol values ((select id from rol where rol.Nombre = 'PESIFICACIONES'),(select id from Categoria where Categoria.Nombre = 'Pesificaciones')) END
IF NOT EXISTS(SELECT 1 FROM CategoriaRol inner join Categoria on categoria.Id = CategoriaRol.Categoria_Id inner join Rol on Rol.Id = CategoriaRol.Rol_Id WHERE Rol.Nombre = 'PAGOS' and Categoria.Nombre = 'Pagos') BEGIN insert into categoriarol values ((select id from rol where rol.Nombre = 'PAGOS'),(select id from Categoria where Categoria.Nombre = 'Pagos')) END
IF NOT EXISTS(SELECT 1 FROM CategoriaRol inner join Categoria on categoria.Id = CategoriaRol.Categoria_Id inner join Rol on Rol.Id = CategoriaRol.Rol_Id WHERE Rol.Nombre = 'FUNCIONAMIENTO WEB' and Categoria.Nombre = 'Funcionamiento Web') BEGIN insert into categoriarol values ((select id from rol where rol.Nombre = 'FUNCIONAMIENTO WEB'),(select id from Categoria where Categoria.Nombre = 'Funcionamiento Web')) END
IF NOT EXISTS(SELECT 1 FROM CategoriaRol inner join Categoria on categoria.Id = CategoriaRol.Categoria_Id inner join Rol on Rol.Id = CategoriaRol.Rol_Id WHERE Rol.Nombre = 'OPERACIONES MATBA' and Categoria.Nombre = 'Operaciones MATBA') BEGIN insert into categoriarol values ((select id from rol where rol.Nombre = 'OPERACIONES MATBA'),(select id from Categoria where Categoria.Nombre = 'Operaciones MATBA')) END
IF NOT EXISTS(SELECT 1 FROM CategoriaRol inner join Categoria on categoria.Id = CategoriaRol.Categoria_Id inner join Rol on Rol.Id = CategoriaRol.Rol_Id WHERE Rol.Nombre = 'PROVEEDOR GENERAL CONSULTA' and Categoria.Nombre = 'Proveedores generales') BEGIN insert into categoriarol values ((select id from rol where rol.Nombre = 'PROVEEDOR GENERAL CONSULTA'),(select id from Categoria where Categoria.Nombre = 'Proveedores generales')) END
IF NOT EXISTS(SELECT 1 FROM CategoriaRol inner join Categoria on categoria.Id = CategoriaRol.Categoria_Id inner join Rol on Rol.Id = CategoriaRol.Rol_Id WHERE Rol.Nombre = 'FLETES CONSULTA' and Categoria.Nombre = 'Fletes') BEGIN insert into categoriarol values ((select id from rol where rol.Nombre = 'FLETES CONSULTA'),(select id from Categoria where Categoria.Nombre = 'Fletes')) END
IF NOT EXISTS(SELECT 1 FROM CategoriaRol inner join Categoria on categoria.Id = CategoriaRol.Categoria_Id inner join Rol on Rol.Id = CategoriaRol.Rol_Id WHERE Rol.Nombre = 'OTROS' and Categoria.Nombre = 'Otros') BEGIN insert into categoriarol values ((select id from rol where rol.Nombre = 'OTROS'),(select id from Categoria where Categoria.Nombre = 'Otros')) END
IF NOT EXISTS(SELECT 1 FROM CategoriaRol inner join Categoria on categoria.Id = CategoriaRol.Categoria_Id inner join Rol on Rol.Id = CategoriaRol.Rol_Id WHERE Rol.Nombre = 'CESIÓN Y RECTIFICACIÓN DE CPE' and Categoria.Nombre = 'Cesión y rectificación de CPE') BEGIN insert into categoriarol values ((select id from rol where rol.Nombre = 'Cesión y rectificación de CPE'),(select id from Categoria where Categoria.Nombre = 'Cesión y rectificación de CPE')) END
IF NOT EXISTS(SELECT 1 FROM CategoriaRol inner join Categoria on categoria.Id = CategoriaRol.Categoria_Id inner join Rol on Rol.Id = CategoriaRol.Rol_Id WHERE Rol.Nombre = 'ORDEN DE CARGA' and Categoria.Nombre = 'ORDEN DE CARGA') BEGIN insert into CategoriaRol values ((select id from rol where rol.Nombre = 'ORDEN DE CARGA'),(select id from Categoria where Categoria.Nombre = 'ORDEN DE CARGA')) END