--Script para categorias
IF NOT EXISTS (SELECT TOP 1 1 FROM Categoria WHERE Code = 'REI' AND Nombre = 'Reclamo Impositivo') BEGIN INSERT Categoria(Code, Nombre) VALUES ('REI','Reclamo Impositivo') END
IF NOT EXISTS (SELECT TOP 1 1 FROM Categoria WHERE Code = 'BOL' AND Nombre = 'Boletos') BEGIN INSERT Categoria(Code, Nombre) VALUES ('BOL','Boletos') END
IF NOT EXISTS (SELECT TOP 1 1 FROM Categoria WHERE Code = 'ACT' AND Nombre = 'Actualización') BEGIN INSERT Categoria(Code, Nombre) VALUES ('ACT','Actualización') END
IF NOT EXISTS (SELECT TOP 1 1 FROM Categoria WHERE Code = 'PAR' AND Nombre = 'Parcial') BEGIN INSERT Categoria(Code, Nombre) VALUES ('PAR','Parcial') END
IF NOT EXISTS (SELECT TOP 1 1 FROM Categoria WHERE Code = 'PARDIR' AND Nombre = 'Parcial Directo') BEGIN INSERT Categoria(Code, Nombre) VALUES ('PARDIR','Parcial Directo') END
IF NOT EXISTS (SELECT TOP 1 1 FROM Categoria WHERE Code = 'PARCOR' AND Nombre = 'Parcial Corredor') BEGIN INSERT Categoria(Code, Nombre) VALUES ('PARDIR','Parcial Corredor') END
IF NOT EXISTS (SELECT TOP 1 1 FROM Categoria WHERE Code = 'FIN' AND Nombre = 'Final') BEGIN INSERT Categoria(Code, Nombre) VALUES ('FIN','Final') END
IF NOT EXISTS (SELECT TOP 1 1 FROM Categoria WHERE Code = 'FINDIR' AND Nombre = 'Final Directo') BEGIN INSERT Categoria(Code, Nombre) VALUES ('FINDIR','Final Directo') END
IF NOT EXISTS (SELECT TOP 1 1 FROM Categoria WHERE Code = 'FINCOR' AND Nombre = 'Final Corredor') BEGIN INSERT Categoria(Code, Nombre) VALUES ('FINCOR','Final Corredor') END
IF NOT EXISTS (SELECT TOP 1 1 FROM Categoria WHERE Code = 'CAL' AND Nombre = 'Calidades') BEGIN INSERT Categoria(Code, Nombre) VALUES ('CAL','Calidades') END
IF NOT EXISTS (SELECT TOP 1 1 FROM Categoria WHERE Code = 'COM' AND Nombre = 'Comisiones') BEGIN INSERT Categoria(Code, Nombre) VALUES ('COM','Comisiones') END
IF NOT EXISTS (SELECT TOP 1 1 FROM Categoria WHERE Code = 'COMP' AND Nombre = 'Solicitud de comprobantes') BEGIN INSERT Categoria(Code, Nombre) VALUES ('COMP','Solicitud de comprobantes') END
IF NOT EXISTS (SELECT TOP 1 1 FROM Categoria WHERE Code = 'APP' AND Nombre = 'Aplicaciones') BEGIN INSERT Categoria(Code, Nombre) VALUES ('APP','Aplicaciones') END
IF NOT EXISTS (SELECT TOP 1 1 FROM Categoria WHERE Code = 'PES' AND Nombre = 'Pesificaciones') BEGIN INSERT Categoria(Code, Nombre) VALUES ('PES','Pesificaciones') END
IF NOT EXISTS (SELECT TOP 1 1 FROM Categoria WHERE Code = 'PAG' AND Nombre = 'Pagos') BEGIN INSERT Categoria(Code, Nombre) VALUES ('PAG','Pagos') END
IF NOT EXISTS (SELECT TOP 1 1 FROM Categoria WHERE Code = 'FWEB' AND Nombre = 'Funcionamiento Web') BEGIN INSERT Categoria(Code, Nombre) VALUES ('FWEB','Funcionamiento Web') END
IF NOT EXISTS (SELECT TOP 1 1 FROM Categoria WHERE Code = 'MATBA' AND Nombre = 'Operaciones MATBA') BEGIN INSERT Categoria(Code, Nombre) VALUES ('MATBA','Operaciones MATBA') END
IF NOT EXISTS (SELECT TOP 1 1 FROM Categoria WHERE Code = 'PROVG' AND Nombre = 'Proveedores generales') BEGIN INSERT Categoria(Code, Nombre) VALUES ('PROVG','Proveedores generales') END
IF NOT EXISTS (SELECT TOP 1 1 FROM Categoria WHERE Code = 'FLET' AND Nombre = 'Fletes') BEGIN INSERT Categoria(Code, Nombre) VALUES ('FLET','Fletes') END
IF NOT EXISTS (SELECT TOP 1 1 FROM Categoria WHERE Code = 'OTRO' AND Nombre = 'Otros') BEGIN INSERT Categoria(Code, Nombre) VALUES ('OTRO','Otros') END
IF NOT EXISTS (SELECT TOP 1 1 FROM Categoria WHERE Code = 'CRCPE' AND Nombre = 'Cesión y rectificación de CPE') BEGIN INSERT Categoria(Code, Nombre) VALUES ('CRCPE','Cesión y rectificación de CPE') END
IF NOT EXISTS (SELECT TOP 1 1 FROM Categoria WHERE Code = 'ORD' AND Nombre = 'Orden de Carga') BEGIN INSERT Categoria(Code, Nombre) VALUES ('ORD','Orden de Carga') END
IF NOT EXISTS (SELECT TOP 1 1 FROM Categoria WHERE Code = 'DISCAL' AND Nombre = 'Discrepancia Calidades') BEGIN INSERT Categoria(Code, Nombre) VALUES ('DISCAL','Discrepancia Calidades') END


--Script para subcategorias
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Retenciones' and Categoria.Nombre = 'Reclamo Impositivo') BEGIN insert into SubCategoria select 'RET','Retenciones',id from Categoria where Nombre = 'Reclamo Impositivo' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Percepciones' and Categoria.Nombre = 'Reclamo Impositivo') BEGIN insert into SubCategoria select 'PER','Percepciones',id from Categoria where Nombre = 'Reclamo Impositivo' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Contratos' and Categoria.Nombre = 'Boletos') BEGIN insert into SubCategoria select 'CON','Contratos',id from Categoria where Nombre = 'Boletos' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Registraciones' and Categoria.Nombre = 'Boletos') BEGIN insert into SubCategoria select 'REG','Registraciones',id from Categoria where Nombre = 'Boletos' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Oblea Plan Canje' and Categoria.Nombre = 'Boletos') BEGIN insert into SubCategoria select 'OPC','Oblea Plan Canje',id from Categoria where Nombre = 'Boletos' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Generación y Modificación de Boletos' and Categoria.Nombre = 'Boletos') BEGIN insert into SubCategoria select 'GMB','Generación y Modificación de Boletos',id from Categoria where Nombre = 'Boletos' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Impositiva' and Categoria.Nombre = 'Actualización') BEGIN insert into SubCategoria select 'IMP','Impositiva',id from Categoria where Nombre = 'Actualización' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Informe comercial' and Categoria.Nombre = 'Actualización') BEGIN insert into SubCategoria select 'INF','Informe comercial',id from Categoria where Nombre = 'Actualización' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Carta presentacón' and Categoria.Nombre = 'Actualización') BEGIN insert into SubCategoria select 'CAP','Carta presentacón',id from Categoria where Nombre = 'Actualización' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'No registradas, Observadas y Rechazadas' and Categoria.Nombre = 'Parcial') BEGIN insert into SubCategoria select 'NROR','No registradas, Observadas y Rechazadas',id from Categoria where Nombre = 'Parcial' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'No registradas, Observadas y Rechazadas' and Categoria.Nombre = 'Parcial Directo') BEGIN insert into SubCategoria select 'NRORPD','No registradas, Observadas y Rechazadas',id from Categoria where Nombre = 'Parcial Directo' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'No registradas, Observadas y Rechazadas' and Categoria.Nombre = 'Parcial Corredor') BEGIN insert into SubCategoria select 'NRORPC','No registradas, Observadas y Rechazadas',id from Categoria where Nombre = 'Parcial Corredor' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'No registradas, Observadas y Rechazadas' and Categoria.Nombre = 'Final') BEGIN insert into SubCategoria select 'NROR','No registradas, Observadas y Rechazadas',id from Categoria where Nombre = 'Final' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Proforma' and Categoria.Nombre = 'Final') BEGIN insert into SubCategoria select 'PROF','Proforma',id from Categoria where Nombre = 'Final' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Servicios' and Categoria.Nombre = 'Final') BEGIN insert into SubCategoria select 'SERV','Servicios',id from Categoria where Nombre = 'Final' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Bonificaciones y rebajas' and Categoria.Nombre = 'Final') BEGIN insert into SubCategoria select 'BON','Bonificaciones y rebajas',id from Categoria where Nombre = 'Final' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Certificaciones de Granos' and Categoria.Nombre = 'Final') BEGIN insert into SubCategoria select 'CDG','Certificaciones de Granos',id from Categoria where Nombre = 'Final' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'No registradas, Observadas y Rechazadas' and Categoria.Nombre = 'Final Directo') BEGIN insert into SubCategoria select 'NRORFD','No registradas, Observadas y Rechazadas',id from Categoria where Nombre = 'Final Directo' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Proforma' and Categoria.Nombre = 'Final Directo') BEGIN insert into SubCategoria select 'PROFFD','Proforma',id from Categoria where Nombre = 'Final Directo' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Servicios' and Categoria.Nombre = 'Final Directo') BEGIN insert into SubCategoria select 'SERVFD','Servicios',id from Categoria where Nombre = 'Final Directo' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Bonificaciones y rebajas' and Categoria.Nombre = 'Final Directo') BEGIN insert into SubCategoria select 'BONFD','Bonificaciones y rebajas',id from Categoria where Nombre = 'Final Directo' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Certificaciones de Granos' and Categoria.Nombre = 'Final Directo') BEGIN insert into SubCategoria select 'CDGFD','Certificaciones de Granos',id from Categoria where Nombre = 'Final Directo' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'No registradas, Observadas y Rechazadas' and Categoria.Nombre = 'Final Corredor') BEGIN insert into SubCategoria select 'NRORFC','No registradas, Observadas y Rechazadas',id from Categoria where Nombre = 'Final Corredor' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Proforma' and Categoria.Nombre = 'Final Corredor') BEGIN insert into SubCategoria select 'PROFFC','Proforma',id from Categoria where Nombre = 'Final Corredor' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Servicios' and Categoria.Nombre = 'Final Corredor') BEGIN insert into SubCategoria select 'SERVFC','Servicios',id from Categoria where Nombre = 'Final Corredor' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Bonificaciones y rebajas' and Categoria.Nombre = 'Final Corredor') BEGIN insert into SubCategoria select 'BONFC','Bonificaciones y rebajas',id from Categoria where Nombre = 'Final Corredor' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Certificaciones de Granos' and Categoria.Nombre = 'Final Corredor') BEGIN insert into SubCategoria select 'CDGFC','Certificaciones de Granos',id from Categoria where Nombre = 'Final Corredor' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Recibos' and Categoria.Nombre = 'Operaciones MATBA') BEGIN insert into SubCategoria select 'REC','Recibos',id from Categoria where Nombre = 'Operaciones MATBA' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Faltantes/Excedentes' and Categoria.Nombre = 'Operaciones MATBA') BEGIN insert into SubCategoria select 'FAL','Faltantes/Excedentes',id from Categoria where Nombre = 'Operaciones MATBA' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Calidades' and Categoria.Nombre = 'Operaciones MATBA') BEGIN insert into SubCategoria select 'CAL','Calidades',id from Categoria where Nombre = 'Operaciones MATBA' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Comprobantes no visualizados' and Categoria.Nombre = 'Proveedores generales') BEGIN insert into SubCategoria select 'CNV','Comprobantes no visualizados',id from Categoria where Nombre = 'Proveedores generales' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Comprobantes en gestión' and Categoria.Nombre = 'Proveedores generales') BEGIN insert into SubCategoria select 'CEG','Comprobantes en gestión',id from Categoria where Nombre = 'Proveedores generales' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Vencimiento de comprobantes' and Categoria.Nombre = 'Proveedores generales') BEGIN insert into SubCategoria select 'VENC','Vencimiento de comprobantes',id from Categoria where Nombre = 'Proveedores generales' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Otros' and Categoria.Nombre = 'Proveedores generales') BEGIN insert into SubCategoria select 'POTR','Otros',id from Categoria where Nombre = 'Proveedores generales' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Proforma de fletes' and Categoria.Nombre = 'Fletes') BEGIN insert into SubCategoria select 'PDF','Proforma de fletes',id from Categoria where Nombre = 'Fletes' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Consulta Carta de Porte' and Categoria.Nombre = 'Fletes') BEGIN insert into SubCategoria select 'CCP','Consulta Carta de Porte',id from Categoria where Nombre = 'Fletes' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'CM 05' and Categoria.Nombre = 'Actualización') BEGIN insert into SubCategoria select 'CM05','CM 05',id from Categoria where Nombre = 'Actualización' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Granos' and Categoria.Nombre = 'Comisiones') BEGIN insert into SubCategoria select 'GRA','Granos',id from Categoria where Nombre = 'Comisiones' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Subproducto' and Categoria.Nombre = 'Comisiones') BEGIN insert into SubCategoria select 'SUBP','Subproducto',id from Categoria where Nombre = 'Comisiones' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Solicitud de proforma flete' and Categoria.Nombre = 'Parcial') BEGIN insert into SubCategoria select 'PFLET','Solicitud de proforma flete',id from Categoria where Nombre = 'Parcial' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Solicitud de proforma flete' and Categoria.Nombre = 'Parcial Directo') BEGIN insert into SubCategoria select 'PFLETPD','Solicitud de proforma flete',id from Categoria where Nombre = 'Parcial Directo' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Solicitud de proforma flete' and Categoria.Nombre = 'Parcial Corredor') BEGIN insert into SubCategoria select 'PFLETPC','Solicitud de proforma flete',id from Categoria where Nombre = 'Parcial Corredor' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'CTG' and Categoria.Nombre = 'Orden de Carga') BEGIN insert into SubCategoria select 'CTG','CTG',id from Categoria where Nombre = 'Orden de Carga' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Datos incorrectos en orden' and Categoria.Nombre = 'Orden de Carga') BEGIN insert into SubCategoria select 'ERROROC','Datos incorrectos en orden',id from Categoria where Nombre = 'Orden de Carga' END
IF NOT EXISTS (select top 1 1 from SubCategoria inner join Categoria on SubCategoria.Categoria_Id = Categoria.Id where SubCategoria.Nombre = 'Otros' and Categoria.Nombre = 'Orden de Carga') BEGIN insert into SubCategoria select 'OTROSOC','Otros',id from Categoria where Nombre = 'Orden de Carga' END
