--Rol
--select *,'IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = '''+Codigo+''' AND Nombre = '''+Nombre+''') BEGIN INSERT INTO Rol values ('''+Codigo+''','''+Nombre+''','+ltrim(EsEditable)+')'from rol
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'ADM' AND Nombre = 'ADMINISTRACION') BEGIN INSERT INTO Rol values ('ADM','ADMINISTRACION',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'ADU' AND Nombre = 'ADUANA') BEGIN INSERT INTO Rol values ('ADU','ADUANA',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'CLIENT' AND Nombre = 'SOLO CLIENTES') BEGIN INSERT INTO Rol values ('CLIENT','SOLO CLIENTES',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'FLETE' AND Nombre = 'FLETES') BEGIN INSERT INTO Rol values ('FLETE','FLETES',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'GRAN' AND Nombre = 'GRANOS') BEGIN INSERT INTO Rol values ('GRAN','GRANOS',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'GRANDA' AND Nombre = 'GRANOS + DATAAGRO') BEGIN INSERT INTO Rol values ('GRANDA','GRANOS + DATAAGRO',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'GYNG' AND Nombre = 'GRANOS Y NO GRANOS') BEGIN INSERT INTO Rol values ('GYNG','GRANOS Y NO GRANOS',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'GYNGDA' AND Nombre = 'GRANOS Y NO GRANOS + DATAAGRO') BEGIN INSERT INTO Rol values ('GYNGDA','GRANOS Y NO GRANOS + DATAAGRO',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'GYNGF' AND Nombre = 'GRANOS Y NO GRANOS + FLETE') BEGIN INSERT INTO Rol values ('GYNGF','GRANOS Y NO GRANOS + FLETE',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'GYNGP' AND Nombre = 'GRANOS Y NO GRANOS +PESIF TEST') BEGIN INSERT INTO Rol values ('GYNGP','GRANOS Y NO GRANOS +PESIF TEST',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'NOGRAN' AND Nombre = 'NO GRANOS') BEGIN INSERT INTO Rol values ('NOGRAN','NO GRANOS',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'RYDA' AND Nombre = 'RYD ADMINISTRACION') BEGIN INSERT INTO Rol values ('RYDA','RYD ADMINISTRACION',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'RYDU' AND Nombre = 'RYD USUARIO') BEGIN INSERT INTO Rol values ('RYDU','RYD USUARIO',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'TODOS' AND Nombre = 'TODOS') BEGIN INSERT INTO Rol values ('TODOS','TODOS',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'NUEG' AND Nombre = 'NUEVO USUARIO GRANOS') BEGIN INSERT INTO Rol values ('NUEG','NUEVO USUARIO GRANOS',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'NOIMP' AND Nombre = 'USUARIO NO IMPLEMENTADO') BEGIN INSERT INTO Rol values ('NOIMP','USUARIO NO IMPLEMENTADO',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'DDAG' AND Nombre = 'DESHABILITADO EN DATAAGRO') BEGIN INSERT INTO Rol values ('DDAG','DESHABILITADO EN DATAAGRO',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'OPE' AND Nombre = 'OPERADOR') BEGIN INSERT INTO Rol values ('OPE','OPERADOR',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'APRO' AND Nombre = 'APROBADOR') BEGIN INSERT INTO Rol values ('APRO','APROBADOR',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'DES' AND Nombre = 'DESHABILITADO') BEGIN INSERT INTO Rol values ('DES','DESHABILITADO',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'NUECORR' AND Nombre = 'NUEVO CORREDOR') BEGIN INSERT INTO Rol values ('NUECORR','NUEVO CORREDOR',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'CORR' AND Nombre = 'CORREDOR') BEGIN INSERT INTO Rol values ('CORR','CORREDOR',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'MF' AND Nombre = 'MULTIFIRMA') BEGIN INSERT INTO Rol values ('MF','MULTIFIRMA',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'NUENOGRAN' AND Nombre = 'NUEVO USUARIO NO GRANOS') BEGIN INSERT INTO Rol values ('NUENOGRAN','NUEVO USUARIO NO GRANOS',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'COMPRAS' AND Nombre = 'COMPRAS') BEGIN INSERT INTO Rol values ('COMPRAS','COMPRAS',1) END  
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'COMERCIAL' AND Nombre = 'COMERCIAL') BEGIN INSERT INTO Rol values ('COMERCIAL','COMERCIAL',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'ADMINCCSS' AND Nombre = 'ADMIN CAMPO SUSTENTABLE') BEGIN INSERT INTO Rol values ('ADMINCCSS','ADMIN CAMPO SUSTENTABLE',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'APIKEY' AND Nombre = 'APIKEY') BEGIN INSERT INTO Rol values ('APIKEY','APIKEY',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'BOL' AND Nombre = 'BOLETOS') BEGIN INSERT INTO Rol values ('BOL','BOLETOS',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'REI' AND Nombre = 'RECLAMO IMPOSITIVO') BEGIN INSERT INTO Rol values ('REI','RECLAMO IMPOSITIVO',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'ACT' AND Nombre = 'ACTUALIZACIÓN') BEGIN INSERT INTO Rol values ('ACT','ACTUALIZACIÓN',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'PARDIR' AND Nombre = 'PARCIAL DIRECTO') BEGIN INSERT INTO Rol values ('PARDIR','PARCIAL DIRECTO',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'PARCOR' AND Nombre = 'PARCIAL CORREDOR') BEGIN INSERT INTO Rol values ('PARCOR','PARCIAL CORREDOR',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'FINDIR' AND Nombre = 'FINAL DIRECTO') BEGIN INSERT INTO Rol values ('FINDIR','FINAL DIRECTO',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'FINCOR' AND Nombre = 'FINAL CORREDOR') BEGIN INSERT INTO Rol values ('FINCOR','FINAL CORREDOR',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'CAL' AND Nombre = 'CALIDADES') BEGIN INSERT INTO Rol values ('CAL','CALIDADES',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'COM' AND Nombre = 'COMISIONES') BEGIN INSERT INTO Rol values ('COM','COMISIONES',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'COMP' AND Nombre = 'COMPROBANTES') BEGIN INSERT INTO Rol values ('COMP','COMPROBANTES',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'APP' AND Nombre = 'APLICACIONES') BEGIN INSERT INTO Rol values ('APP','APLICACIONES',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'PES' AND Nombre = 'PESIFICACIONES') BEGIN INSERT INTO Rol values ('PES','PESIFICACIONES',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'PAG' AND Nombre = 'PAGOS') BEGIN INSERT INTO Rol values ('PAG','PAGOS',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'FWEB' AND Nombre = 'FUNCIONAMIENTO WEB') BEGIN INSERT INTO Rol values ('FWEB','FUNCIONAMIENTO WEB',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'MATBA' AND Nombre = 'OPERACIONES MATBA') BEGIN INSERT INTO Rol values ('MATBA','OPERACIONES MATBA',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'PROVGC' AND Nombre = 'PROVEEDOR GENERAL CONSULTA') BEGIN INSERT INTO Rol values ('PROVGC','PROVEEDOR GENERAL CONSULTA',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'FLECONSULTA' AND Nombre = 'FLETES CONSULTA') BEGIN INSERT INTO Rol values ('FLECONSULTA','FLETES CONSULTA',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'OTRO' AND Nombre = 'OTROS') BEGIN INSERT INTO Rol values ('OTRO','OTROS',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'AIGRAN' AND Nombre = 'ALTA INTERNA GRANOS') BEGIN INSERT INTO Rol values ('AIGRAN','ALTA INTERNA GRANOS',1) END
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'AINOGRAN' AND Nombre = 'ALTA INTERNA NO GRANOS') BEGIN INSERT INTO Rol values ('AINOGRAN','ALTA INTERNA NO GRANOS',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'ADMCM05' AND Nombre = 'Gestion CM05') BEGIN INSERT INTO Rol values ('ADMCM05','Gestion CM05',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'SOLP' AND Nombre = 'SOLP') BEGIN INSERT INTO Rol values ('SOLP','SOLP',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'ADMINPLATCOMPRAS' AND Nombre = 'ADMIN PLATAFORMA COMPRAS') BEGIN INSERT INTO Rol values ('ADMINPLATCOMPRAS','ADMIN PLATAFORMA COMPRAS',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'ACCESO QR' AND Nombre = 'Acceso QR') BEGIN INSERT INTO Rol values ('ACCESO QR','Acceso QR',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'MESAFAS' AND Nombre = 'MESA FAS') BEGIN INSERT INTO Rol values ('MESAFAS','MESA FAS',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'PUERTO' AND Nombre = 'PUERTO') BEGIN INSERT INTO Rol values ('PUERTO','PUERTO',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'NUECLI' AND Nombre = 'NUEVO CLIENTE') BEGIN INSERT INTO Rol values ('NUECLI','NUEVO CLIENTE',1) END 
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'CRDECPE' AND Nombre = 'CESIÓN Y RECTIFICACIÓN DE CPE') BEGIN INSERT INTO Rol values ('CRDECPE','CESIÓN Y RECTIFICACIÓN DE CPE',1) END
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'ANUL' AND Nombre = 'ANULADOR') BEGIN INSERT INTO Rol values ('ANUL','ANULADOR',1) END
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'ECHEQ ADMIN' AND Nombre = 'GESTION ECHEQ ADMIN') BEGIN INSERT INTO Rol values ('ECHEQ ADMIN','GESTION ECHEQ ADMIN',1) END
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'FASON' AND Nombre = 'FASON') BEGIN INSERT INTO Rol values ('FASON','FASON',1) END
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'FASON ADMIN' AND Nombre = 'FASON ADMIN') BEGIN INSERT INTO Rol values ('FASON ADMIN','FASON ADMIN',1) END
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'APLCCPP' AND Nombre = 'APLICACION CCPP') BEGIN INSERT INTO Rol values ('APLCCPP','APLICACION CCPP',1) END
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'APLCCPP ADMIN' AND Nombre = 'APLICACION CCPP ADMIN') BEGIN INSERT INTO Rol values ('APLCCPP ADMIN','APLICACION CCPP ADMIN',1) END
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'COMPRADOR' AND Nombre = 'COMPRADOR') BEGIN INSERT INTO Rol values ('COMPRADOR','COMPRADOR', 1) END
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'FLETE MOA' AND Nombre = 'FLETE MOA') BEGIN INSERT INTO Rol values ('FLETE MOA','FLETE MOA', 1) END
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'COMPRASADMIN' AND Nombre = 'COMPRAS ADMIN') BEGIN INSERT INTO Rol values ('COMPRASADMIN','COMPRAS ADMIN',1) END
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'ORD' AND Nombre = 'ORDEN DE CARGA') BEGIN INSERT INTO Rol values ('ORD','ORDEN DE CARGA',1) END
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'DISCAL' AND Nombre = 'DISCREPANCIA CALIDADES') BEGIN INSERT INTO Rol values ('DISCAL','DISCREPANCIA CALIDADES',1) END
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'RESIDUOS' and Nombre = 'RESIDUOS') BEGIN INSERT INTO Rol VALUES ('RESIDUOS','RESIDUOS',1) END
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'RESIDUOS ADMIN' and Nombre = 'RESIDUOS ADMIN') BEGIN INSERT INTO Rol VALUES ('RESIDUOS ADMIN','RESIDUOS ADMIN',1) END
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'ALLES' AND Nombre = 'VER TODOS LOS ESTADOS DE ES') BEGIN INSERT INTO Rol values ('ALLES','VER TODOS LOS ESTADOS DE ES',1) END
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'ADMINCONTMA' AND Nombre = 'ADMIN CONTABILIZACION MES ANTERIOR') BEGIN INSERT INTO Rol values ('ADMINCONTMA','ADMIN CONTABILIZACION MES ANTERIOR',1) END 

-- El rol 'CLIENTE CON CPEDG' deja de estar vigente
--IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'APLCLICPEDG' AND Nombre = 'CLIENTE CON CPEDG') BEGIN INSERT INTO Rol values ('APLCLICPEDG','CLIENTE CON CPEDG', 1) END
IF EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'APLCLICPEDG' AND Nombre = 'CLIENTE CON CPEDG') BEGIN DELETE Rol WHERE Codigo = 'APLCLICPEDG' AND Nombre = 'CLIENTE CON CPEDG' END

--ROL API
--ORDENES DE RESIDUOS
IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'API_ORDRESIDUOS' and Nombre = 'API ORDENES RESIDUOS') BEGIN INSERT INTO Rol VALUES ('API_ORDRESIDUOS','API ORDENES RESIDUOS',1) END

IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'CERTIFICACION' and Nombre = 'CERTIFICACIÓN DE SERVICIOS') BEGIN INSERT INTO Rol VALUES ('CERTIFICACION','CERTIFICACIÓN DE SERVICIOS',1) END

IF NOT EXISTS(SELECT 1 FROM Rol WHERE Codigo = 'CERTIFICACION EXTERNA' and Nombre = 'CERTIFICACIÓN DE SERVICIOS') BEGIN INSERT INTO Rol VALUES ('CERTIFICACION EXTERNA','CERTIFICACIÓN DE SERVICIOS',1) END

