//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SustitucionMOAWS.VendedorHabilitadoWebServiceMOA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:OPERACIONES", ConfigurationName="VendedorHabilitadoWebServiceMOA.SI_MPMF_MOAOP_VENDED_HABILIT")]
    public interface SI_MPMF_MOAOP_VENDED_HABILIT {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SustitucionMOAWS.VendedorHabilitadoWebServiceMOA.SI_MPMF_MOAOP_VENDED_HABILITResponse SI_MPMF_MOAOP_VENDED_HABILIT(SustitucionMOAWS.VendedorHabilitadoWebServiceMOA.SI_MPMF_MOAOP_VENDED_HABILITRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SustitucionMOAWS.VendedorHabilitadoWebServiceMOA.SI_MPMF_MOAOP_VENDED_HABILITResponse> SI_MPMF_MOAOP_VENDED_HABILITAsync(SustitucionMOAWS.VendedorHabilitadoWebServiceMOA.SI_MPMF_MOAOP_VENDED_HABILITRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPTE3420 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mANDTField;
        
        private string lIFNRField;
        
        private string cLASIFICACIONField;
        
        private string iNSCRIPTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MANDT {
            get {
                return this.mANDTField;
            }
            set {
                this.mANDTField = value;
                this.RaisePropertyChanged("MANDT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
                this.RaisePropertyChanged("LIFNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CLASIFICACION {
            get {
                return this.cLASIFICACIONField;
            }
            set {
                this.cLASIFICACIONField = value;
                this.RaisePropertyChanged("CLASIFICACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string INSCRIPTO {
            get {
                return this.iNSCRIPTOField;
            }
            set {
                this.iNSCRIPTOField = value;
                this.RaisePropertyChanged("INSCRIPTO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES4450 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pROVEEDORField;
        
        private string dESCRIPCIONField;
        
        private decimal eXENCIONField;
        
        private bool eXENCIONFieldSpecified;
        
        private string fECHA_DESDEField;
        
        private string fECHA_HASTAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PROVEEDOR {
            get {
                return this.pROVEEDORField;
            }
            set {
                this.pROVEEDORField = value;
                this.RaisePropertyChanged("PROVEEDOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
                this.RaisePropertyChanged("DESCRIPCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal EXENCION {
            get {
                return this.eXENCIONField;
            }
            set {
                this.eXENCIONField = value;
                this.RaisePropertyChanged("EXENCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EXENCIONSpecified {
            get {
                return this.eXENCIONFieldSpecified;
            }
            set {
                this.eXENCIONFieldSpecified = value;
                this.RaisePropertyChanged("EXENCIONSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string FECHA_DESDE {
            get {
                return this.fECHA_DESDEField;
            }
            set {
                this.fECHA_DESDEField = value;
                this.RaisePropertyChanged("FECHA_DESDE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string FECHA_HASTA {
            get {
                return this.fECHA_HASTAField;
            }
            set {
                this.fECHA_HASTAField = value;
                this.RaisePropertyChanged("FECHA_HASTA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES4430 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pROVEEDORField;
        
        private string pROVINCIAField;
        
        private decimal cOEFICIENTEField;
        
        private bool cOEFICIENTEFieldSpecified;
        
        private string dESCRIPCIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PROVEEDOR {
            get {
                return this.pROVEEDORField;
            }
            set {
                this.pROVEEDORField = value;
                this.RaisePropertyChanged("PROVEEDOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PROVINCIA {
            get {
                return this.pROVINCIAField;
            }
            set {
                this.pROVINCIAField = value;
                this.RaisePropertyChanged("PROVINCIA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal COEFICIENTE {
            get {
                return this.cOEFICIENTEField;
            }
            set {
                this.cOEFICIENTEField = value;
                this.RaisePropertyChanged("COEFICIENTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool COEFICIENTESpecified {
            get {
                return this.cOEFICIENTEFieldSpecified;
            }
            set {
                this.cOEFICIENTEFieldSpecified = value;
                this.RaisePropertyChanged("COEFICIENTESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
                this.RaisePropertyChanged("DESCRIPCION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES4470 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pROVEEDORField;
        
        private string dESCRIPCIONField;
        
        private string rG2300Field;
        
        private string cUITField;
        
        private string aCTIVIDAD_AFIPField;
        
        private string cALLE_FISCALField;
        
        private string lOCA_FISCALField;
        
        private string pROV_FISCALField;
        
        private string cP_FISCALField;
        
        private string cALLE_ENVIOField;
        
        private string lOCA_ENVIOField;
        
        private string pROV_ENVIOField;
        
        private string cP_ENVIOField;
        
        private string cATE_FISCAL_RETField;
        
        private string nRO_INSC_IIBBField;
        
        private string cATE_FISCAL_IIBBField;
        
        private string tRIBU_DIF_PRECIOField;
        
        private string f1276Field;
        
        private string cM05Field;
        
        private string f_LEGAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PROVEEDOR {
            get {
                return this.pROVEEDORField;
            }
            set {
                this.pROVEEDORField = value;
                this.RaisePropertyChanged("PROVEEDOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
                this.RaisePropertyChanged("DESCRIPCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string RG2300 {
            get {
                return this.rG2300Field;
            }
            set {
                this.rG2300Field = value;
                this.RaisePropertyChanged("RG2300");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CUIT {
            get {
                return this.cUITField;
            }
            set {
                this.cUITField = value;
                this.RaisePropertyChanged("CUIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ACTIVIDAD_AFIP {
            get {
                return this.aCTIVIDAD_AFIPField;
            }
            set {
                this.aCTIVIDAD_AFIPField = value;
                this.RaisePropertyChanged("ACTIVIDAD_AFIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string CALLE_FISCAL {
            get {
                return this.cALLE_FISCALField;
            }
            set {
                this.cALLE_FISCALField = value;
                this.RaisePropertyChanged("CALLE_FISCAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string LOCA_FISCAL {
            get {
                return this.lOCA_FISCALField;
            }
            set {
                this.lOCA_FISCALField = value;
                this.RaisePropertyChanged("LOCA_FISCAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string PROV_FISCAL {
            get {
                return this.pROV_FISCALField;
            }
            set {
                this.pROV_FISCALField = value;
                this.RaisePropertyChanged("PROV_FISCAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string CP_FISCAL {
            get {
                return this.cP_FISCALField;
            }
            set {
                this.cP_FISCALField = value;
                this.RaisePropertyChanged("CP_FISCAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string CALLE_ENVIO {
            get {
                return this.cALLE_ENVIOField;
            }
            set {
                this.cALLE_ENVIOField = value;
                this.RaisePropertyChanged("CALLE_ENVIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string LOCA_ENVIO {
            get {
                return this.lOCA_ENVIOField;
            }
            set {
                this.lOCA_ENVIOField = value;
                this.RaisePropertyChanged("LOCA_ENVIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string PROV_ENVIO {
            get {
                return this.pROV_ENVIOField;
            }
            set {
                this.pROV_ENVIOField = value;
                this.RaisePropertyChanged("PROV_ENVIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string CP_ENVIO {
            get {
                return this.cP_ENVIOField;
            }
            set {
                this.cP_ENVIOField = value;
                this.RaisePropertyChanged("CP_ENVIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string CATE_FISCAL_RET {
            get {
                return this.cATE_FISCAL_RETField;
            }
            set {
                this.cATE_FISCAL_RETField = value;
                this.RaisePropertyChanged("CATE_FISCAL_RET");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string NRO_INSC_IIBB {
            get {
                return this.nRO_INSC_IIBBField;
            }
            set {
                this.nRO_INSC_IIBBField = value;
                this.RaisePropertyChanged("NRO_INSC_IIBB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string CATE_FISCAL_IIBB {
            get {
                return this.cATE_FISCAL_IIBBField;
            }
            set {
                this.cATE_FISCAL_IIBBField = value;
                this.RaisePropertyChanged("CATE_FISCAL_IIBB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string TRIBU_DIF_PRECIO {
            get {
                return this.tRIBU_DIF_PRECIOField;
            }
            set {
                this.tRIBU_DIF_PRECIOField = value;
                this.RaisePropertyChanged("TRIBU_DIF_PRECIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string F1276 {
            get {
                return this.f1276Field;
            }
            set {
                this.f1276Field = value;
                this.RaisePropertyChanged("F1276");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string CM05 {
            get {
                return this.cM05Field;
            }
            set {
                this.cM05Field = value;
                this.RaisePropertyChanged("CM05");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string F_LEGA {
            get {
                return this.f_LEGAField;
            }
            set {
                this.f_LEGAField = value;
                this.RaisePropertyChanged("F_LEGA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MPMF_MOAOP_VENDED_HABILIT", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MPMF_MOAOP_VENDED_HABILITRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_CUIT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_SOCIEDAD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_USUARIO;
        
        public SI_MPMF_MOAOP_VENDED_HABILITRequest() {
        }
        
        public SI_MPMF_MOAOP_VENDED_HABILITRequest(string IM_CUIT, string IM_SOCIEDAD, string IM_USUARIO) {
            this.IM_CUIT = IM_CUIT;
            this.IM_SOCIEDAD = IM_SOCIEDAD;
            this.IM_USUARIO = IM_USUARIO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MPMF_MOAOP_VENDED_HABILIT.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MPMF_MOAOP_VENDED_HABILITResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.VendedorHabilitadoWebServiceMOA.ZMPTE3420[] PT_ACTIVIDAD_PROV;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STATUS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=2)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.VendedorHabilitadoWebServiceMOA.ZMPES4470[] T_CABE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=3)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.VendedorHabilitadoWebServiceMOA.ZMPES4430[] T_CONVENIO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=4)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.VendedorHabilitadoWebServiceMOA.ZMPES4450[] T_EXECIONES;
        
        public SI_MPMF_MOAOP_VENDED_HABILITResponse() {
        }
        
        public SI_MPMF_MOAOP_VENDED_HABILITResponse(SustitucionMOAWS.VendedorHabilitadoWebServiceMOA.ZMPTE3420[] PT_ACTIVIDAD_PROV, string STATUS, SustitucionMOAWS.VendedorHabilitadoWebServiceMOA.ZMPES4470[] T_CABE, SustitucionMOAWS.VendedorHabilitadoWebServiceMOA.ZMPES4430[] T_CONVENIO, SustitucionMOAWS.VendedorHabilitadoWebServiceMOA.ZMPES4450[] T_EXECIONES) {
            this.PT_ACTIVIDAD_PROV = PT_ACTIVIDAD_PROV;
            this.STATUS = STATUS;
            this.T_CABE = T_CABE;
            this.T_CONVENIO = T_CONVENIO;
            this.T_EXECIONES = T_EXECIONES;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_MPMF_MOAOP_VENDED_HABILITChannel : SustitucionMOAWS.VendedorHabilitadoWebServiceMOA.SI_MPMF_MOAOP_VENDED_HABILIT, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_MPMF_MOAOP_VENDED_HABILITClient : System.ServiceModel.ClientBase<SustitucionMOAWS.VendedorHabilitadoWebServiceMOA.SI_MPMF_MOAOP_VENDED_HABILIT>, SustitucionMOAWS.VendedorHabilitadoWebServiceMOA.SI_MPMF_MOAOP_VENDED_HABILIT {
        
        public SI_MPMF_MOAOP_VENDED_HABILITClient() {
        }
        
        public SI_MPMF_MOAOP_VENDED_HABILITClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_MPMF_MOAOP_VENDED_HABILITClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MPMF_MOAOP_VENDED_HABILITClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MPMF_MOAOP_VENDED_HABILITClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SustitucionMOAWS.VendedorHabilitadoWebServiceMOA.SI_MPMF_MOAOP_VENDED_HABILITResponse SustitucionMOAWS.VendedorHabilitadoWebServiceMOA.SI_MPMF_MOAOP_VENDED_HABILIT.SI_MPMF_MOAOP_VENDED_HABILIT(SustitucionMOAWS.VendedorHabilitadoWebServiceMOA.SI_MPMF_MOAOP_VENDED_HABILITRequest request) {
            return base.Channel.SI_MPMF_MOAOP_VENDED_HABILIT(request);
        }
        
        public SustitucionMOAWS.VendedorHabilitadoWebServiceMOA.ZMPTE3420[] SI_MPMF_MOAOP_VENDED_HABILIT(string IM_CUIT, string IM_SOCIEDAD, string IM_USUARIO, out string STATUS, out SustitucionMOAWS.VendedorHabilitadoWebServiceMOA.ZMPES4470[] T_CABE, out SustitucionMOAWS.VendedorHabilitadoWebServiceMOA.ZMPES4430[] T_CONVENIO, out SustitucionMOAWS.VendedorHabilitadoWebServiceMOA.ZMPES4450[] T_EXECIONES) {
            SustitucionMOAWS.VendedorHabilitadoWebServiceMOA.SI_MPMF_MOAOP_VENDED_HABILITRequest inValue = new SustitucionMOAWS.VendedorHabilitadoWebServiceMOA.SI_MPMF_MOAOP_VENDED_HABILITRequest();
            inValue.IM_CUIT = IM_CUIT;
            inValue.IM_SOCIEDAD = IM_SOCIEDAD;
            inValue.IM_USUARIO = IM_USUARIO;
            SustitucionMOAWS.VendedorHabilitadoWebServiceMOA.SI_MPMF_MOAOP_VENDED_HABILITResponse retVal = ((SustitucionMOAWS.VendedorHabilitadoWebServiceMOA.SI_MPMF_MOAOP_VENDED_HABILIT)(this)).SI_MPMF_MOAOP_VENDED_HABILIT(inValue);
            STATUS = retVal.STATUS;
            T_CABE = retVal.T_CABE;
            T_CONVENIO = retVal.T_CONVENIO;
            T_EXECIONES = retVal.T_EXECIONES;
            return retVal.PT_ACTIVIDAD_PROV;
        }
        
        public System.Threading.Tasks.Task<SustitucionMOAWS.VendedorHabilitadoWebServiceMOA.SI_MPMF_MOAOP_VENDED_HABILITResponse> SI_MPMF_MOAOP_VENDED_HABILITAsync(SustitucionMOAWS.VendedorHabilitadoWebServiceMOA.SI_MPMF_MOAOP_VENDED_HABILITRequest request) {
            return base.Channel.SI_MPMF_MOAOP_VENDED_HABILITAsync(request);
        }
    }
}
