//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SustitucionMOAWS.ContratoPDFWebServiceMOA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:OPERACIONES", ConfigurationName="ContratoPDFWebServiceMOA.SI_MPMF_MOAOP_PDF_CONTRATO")]
    public interface SI_MPMF_MOAOP_PDF_CONTRATO {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SustitucionMOAWS.ContratoPDFWebServiceMOA.SI_MPMF_MOAOP_PDF_CONTRATOResponse SI_MPMF_MOAOP_PDF_CONTRATO(SustitucionMOAWS.ContratoPDFWebServiceMOA.SI_MPMF_MOAOP_PDF_CONTRATORequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SustitucionMOAWS.ContratoPDFWebServiceMOA.SI_MPMF_MOAOP_PDF_CONTRATOResponse> SI_MPMF_MOAOP_PDF_CONTRATOAsync(SustitucionMOAWS.ContratoPDFWebServiceMOA.SI_MPMF_MOAOP_PDF_CONTRATORequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES4910 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cODIGOField;
        
        private string dESCRIPCIONField;
        
        private string tIPOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CODIGO {
            get {
                return this.cODIGOField;
            }
            set {
                this.cODIGOField = value;
                this.RaisePropertyChanged("CODIGO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
                this.RaisePropertyChanged("DESCRIPCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TIPO {
            get {
                return this.tIPOField;
            }
            set {
                this.tIPOField = value;
                this.RaisePropertyChanged("TIPO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ITCOO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tDPRINTCOMField;
        
        private string tDPRINTPARField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TDPRINTCOM {
            get {
                return this.tDPRINTCOMField;
            }
            set {
                this.tDPRINTCOMField = value;
                this.RaisePropertyChanged("TDPRINTCOM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TDPRINTPAR {
            get {
                return this.tDPRINTPARField;
            }
            set {
                this.tDPRINTPARField = value;
                this.RaisePropertyChanged("TDPRINTPAR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MPMF_MOAOP_PDF_CONTRATO", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MPMF_MOAOP_PDF_CONTRATORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_CONTRATO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_PROVEEDOR;
        
        public SI_MPMF_MOAOP_PDF_CONTRATORequest() {
        }
        
        public SI_MPMF_MOAOP_PDF_CONTRATORequest(string IM_CONTRATO, string IM_PROVEEDOR) {
            this.IM_CONTRATO = IM_CONTRATO;
            this.IM_PROVEEDOR = IM_PROVEEDOR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MPMF_MOAOP_PDF_CONTRATO.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MPMF_MOAOP_PDF_CONTRATOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SustitucionMOAWS.ContratoPDFWebServiceMOA.ZMPES4910 EX_MENSAJE_ERROR;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.ContratoPDFWebServiceMOA.ITCOO[] EX_OTF;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] EX_PDF;
        
        public SI_MPMF_MOAOP_PDF_CONTRATOResponse() {
        }
        
        public SI_MPMF_MOAOP_PDF_CONTRATOResponse(SustitucionMOAWS.ContratoPDFWebServiceMOA.ZMPES4910 EX_MENSAJE_ERROR, SustitucionMOAWS.ContratoPDFWebServiceMOA.ITCOO[] EX_OTF, byte[] EX_PDF) {
            this.EX_MENSAJE_ERROR = EX_MENSAJE_ERROR;
            this.EX_OTF = EX_OTF;
            this.EX_PDF = EX_PDF;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_MPMF_MOAOP_PDF_CONTRATOChannel : SustitucionMOAWS.ContratoPDFWebServiceMOA.SI_MPMF_MOAOP_PDF_CONTRATO, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_MPMF_MOAOP_PDF_CONTRATOClient : System.ServiceModel.ClientBase<SustitucionMOAWS.ContratoPDFWebServiceMOA.SI_MPMF_MOAOP_PDF_CONTRATO>, SustitucionMOAWS.ContratoPDFWebServiceMOA.SI_MPMF_MOAOP_PDF_CONTRATO {
        
        public SI_MPMF_MOAOP_PDF_CONTRATOClient() {
        }
        
        public SI_MPMF_MOAOP_PDF_CONTRATOClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_MPMF_MOAOP_PDF_CONTRATOClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MPMF_MOAOP_PDF_CONTRATOClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MPMF_MOAOP_PDF_CONTRATOClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SustitucionMOAWS.ContratoPDFWebServiceMOA.SI_MPMF_MOAOP_PDF_CONTRATOResponse SustitucionMOAWS.ContratoPDFWebServiceMOA.SI_MPMF_MOAOP_PDF_CONTRATO.SI_MPMF_MOAOP_PDF_CONTRATO(SustitucionMOAWS.ContratoPDFWebServiceMOA.SI_MPMF_MOAOP_PDF_CONTRATORequest request) {
            return base.Channel.SI_MPMF_MOAOP_PDF_CONTRATO(request);
        }
        
        public SustitucionMOAWS.ContratoPDFWebServiceMOA.ZMPES4910 SI_MPMF_MOAOP_PDF_CONTRATO(string IM_CONTRATO, string IM_PROVEEDOR, out SustitucionMOAWS.ContratoPDFWebServiceMOA.ITCOO[] EX_OTF, out byte[] EX_PDF) {
            SustitucionMOAWS.ContratoPDFWebServiceMOA.SI_MPMF_MOAOP_PDF_CONTRATORequest inValue = new SustitucionMOAWS.ContratoPDFWebServiceMOA.SI_MPMF_MOAOP_PDF_CONTRATORequest();
            inValue.IM_CONTRATO = IM_CONTRATO;
            inValue.IM_PROVEEDOR = IM_PROVEEDOR;
            SustitucionMOAWS.ContratoPDFWebServiceMOA.SI_MPMF_MOAOP_PDF_CONTRATOResponse retVal = ((SustitucionMOAWS.ContratoPDFWebServiceMOA.SI_MPMF_MOAOP_PDF_CONTRATO)(this)).SI_MPMF_MOAOP_PDF_CONTRATO(inValue);
            EX_OTF = retVal.EX_OTF;
            EX_PDF = retVal.EX_PDF;
            return retVal.EX_MENSAJE_ERROR;
        }
        
        public System.Threading.Tasks.Task<SustitucionMOAWS.ContratoPDFWebServiceMOA.SI_MPMF_MOAOP_PDF_CONTRATOResponse> SI_MPMF_MOAOP_PDF_CONTRATOAsync(SustitucionMOAWS.ContratoPDFWebServiceMOA.SI_MPMF_MOAOP_PDF_CONTRATORequest request) {
            return base.Channel.SI_MPMF_MOAOP_PDF_CONTRATOAsync(request);
        }
    }
}
