//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SustitucionMOAWS.ObtenerFuenteAprovisionamientoWebServiceMOA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:OPERACIONES", ConfigurationName="ObtenerFuenteAprovisionamientoWebServiceMOA.SI_MMRFC_OBTENER_FUENTE_APROV")]
    public interface SI_MMRFC_OBTENER_FUENTE_APROV {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SustitucionMOAWS.ObtenerFuenteAprovisionamientoWebServiceMOA.SI_MMRFC_OBTENER_FUENTE_APROVResponse SI_MMRFC_OBTENER_FUENTE_APROV(SustitucionMOAWS.ObtenerFuenteAprovisionamientoWebServiceMOA.SI_MMRFC_OBTENER_FUENTE_APROVRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SustitucionMOAWS.ObtenerFuenteAprovisionamientoWebServiceMOA.SI_MMRFC_OBTENER_FUENTE_APROVResponse> SI_MMRFC_OBTENER_FUENTE_APROVAsync(SustitucionMOAWS.ObtenerFuenteAprovisionamientoWebServiceMOA.SI_MMRFC_OBTENER_FUENTE_APROVRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES5850 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fIXED_VENDField;
        
        private string nAM_VENDORField;
        
        private string sUPPL_PLNTField;
        
        private string aGREEMENTField;
        
        private string aGMT_ITEMField;
        
        private string iNFO_RECField;
        
        private string dOC_CATField;
        
        private string pURCH_ORGField;
        
        private string pO_UNITField;
        
        private string iTEM_CATField;
        
        private string mATERIALField;
        
        private string iTEM_CAT_EXTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FIXED_VEND {
            get {
                return this.fIXED_VENDField;
            }
            set {
                this.fIXED_VENDField = value;
                this.RaisePropertyChanged("FIXED_VEND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NAM_VENDOR {
            get {
                return this.nAM_VENDORField;
            }
            set {
                this.nAM_VENDORField = value;
                this.RaisePropertyChanged("NAM_VENDOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string SUPPL_PLNT {
            get {
                return this.sUPPL_PLNTField;
            }
            set {
                this.sUPPL_PLNTField = value;
                this.RaisePropertyChanged("SUPPL_PLNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string AGREEMENT {
            get {
                return this.aGREEMENTField;
            }
            set {
                this.aGREEMENTField = value;
                this.RaisePropertyChanged("AGREEMENT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string AGMT_ITEM {
            get {
                return this.aGMT_ITEMField;
            }
            set {
                this.aGMT_ITEMField = value;
                this.RaisePropertyChanged("AGMT_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string INFO_REC {
            get {
                return this.iNFO_RECField;
            }
            set {
                this.iNFO_RECField = value;
                this.RaisePropertyChanged("INFO_REC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string DOC_CAT {
            get {
                return this.dOC_CATField;
            }
            set {
                this.dOC_CATField = value;
                this.RaisePropertyChanged("DOC_CAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string PURCH_ORG {
            get {
                return this.pURCH_ORGField;
            }
            set {
                this.pURCH_ORGField = value;
                this.RaisePropertyChanged("PURCH_ORG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string PO_UNIT {
            get {
                return this.pO_UNITField;
            }
            set {
                this.pO_UNITField = value;
                this.RaisePropertyChanged("PO_UNIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ITEM_CAT {
            get {
                return this.iTEM_CATField;
            }
            set {
                this.iTEM_CATField = value;
                this.RaisePropertyChanged("ITEM_CAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string MATERIAL {
            get {
                return this.mATERIALField;
            }
            set {
                this.mATERIALField = value;
                this.RaisePropertyChanged("MATERIAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ITEM_CAT_EXT {
            get {
                return this.iTEM_CAT_EXTField;
            }
            set {
                this.iTEM_CAT_EXTField = value;
                this.RaisePropertyChanged("ITEM_CAT_EXT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPIRETURN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string cODEField;
        
        private string mESSAGEField;
        
        private string lOG_NOField;
        
        private string lOG_MSG_NOField;
        
        private string mESSAGE_V1Field;
        
        private string mESSAGE_V2Field;
        
        private string mESSAGE_V3Field;
        
        private string mESSAGE_V4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CODE {
            get {
                return this.cODEField;
            }
            set {
                this.cODEField = value;
                this.RaisePropertyChanged("CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string LOG_NO {
            get {
                return this.lOG_NOField;
            }
            set {
                this.lOG_NOField = value;
                this.RaisePropertyChanged("LOG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LOG_MSG_NO {
            get {
                return this.lOG_MSG_NOField;
            }
            set {
                this.lOG_MSG_NOField = value;
                this.RaisePropertyChanged("LOG_MSG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string MESSAGE_V1 {
            get {
                return this.mESSAGE_V1Field;
            }
            set {
                this.mESSAGE_V1Field = value;
                this.RaisePropertyChanged("MESSAGE_V1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MESSAGE_V2 {
            get {
                return this.mESSAGE_V2Field;
            }
            set {
                this.mESSAGE_V2Field = value;
                this.RaisePropertyChanged("MESSAGE_V2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MESSAGE_V3 {
            get {
                return this.mESSAGE_V3Field;
            }
            set {
                this.mESSAGE_V3Field = value;
                this.RaisePropertyChanged("MESSAGE_V3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MESSAGE_V4 {
            get {
                return this.mESSAGE_V4Field;
            }
            set {
                this.mESSAGE_V4Field = value;
                this.RaisePropertyChanged("MESSAGE_V4");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MMRFC_OBTENER_FUENTE_APROV", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MMRFC_OBTENER_FUENTE_APROVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_DELIV_DATE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_MATERIAL;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_PLANT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_VENDOR;
        
        public SI_MMRFC_OBTENER_FUENTE_APROVRequest() {
        }
        
        public SI_MMRFC_OBTENER_FUENTE_APROVRequest(string IM_DELIV_DATE, string IM_MATERIAL, string IM_PLANT, string IM_VENDOR) {
            this.IM_DELIV_DATE = IM_DELIV_DATE;
            this.IM_MATERIAL = IM_MATERIAL;
            this.IM_PLANT = IM_PLANT;
            this.IM_VENDOR = IM_VENDOR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MMRFC_OBTENER_FUENTE_APROV.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MMRFC_OBTENER_FUENTE_APROVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EX_EXITO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.ObtenerFuenteAprovisionamientoWebServiceMOA.ZMPES5850[] EX_FUENTE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=2)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SustitucionMOAWS.ObtenerFuenteAprovisionamientoWebServiceMOA.BAPIRETURN[] EX_RETURN;
        
        public SI_MMRFC_OBTENER_FUENTE_APROVResponse() {
        }
        
        public SI_MMRFC_OBTENER_FUENTE_APROVResponse(string EX_EXITO, SustitucionMOAWS.ObtenerFuenteAprovisionamientoWebServiceMOA.ZMPES5850[] EX_FUENTE, SustitucionMOAWS.ObtenerFuenteAprovisionamientoWebServiceMOA.BAPIRETURN[] EX_RETURN) {
            this.EX_EXITO = EX_EXITO;
            this.EX_FUENTE = EX_FUENTE;
            this.EX_RETURN = EX_RETURN;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_MMRFC_OBTENER_FUENTE_APROVChannel : SustitucionMOAWS.ObtenerFuenteAprovisionamientoWebServiceMOA.SI_MMRFC_OBTENER_FUENTE_APROV, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_MMRFC_OBTENER_FUENTE_APROVClient : System.ServiceModel.ClientBase<SustitucionMOAWS.ObtenerFuenteAprovisionamientoWebServiceMOA.SI_MMRFC_OBTENER_FUENTE_APROV>, SustitucionMOAWS.ObtenerFuenteAprovisionamientoWebServiceMOA.SI_MMRFC_OBTENER_FUENTE_APROV {
        
        public SI_MMRFC_OBTENER_FUENTE_APROVClient() {
        }
        
        public SI_MMRFC_OBTENER_FUENTE_APROVClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_MMRFC_OBTENER_FUENTE_APROVClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MMRFC_OBTENER_FUENTE_APROVClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MMRFC_OBTENER_FUENTE_APROVClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SustitucionMOAWS.ObtenerFuenteAprovisionamientoWebServiceMOA.SI_MMRFC_OBTENER_FUENTE_APROVResponse SustitucionMOAWS.ObtenerFuenteAprovisionamientoWebServiceMOA.SI_MMRFC_OBTENER_FUENTE_APROV.SI_MMRFC_OBTENER_FUENTE_APROV(SustitucionMOAWS.ObtenerFuenteAprovisionamientoWebServiceMOA.SI_MMRFC_OBTENER_FUENTE_APROVRequest request) {
            return base.Channel.SI_MMRFC_OBTENER_FUENTE_APROV(request);
        }
        
        public string SI_MMRFC_OBTENER_FUENTE_APROV(string IM_DELIV_DATE, string IM_MATERIAL, string IM_PLANT, string IM_VENDOR, out SustitucionMOAWS.ObtenerFuenteAprovisionamientoWebServiceMOA.ZMPES5850[] EX_FUENTE, out SustitucionMOAWS.ObtenerFuenteAprovisionamientoWebServiceMOA.BAPIRETURN[] EX_RETURN) {
            SustitucionMOAWS.ObtenerFuenteAprovisionamientoWebServiceMOA.SI_MMRFC_OBTENER_FUENTE_APROVRequest inValue = new SustitucionMOAWS.ObtenerFuenteAprovisionamientoWebServiceMOA.SI_MMRFC_OBTENER_FUENTE_APROVRequest();
            inValue.IM_DELIV_DATE = IM_DELIV_DATE;
            inValue.IM_MATERIAL = IM_MATERIAL;
            inValue.IM_PLANT = IM_PLANT;
            inValue.IM_VENDOR = IM_VENDOR;
            SustitucionMOAWS.ObtenerFuenteAprovisionamientoWebServiceMOA.SI_MMRFC_OBTENER_FUENTE_APROVResponse retVal = ((SustitucionMOAWS.ObtenerFuenteAprovisionamientoWebServiceMOA.SI_MMRFC_OBTENER_FUENTE_APROV)(this)).SI_MMRFC_OBTENER_FUENTE_APROV(inValue);
            EX_FUENTE = retVal.EX_FUENTE;
            EX_RETURN = retVal.EX_RETURN;
            return retVal.EX_EXITO;
        }
        
        public System.Threading.Tasks.Task<SustitucionMOAWS.ObtenerFuenteAprovisionamientoWebServiceMOA.SI_MMRFC_OBTENER_FUENTE_APROVResponse> SI_MMRFC_OBTENER_FUENTE_APROVAsync(SustitucionMOAWS.ObtenerFuenteAprovisionamientoWebServiceMOA.SI_MMRFC_OBTENER_FUENTE_APROVRequest request) {
            return base.Channel.SI_MMRFC_OBTENER_FUENTE_APROVAsync(request);
        }
    }
}
