//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SustitucionMOAWS.ModificarEntregaOrdenFasV2WebServiceMOA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:OPERACIONES", ConfigurationName="ModificarEntregaOrdenFasV2WebServiceMOA.SI_MPMF_MOAOP_MOD_ENTREGA_V2")]
    public interface SI_MPMF_MOAOP_MOD_ENTREGA_V2 {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:sap-com:document:sap:rfc:functions) of message SI_MPMF_MOAOP_MOD_ENTREGA_V2Request does not match the default value (urn:OPERACIONES)
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SustitucionMOAWS.ModificarEntregaOrdenFasV2WebServiceMOA.SI_MPMF_MOAOP_MOD_ENTREGA_V2Response SI_MPMF_MOAOP_MOD_ENTREGA_V2(SustitucionMOAWS.ModificarEntregaOrdenFasV2WebServiceMOA.SI_MPMF_MOAOP_MOD_ENTREGA_V2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SustitucionMOAWS.ModificarEntregaOrdenFasV2WebServiceMOA.SI_MPMF_MOAOP_MOD_ENTREGA_V2Response> SI_MPMF_MOAOP_MOD_ENTREGA_V2Async(SustitucionMOAWS.ModificarEntregaOrdenFasV2WebServiceMOA.SI_MPMF_MOAOP_MOD_ENTREGA_V2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MPMF_MOAOP_MOD_ENTREGA_V2", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MPMF_MOAOP_MOD_ENTREGA_V2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_ACOPLADO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_BORRAR;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_CHASIS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_CHOFER;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_DOCUMENTO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_ENTREGA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_TIPODOC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_TRANSPORTE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_TRANSPORTISTA_REAL;
        
        public SI_MPMF_MOAOP_MOD_ENTREGA_V2Request() {
        }
        
        public SI_MPMF_MOAOP_MOD_ENTREGA_V2Request(string IM_ACOPLADO, string IM_BORRAR, string IM_CHASIS, string IM_CHOFER, string IM_DOCUMENTO, string IM_ENTREGA, string IM_TIPODOC, string IM_TRANSPORTE, string IM_TRANSPORTISTA_REAL) {
            this.IM_ACOPLADO = IM_ACOPLADO;
            this.IM_BORRAR = IM_BORRAR;
            this.IM_CHASIS = IM_CHASIS;
            this.IM_CHOFER = IM_CHOFER;
            this.IM_DOCUMENTO = IM_DOCUMENTO;
            this.IM_ENTREGA = IM_ENTREGA;
            this.IM_TIPODOC = IM_TIPODOC;
            this.IM_TRANSPORTE = IM_TRANSPORTE;
            this.IM_TRANSPORTISTA_REAL = IM_TRANSPORTISTA_REAL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MPMF_MOAOP_MOD_ENTREGA_V2.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MPMF_MOAOP_MOD_ENTREGA_V2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EX_MENSAJE;
        
        public SI_MPMF_MOAOP_MOD_ENTREGA_V2Response() {
        }
        
        public SI_MPMF_MOAOP_MOD_ENTREGA_V2Response(string EX_MENSAJE) {
            this.EX_MENSAJE = EX_MENSAJE;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_MPMF_MOAOP_MOD_ENTREGA_V2Channel : SustitucionMOAWS.ModificarEntregaOrdenFasV2WebServiceMOA.SI_MPMF_MOAOP_MOD_ENTREGA_V2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_MPMF_MOAOP_MOD_ENTREGA_V2Client : System.ServiceModel.ClientBase<SustitucionMOAWS.ModificarEntregaOrdenFasV2WebServiceMOA.SI_MPMF_MOAOP_MOD_ENTREGA_V2>, SustitucionMOAWS.ModificarEntregaOrdenFasV2WebServiceMOA.SI_MPMF_MOAOP_MOD_ENTREGA_V2 {
        
        public SI_MPMF_MOAOP_MOD_ENTREGA_V2Client() {
        }
        
        public SI_MPMF_MOAOP_MOD_ENTREGA_V2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_MPMF_MOAOP_MOD_ENTREGA_V2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MPMF_MOAOP_MOD_ENTREGA_V2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MPMF_MOAOP_MOD_ENTREGA_V2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SustitucionMOAWS.ModificarEntregaOrdenFasV2WebServiceMOA.SI_MPMF_MOAOP_MOD_ENTREGA_V2Response SustitucionMOAWS.ModificarEntregaOrdenFasV2WebServiceMOA.SI_MPMF_MOAOP_MOD_ENTREGA_V2.SI_MPMF_MOAOP_MOD_ENTREGA_V2(SustitucionMOAWS.ModificarEntregaOrdenFasV2WebServiceMOA.SI_MPMF_MOAOP_MOD_ENTREGA_V2Request request) {
            return base.Channel.SI_MPMF_MOAOP_MOD_ENTREGA_V2(request);
        }
        
        public string SI_MPMF_MOAOP_MOD_ENTREGA_V2(string IM_ACOPLADO, string IM_BORRAR, string IM_CHASIS, string IM_CHOFER, string IM_DOCUMENTO, string IM_ENTREGA, string IM_TIPODOC, string IM_TRANSPORTE, string IM_TRANSPORTISTA_REAL) {
            SustitucionMOAWS.ModificarEntregaOrdenFasV2WebServiceMOA.SI_MPMF_MOAOP_MOD_ENTREGA_V2Request inValue = new SustitucionMOAWS.ModificarEntregaOrdenFasV2WebServiceMOA.SI_MPMF_MOAOP_MOD_ENTREGA_V2Request();
            inValue.IM_ACOPLADO = IM_ACOPLADO;
            inValue.IM_BORRAR = IM_BORRAR;
            inValue.IM_CHASIS = IM_CHASIS;
            inValue.IM_CHOFER = IM_CHOFER;
            inValue.IM_DOCUMENTO = IM_DOCUMENTO;
            inValue.IM_ENTREGA = IM_ENTREGA;
            inValue.IM_TIPODOC = IM_TIPODOC;
            inValue.IM_TRANSPORTE = IM_TRANSPORTE;
            inValue.IM_TRANSPORTISTA_REAL = IM_TRANSPORTISTA_REAL;
            SustitucionMOAWS.ModificarEntregaOrdenFasV2WebServiceMOA.SI_MPMF_MOAOP_MOD_ENTREGA_V2Response retVal = ((SustitucionMOAWS.ModificarEntregaOrdenFasV2WebServiceMOA.SI_MPMF_MOAOP_MOD_ENTREGA_V2)(this)).SI_MPMF_MOAOP_MOD_ENTREGA_V2(inValue);
            return retVal.EX_MENSAJE;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SustitucionMOAWS.ModificarEntregaOrdenFasV2WebServiceMOA.SI_MPMF_MOAOP_MOD_ENTREGA_V2Response> SustitucionMOAWS.ModificarEntregaOrdenFasV2WebServiceMOA.SI_MPMF_MOAOP_MOD_ENTREGA_V2.SI_MPMF_MOAOP_MOD_ENTREGA_V2Async(SustitucionMOAWS.ModificarEntregaOrdenFasV2WebServiceMOA.SI_MPMF_MOAOP_MOD_ENTREGA_V2Request request) {
            return base.Channel.SI_MPMF_MOAOP_MOD_ENTREGA_V2Async(request);
        }
        
        public System.Threading.Tasks.Task<SustitucionMOAWS.ModificarEntregaOrdenFasV2WebServiceMOA.SI_MPMF_MOAOP_MOD_ENTREGA_V2Response> SI_MPMF_MOAOP_MOD_ENTREGA_V2Async(string IM_ACOPLADO, string IM_BORRAR, string IM_CHASIS, string IM_CHOFER, string IM_DOCUMENTO, string IM_ENTREGA, string IM_TIPODOC, string IM_TRANSPORTE, string IM_TRANSPORTISTA_REAL) {
            SustitucionMOAWS.ModificarEntregaOrdenFasV2WebServiceMOA.SI_MPMF_MOAOP_MOD_ENTREGA_V2Request inValue = new SustitucionMOAWS.ModificarEntregaOrdenFasV2WebServiceMOA.SI_MPMF_MOAOP_MOD_ENTREGA_V2Request();
            inValue.IM_ACOPLADO = IM_ACOPLADO;
            inValue.IM_BORRAR = IM_BORRAR;
            inValue.IM_CHASIS = IM_CHASIS;
            inValue.IM_CHOFER = IM_CHOFER;
            inValue.IM_DOCUMENTO = IM_DOCUMENTO;
            inValue.IM_ENTREGA = IM_ENTREGA;
            inValue.IM_TIPODOC = IM_TIPODOC;
            inValue.IM_TRANSPORTE = IM_TRANSPORTE;
            inValue.IM_TRANSPORTISTA_REAL = IM_TRANSPORTISTA_REAL;
            return ((SustitucionMOAWS.ModificarEntregaOrdenFasV2WebServiceMOA.SI_MPMF_MOAOP_MOD_ENTREGA_V2)(this)).SI_MPMF_MOAOP_MOD_ENTREGA_V2Async(inValue);
        }
    }
}
