using SustitucionMOAModel.Consultas;
using SustitucionMOAModel.Dto;
using SustitucionMOAModel.Enums;
using SustitucionMOAModel.Models.WSMapMOA;
using SustitucionMOAModel.Models.WSMapMOA.Compras;
using SustitucionMOAWS.WSConsumers;
using System;
using System.Collections.Generic;
using System.Web;

namespace SustitucionMOAUtils.Interfaces
{
    public interface IComprasService
    {
        RespuestaGuardarSOLP GuardarSolp(SolpDto solp, HttpFileCollectionBase adjuntos);
        string ObtenerRutaArchivo(int archivoId);
        List<TablaSapDto> ObtenerTablaSap(string tabla);
        List<TablaGeneralDto> ObtenerTablaGeneral(string tabla);
        List<CentroDireccionDto> ObtenerCentrosDireccion();
        ListaPaginada<SolpDto> ListarSolp(UsuarioDto usuarioActual, Paginacion paginacion, string nroSolp, DateTime? desde, DateTime? hasta, bool? sap, bool? mantenimiento, bool? web, int? usuarioId, List<int> estados = null);
        string BorrarSolp(int idSolp);
        SolpDto TraerSolpId(int idSolp);
        List<TablaEstadoDto> ObtenerTablaEstado(string tabla);
        byte[] GenerarSolpPdf(int idSolp);
        Pdf GenerarPeticionDeOfertaUsuarioPdf(int idPeticionDeOfertaUsuario);
        string GenerarZipPliego(int idSolp, string pathBase);
        List<TablaSapDto> ObtenerServiciosSap();
        List<TablaSapDto> AutocompleteTablaSap(string tabla, string valor);
        List<TablaSapDto> ObtenerCecoSap();
        List<TablaSapDto> ObtenerCuentasSap();
        List<TablaSapDto> ObtenerOrdenesSap(string idOrder = "");
        List<TablaSapDto> ObtenerDatosPorCodigosSap(List<TablaSapDto> codigos);
        void ActualizarMaterialesSolp();
        void ActualizarFechaLiberacion(string nrosolp, DateTime fechaLiberacion);
        void ActualizarServiciosSolp();
        List<ServicioSolpDto> ObtenerDatosPorCodigosSapServicioSolp(List<string> codigos);
        List<ServicioSolpDto> AutocompleteServicioSolp(string valor);
        List<ServicioSolpDto> AutocompleteCodigoServicioSolp(string valor);
        void ActualizarEstadoSolpBulk();
        List<UsuarioComprasRelacionConUsuariosDto> ListarUsuarioCompras(UsuarioDto usuarioActual);
        void ObtenerSolpesDesdeSAPJob(ObtenerSolpRequest obtenerSolpRequest);
        List<MaterialSolpDto> AutocompleteMaterialSolp(string valor, int centroId);
        List<MaterialSolpDto> AutocompleteCodigoMaterialSolp(string valor, int centroId);
        List<ProvinciaDTO> ListarProvincia();
        void EnviarEmailSolp(EmailComposeDto emailCompose);
        SolpDescargaZipPorLink PuedeDescargarPliegoDesdeLink(int solpId, Guid? token);
        List<FuenteAprovisionamientoDto> ListarFuenteAprovisionamiento(string fechaEntregaPosicion, string numeroMaterial, string centro);
        List<ContratoSolp> ObtenerContratoMarco(string numeroContrato, string centro);
        ListaPaginada<SolpDto> ListarSolpComprador(int usuario_Id, Paginacion paginacion, string nroSolp = null, List<int> usuarios = null, List<int> estados = null, List<int> centros = null, List<int> grupoDeCompras = null);
        List<AsociarContratoDto> DevolverContratosAsociados(List<SolpPosicionDto> posiciones);
        SolpCompraDto ObtenerSolpCompras(int id);
        RespuestaGuardarSOLP GrabarPeticionDeOferta(GuardarPeticionDeOfertaDto peticionDeOferta, HttpFileCollectionBase adjuntos, bool enviarMail, List<RegistroInfoDto> registroInfo);
        List<LegajoDto> ObtenerLegajo(int peticionDeOfertaId, int? idPeticionDeOfertaUsuario);
        Resultado GuardarAdjuntosPeticionDeOferta(int idPeticion, HttpFileCollectionBase files, UsuarioDto usuarioDto);
        string DescargarLegajo(int idPeticion, string path, int? idPeticionDeOfertaUsuario);
        RespuestaGuardarSOLP GrabarCircular(CircularDto circularDto, HttpFileCollectionBase adjuntos);
        PeticionDeOfertaDto ObtenerPeticionDeOfertaParaCircular(int peticionId);
        RespuestaGuardarSOLP GrabarProveedoresEnPeticionDeOferta(List<int> usuariosId, int peticionId);
        ListaPaginada<PeticionDeOfertaDto> ListarPOProveedor(Paginacion paginacion, string nroSolp, string nroPo, string nombrePedido, string username, DateTime? desde, DateTime? hasta, int? estadoLicitacion, int? estadoCotizacion);
        PeticionDeOfertaDto ListarOfertasComprador(int PeticionOferta_Id, UsuarioDto usuario);
        string DescargarAdjuntosCotizacion(int idCotizacion, string pathBase);
        RespuestaGuardarSOLP GrabarRevisionTecnica(List<PeticionDeOfertaUsarioDto> revision, int usuarioId, bool finalizar);
        PeticionDeOfertaDto TraerCotizacion(int peticionId);
        RespuestaGuardarSOLP GrabarCotizacion(GuardarCotizacion cotizacionDto, HttpFileCollectionBase adjuntos, bool esFinalizado, int usuarioActualId, bool enviarMail);
        GuardarCotizacion ObtenerPrecioTotalPosicionProveedor(GuardarCotizacion cotizacionDto);
        RespuestaCrearOrdenDeCompra GrabarAdjudicacion(AdjudicacionDto adjudicacionDto, int usuarioActualId, string mensaje);
        List<AdjudicacionDto> ListarAdjudicaciones(int solpId);
        AdjudicacionDto ObtenerAdjudicacion(int adjudicacionId);
        AdjudicacionDto ObtenerAdjudicacion(string nroOC);
        OrdenDeCompraSAPDto ObtenerOrdenDeCompra(string nroOC);
        List<RespuestaCrearOrdenDeCompra> CrearOrdenDeCompraConRegistroInfo(List<RegistroInfoDto> registros, int usuarioActualId);
        RespuestaGuardarSOLP CerrarCotizacion(int peticionId, int usuarioActualId, string observaciones);
        DatosUltimaSolpDto ObtenerUltimaSolp(int usuarioId);
        RegistroInfoDto ObtenerUltimoRegistroMaterial(string material, string centro, string grupoDeCompras);
        void ActualizarFechaLiberacionOC(string nroOc, DateTime fechaLiberacion);
        LegajoExternoDto ObtenerLegajoParaExternos(int adjudicacionId, string token);
        List<OrdenDeCompraSAPDto> ObtenerReporteOrdenDeCompra(string nroOC, string fechaDesde, string fechaHasta, string codigoProveedor);
        Resultado GrabarPeticionDeOfertaVisualizacionPrecio(PeticionDeOfertaVisualizacionPrecioDto peticionDeOfertaVisualizacionPrecioDto, HttpFileCollectionBase adjuntos);
        ChatComprasDto ObtenerChat(int peticionDeOfertaId, int usuarioActualId);
        Resultado GrabarMensajeChatInterno(ChatInternoComprasDto mensaje);
        string ExportarChatInternoAtexto(int peticionDeOfertaId, string rutaArchivo);
    }
}