//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SustitucionMOAWS.OrdenCargaEntregadaWebServiceMOA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:OPERACIONES", ConfigurationName="OrdenCargaEntregadaWebServiceMOA.SI_MPMF_MOAOP_ORDEN_CARGA_ENTRE")]
    public interface SI_MPMF_MOAOP_ORDEN_CARGA_ENTRE {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SustitucionMOAWS.OrdenCargaEntregadaWebServiceMOA.SI_MPMF_MOAOP_ORDEN_CARGA_ENTREResponse SI_MPMF_MOAOP_ORDEN_CARGA_ENTRE(SustitucionMOAWS.OrdenCargaEntregadaWebServiceMOA.SI_MPMF_MOAOP_ORDEN_CARGA_ENTRERequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SustitucionMOAWS.OrdenCargaEntregadaWebServiceMOA.SI_MPMF_MOAOP_ORDEN_CARGA_ENTREResponse> SI_MPMF_MOAOP_ORDEN_CARGA_ENTREAsync(SustitucionMOAWS.OrdenCargaEntregadaWebServiceMOA.SI_MPMF_MOAOP_ORDEN_CARGA_ENTRERequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MPMF_MOAOP_ORDEN_CARGA_ENTRE", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MPMF_MOAOP_ORDEN_CARGA_ENTRERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_DOCUMENTO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal IM_KILOS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_NOMBRECONDUCTOR;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_PATENTEACOPLADO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_PATENTECHASIS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_PEDIDO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_TIPODOCUMENTO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IM_TRANSPORTISTA;
        
        public SI_MPMF_MOAOP_ORDEN_CARGA_ENTRERequest() {
        }
        
        public SI_MPMF_MOAOP_ORDEN_CARGA_ENTRERequest(string IM_DOCUMENTO, decimal IM_KILOS, string IM_NOMBRECONDUCTOR, string IM_PATENTEACOPLADO, string IM_PATENTECHASIS, string IM_PEDIDO, string IM_TIPODOCUMENTO, string IM_TRANSPORTISTA) {
            this.IM_DOCUMENTO = IM_DOCUMENTO;
            this.IM_KILOS = IM_KILOS;
            this.IM_NOMBRECONDUCTOR = IM_NOMBRECONDUCTOR;
            this.IM_PATENTEACOPLADO = IM_PATENTEACOPLADO;
            this.IM_PATENTECHASIS = IM_PATENTECHASIS;
            this.IM_PEDIDO = IM_PEDIDO;
            this.IM_TIPODOCUMENTO = IM_TIPODOCUMENTO;
            this.IM_TRANSPORTISTA = IM_TRANSPORTISTA;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_MPMF_MOAOP_ORDEN_CARGA_ENTRE.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MPMF_MOAOP_ORDEN_CARGA_ENTREResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EX_ENTREGA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EX_MENSAJE;
        
        public SI_MPMF_MOAOP_ORDEN_CARGA_ENTREResponse() {
        }
        
        public SI_MPMF_MOAOP_ORDEN_CARGA_ENTREResponse(string EX_ENTREGA, string EX_MENSAJE) {
            this.EX_ENTREGA = EX_ENTREGA;
            this.EX_MENSAJE = EX_MENSAJE;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_MPMF_MOAOP_ORDEN_CARGA_ENTREChannel : SustitucionMOAWS.OrdenCargaEntregadaWebServiceMOA.SI_MPMF_MOAOP_ORDEN_CARGA_ENTRE, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_MPMF_MOAOP_ORDEN_CARGA_ENTREClient : System.ServiceModel.ClientBase<SustitucionMOAWS.OrdenCargaEntregadaWebServiceMOA.SI_MPMF_MOAOP_ORDEN_CARGA_ENTRE>, SustitucionMOAWS.OrdenCargaEntregadaWebServiceMOA.SI_MPMF_MOAOP_ORDEN_CARGA_ENTRE {
        
        public SI_MPMF_MOAOP_ORDEN_CARGA_ENTREClient() {
        }
        
        public SI_MPMF_MOAOP_ORDEN_CARGA_ENTREClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_MPMF_MOAOP_ORDEN_CARGA_ENTREClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MPMF_MOAOP_ORDEN_CARGA_ENTREClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MPMF_MOAOP_ORDEN_CARGA_ENTREClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SustitucionMOAWS.OrdenCargaEntregadaWebServiceMOA.SI_MPMF_MOAOP_ORDEN_CARGA_ENTREResponse SustitucionMOAWS.OrdenCargaEntregadaWebServiceMOA.SI_MPMF_MOAOP_ORDEN_CARGA_ENTRE.SI_MPMF_MOAOP_ORDEN_CARGA_ENTRE(SustitucionMOAWS.OrdenCargaEntregadaWebServiceMOA.SI_MPMF_MOAOP_ORDEN_CARGA_ENTRERequest request) {
            return base.Channel.SI_MPMF_MOAOP_ORDEN_CARGA_ENTRE(request);
        }
        
        public string SI_MPMF_MOAOP_ORDEN_CARGA_ENTRE(string IM_DOCUMENTO, decimal IM_KILOS, string IM_NOMBRECONDUCTOR, string IM_PATENTEACOPLADO, string IM_PATENTECHASIS, string IM_PEDIDO, string IM_TIPODOCUMENTO, string IM_TRANSPORTISTA, out string EX_MENSAJE) {
            SustitucionMOAWS.OrdenCargaEntregadaWebServiceMOA.SI_MPMF_MOAOP_ORDEN_CARGA_ENTRERequest inValue = new SustitucionMOAWS.OrdenCargaEntregadaWebServiceMOA.SI_MPMF_MOAOP_ORDEN_CARGA_ENTRERequest();
            inValue.IM_DOCUMENTO = IM_DOCUMENTO;
            inValue.IM_KILOS = IM_KILOS;
            inValue.IM_NOMBRECONDUCTOR = IM_NOMBRECONDUCTOR;
            inValue.IM_PATENTEACOPLADO = IM_PATENTEACOPLADO;
            inValue.IM_PATENTECHASIS = IM_PATENTECHASIS;
            inValue.IM_PEDIDO = IM_PEDIDO;
            inValue.IM_TIPODOCUMENTO = IM_TIPODOCUMENTO;
            inValue.IM_TRANSPORTISTA = IM_TRANSPORTISTA;
            SustitucionMOAWS.OrdenCargaEntregadaWebServiceMOA.SI_MPMF_MOAOP_ORDEN_CARGA_ENTREResponse retVal = ((SustitucionMOAWS.OrdenCargaEntregadaWebServiceMOA.SI_MPMF_MOAOP_ORDEN_CARGA_ENTRE)(this)).SI_MPMF_MOAOP_ORDEN_CARGA_ENTRE(inValue);
            EX_MENSAJE = retVal.EX_MENSAJE;
            return retVal.EX_ENTREGA;
        }
        
        public System.Threading.Tasks.Task<SustitucionMOAWS.OrdenCargaEntregadaWebServiceMOA.SI_MPMF_MOAOP_ORDEN_CARGA_ENTREResponse> SI_MPMF_MOAOP_ORDEN_CARGA_ENTREAsync(SustitucionMOAWS.OrdenCargaEntregadaWebServiceMOA.SI_MPMF_MOAOP_ORDEN_CARGA_ENTRERequest request) {
            return base.Channel.SI_MPMF_MOAOP_ORDEN_CARGA_ENTREAsync(request);
        }
    }
}
